// Copyright (c) 2025 worldiety GmbH
//
// This file is part of the NAGO Low-Code Platform.
// Licensed under the terms specified in the LICENSE file.
//
// SPDX-License-Identifier: Custom-License

package oas

type SecurityScheme struct {
	// any: REQUIRED. The type of the security scheme. Valid values are "apiKey", "http", "mutualTLS", "oauth2", "openIdConnect".
	Type string `json:"type"`

	// any: A description for security scheme. CommonMark syntax MAY be used for rich text representation.
	Description string `json:"description,omitempty"`

	// apiKey: REQUIRED. The name of the header, query or cookie parameter to be used.
	Name string `json:"name"`

	// apiKey: REQUIRED. The location of the API key. Valid values are "query", "header", or "cookie".
	In string `json:"in,omitempty"`

	// apiKey: REQUIRED. The name of the HTTP Authentication scheme to be used in the Authorization header as defined in RFC7235. The values used SHOULD be registered in the IANA Authentication Scheme registry. The value is case-insensitive, as defined in RFC7235.
	Scheme string `json:"scheme"`

	// http "bearer": A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes.
	BearerFormat string `json:"bearerFormat,omitempty"`
}
