// Code generated by cmd/embed-icons. DO NOT EDIT.

package icons

import (
	_ "embed"
	"go.wdy.de/nago/presentation/ora"
)

//go:embed address-book.svg
var AddressBook ora.SVG

//go:embed adjustments-horizontal.svg
var AdjustmentsHorizontal ora.SVG

//go:embed adjustments-vertical.svg
var AdjustmentsVertical ora.SVG

//go:embed align-center.svg
var AlignCenter ora.SVG

//go:embed angle-down.svg
var AngleDown ora.SVG

//go:embed angle-left.svg
var AngleLeft ora.SVG

//go:embed angle-right.svg
var AngleRight ora.SVG

//go:embed angle-up.svg
var AngleUp ora.SVG

//go:embed annotation.svg
var Annotation ora.SVG

//go:embed archive-arrow-down.svg
var ArchiveArrowDown ora.SVG

//go:embed archive.svg
var Archive ora.SVG

//go:embed arrow-down-to-bracket.svg
var ArrowDownToBracket ora.SVG

//go:embed arrow-down.svg
var ArrowDown ora.SVG

//go:embed arrow-left-to-bracket.svg
var ArrowLeftToBracket ora.SVG

//go:embed arrow-left.svg
var ArrowLeft ora.SVG

//go:embed arrow-right-alt.svg
var ArrowRightAlt ora.SVG

//go:embed arrow-right-to-bracket.svg
var ArrowRightToBracket ora.SVG

//go:embed arrow-right.svg
var ArrowRight ora.SVG

//go:embed arrow-sort-letters.svg
var ArrowSortLetters ora.SVG

//go:embed arrow-up-down.svg
var ArrowUpDown ora.SVG

//go:embed arrow-up-from-bracket.svg
var ArrowUpFromBracket ora.SVG

//go:embed arrow-up-right-down-left.svg
var ArrowUpRightDownLeft ora.SVG

//go:embed arrow-up-right-from-square.svg
var ArrowUpRightFromSquare ora.SVG

//go:embed arrow-up.svg
var ArrowUp ora.SVG

//go:embed arrows-repeat-count.svg
var ArrowsRepeatCount ora.SVG

//go:embed arrows-repeat.svg
var ArrowsRepeat ora.SVG

//go:embed atom.svg
var Atom ora.SVG

//go:embed award.svg
var Award ora.SVG

//go:embed backward-step.svg
var BackwardStep ora.SVG

//go:embed badge-check.svg
var BadgeCheck ora.SVG

//go:embed ban.svg
var Ban ora.SVG

//go:embed bars-from-left.svg
var BarsFromLeft ora.SVG

//go:embed bars.svg
var Bars ora.SVG

//go:embed bell-active-alt.svg
var BellActiveAlt ora.SVG

//go:embed bell-active.svg
var BellActive ora.SVG

//go:embed bell-ring.svg
var BellRing ora.SVG

//go:embed bell.svg
var Bell ora.SVG

//go:embed blender-phone.svg
var BlenderPhone ora.SVG

//go:embed book-open.svg
var BookOpen ora.SVG

//go:embed book.svg
var Book ora.SVG

//go:embed bookmark.svg
var Bookmark ora.SVG

//go:embed brain.svg
var Brain ora.SVG

//go:embed briefcase.svg
var Briefcase ora.SVG

//go:embed bug.svg
var Bug ora.SVG

//go:embed building.svg
var Building ora.SVG

//go:embed bullhorn.svg
var Bullhorn ora.SVG

//go:embed calendar-edit.svg
var CalendarEdit ora.SVG

//go:embed calendar-month.svg
var CalendarMonth ora.SVG

//go:embed calendar-plus.svg
var CalendarPlus ora.SVG

//go:embed calendar-week.svg
var CalendarWeek ora.SVG

//go:embed camera-photo.svg
var CameraPhoto ora.SVG

//go:embed caption.svg
var Caption ora.SVG

//go:embed caret-down.svg
var CaretDown ora.SVG

//go:embed caret-left.svg
var CaretLeft ora.SVG

//go:embed caret-right.svg
var CaretRight ora.SVG

//go:embed caret-sort.svg
var CaretSort ora.SVG

//go:embed caret-up.svg
var CaretUp ora.SVG

//go:embed cart-plus-alt.svg
var CartPlusAlt ora.SVG

//go:embed cart-plus.svg
var CartPlus ora.SVG

//go:embed cart.svg
var Cart ora.SVG

//go:embed cash.svg
var Cash ora.SVG

//go:embed chart-line-down.svg
var ChartLineDown ora.SVG

//go:embed chart-line-up.svg
var ChartLineUp ora.SVG

//go:embed chart-mixed-dollar.svg
var ChartMixedDollar ora.SVG

//go:embed chart-mixed.svg
var ChartMixed ora.SVG

//go:embed chart-pie.svg
var ChartPie ora.SVG

//go:embed chart.svg
var Chart ora.SVG

//go:embed check-circle.svg
var CheckCircle ora.SVG

//go:embed check-plus-circle.svg
var CheckPlusCircle ora.SVG

//go:embed check.svg
var Check ora.SVG

//go:embed chevron-double-down.svg
var ChevronDoubleDown ora.SVG

//go:embed chevron-double-left.svg
var ChevronDoubleLeft ora.SVG

//go:embed chevron-double-right.svg
var ChevronDoubleRight ora.SVG

//go:embed chevron-double-up.svg
var ChevronDoubleUp ora.SVG

//go:embed chevron-down.svg
var ChevronDown ora.SVG

//go:embed chevron-left.svg
var ChevronLeft ora.SVG

//go:embed chevron-right.svg
var ChevronRight ora.SVG

//go:embed chevron-sort.svg
var ChevronSort ora.SVG

//go:embed chevron-up.svg
var ChevronUp ora.SVG

//go:embed circle-minus.svg
var CircleMinus ora.SVG

//go:embed circle-pause.svg
var CirclePause ora.SVG

//go:embed circle-plus.svg
var CirclePlus ora.SVG

//go:embed clapperboard-play.svg
var ClapperboardPlay ora.SVG

//go:embed clipboard-check.svg
var ClipboardCheck ora.SVG

//go:embed clipboard-clean.svg
var ClipboardClean ora.SVG

//go:embed clipboard-list.svg
var ClipboardList ora.SVG

//go:embed clipboard.svg
var Clipboard ora.SVG

//go:embed clock.svg
var Clock ora.SVG

//go:embed close-circle.svg
var CloseCircle ora.SVG

//go:embed close.svg
var Close ora.SVG

//go:embed cloud-arrow-up.svg
var CloudArrowUp ora.SVG

//go:embed code-branch.svg
var CodeBranch ora.SVG

//go:embed code-fork.svg
var CodeFork ora.SVG

//go:embed code-merge.svg
var CodeMerge ora.SVG

//go:embed code-pull-request.svg
var CodePullRequest ora.SVG

//go:embed code.svg
var Code ora.SVG

//go:embed cog.svg
var Cog ora.SVG

//go:embed column.svg
var Column ora.SVG

//go:embed command.svg
var Command ora.SVG

//go:embed compress.svg
var Compress ora.SVG

//go:embed computer-speaker.svg
var ComputerSpeaker ora.SVG

//go:embed credit-card-plus.svg
var CreditCardPlus ora.SVG

//go:embed credit-card.svg
var CreditCard ora.SVG

//go:embed database.svg
var Database ora.SVG

//go:embed desktop-pc.svg
var DesktopPc ora.SVG

//go:embed dna.svg
var Dna ora.SVG

//go:embed dollar.svg
var Dollar ora.SVG

//go:embed dots-horizontal.svg
var DotsHorizontal ora.SVG

//go:embed dots-vertical.svg
var DotsVertical ora.SVG

//go:embed download.svg
var Download ora.SVG

//go:embed draw-square.svg
var DrawSquare ora.SVG

//go:embed edit.svg
var Edit ora.SVG

//go:embed envelope-open.svg
var EnvelopeOpen ora.SVG

//go:embed envelope.svg
var Envelope ora.SVG

//go:embed euro.svg
var Euro ora.SVG

//go:embed exclamation-circle.svg
var ExclamationCircle ora.SVG

//go:embed expand.svg
var Expand ora.SVG

//go:embed eye-slash.svg
var EyeSlash ora.SVG

//go:embed eye.svg
var Eye ora.SVG

//go:embed face-explode.svg
var FaceExplode ora.SVG

//go:embed face-grin-stars.svg
var FaceGrinStars ora.SVG

//go:embed face-grin.svg
var FaceGrin ora.SVG

//go:embed face-laugh.svg
var FaceLaugh ora.SVG

//go:embed file-chart-bar.svg
var FileChartBar ora.SVG

//go:embed file-check.svg
var FileCheck ora.SVG

//go:embed file-circle-plus.svg
var FileCirclePlus ora.SVG

//go:embed file-clone.svg
var FileClone ora.SVG

//go:embed file-code.svg
var FileCode ora.SVG

//go:embed file-copy-alt.svg
var FileCopyAlt ora.SVG

//go:embed file-copy.svg
var FileCopy ora.SVG

//go:embed file-csv.svg
var FileCsv ora.SVG

//go:embed file-doc.svg
var FileDoc ora.SVG

//go:embed file-export.svg
var FileExport ora.SVG

//go:embed file-image.svg
var FileImage ora.SVG

//go:embed file-import.svg
var FileImport ora.SVG

//go:embed file-invoice.svg
var FileInvoice ora.SVG

//go:embed file-lines.svg
var FileLines ora.SVG

//go:embed file-music.svg
var FileMusic ora.SVG

//go:embed file-paste.svg
var FilePaste ora.SVG

//go:embed file-pdf.svg
var FilePdf ora.SVG

//go:embed file-pen.svg
var FilePen ora.SVG

//go:embed file-ppt.svg
var FilePpt ora.SVG

//go:embed file-search.svg
var FileSearch ora.SVG

//go:embed file-shield.svg
var FileShield ora.SVG

//go:embed file-video.svg
var FileVideo ora.SVG

//go:embed file-word.svg
var FileWord ora.SVG

//go:embed file-zip.svg
var FileZip ora.SVG

//go:embed file.svg
var File ora.SVG

//go:embed filter.svg
var Filter ora.SVG

//go:embed fingerprint.svg
var Fingerprint ora.SVG

//go:embed fire.svg
var Fire ora.SVG

//go:embed flag.svg
var Flag ora.SVG

//go:embed floppy-disk-alt.svg
var FloppyDiskAlt ora.SVG

//go:embed floppy-disk.svg
var FloppyDisk ora.SVG

//go:embed folder-arrow-right.svg
var FolderArrowRight ora.SVG

//go:embed folder-duplicate.svg
var FolderDuplicate ora.SVG

//go:embed folder-open.svg
var FolderOpen ora.SVG

//go:embed folder-plus.svg
var FolderPlus ora.SVG

//go:embed folder.svg
var Folder ora.SVG

//go:embed forward-step.svg
var ForwardStep ora.SVG

//go:embed forward.svg
var Forward ora.SVG

//go:embed gift-box.svg
var GiftBox ora.SVG

//go:embed globe.svg
var Globe ora.SVG

//go:embed grid-plus.svg
var GridPlus ora.SVG

//go:embed grid.svg
var Grid ora.SVG

//go:embed headphones.svg
var Headphones ora.SVG

//go:embed heart.svg
var Heart ora.SVG

//go:embed home.svg
var Home ora.SVG

//go:embed hourglass.svg
var Hourglass ora.SVG

//go:embed image.svg
var Image ora.SVG

//go:embed inbox-full.svg
var InboxFull ora.SVG

//go:embed inbox.svg
var Inbox ora.SVG

//go:embed indent.svg
var Indent ora.SVG

//go:embed info-circle.svg
var InfoCircle ora.SVG

//go:embed keyboard.svg
var Keyboard ora.SVG

//go:embed label.svg
var Label ora.SVG

//go:embed landmark.svg
var Landmark ora.SVG

//go:embed language.svg
var Language ora.SVG

//go:embed layers.svg
var Layers ora.SVG

//go:embed letter-bold.svg
var LetterBold ora.SVG

//go:embed letter-italic.svg
var LetterItalic ora.SVG

//go:embed letter-underline.svg
var LetterUnderline ora.SVG

//go:embed life-saver.svg
var LifeSaver ora.SVG

//go:embed lightbulb.svg
var Lightbulb ora.SVG

//go:embed link.svg
var Link ora.SVG

//go:embed list-music.svg
var ListMusic ora.SVG

//go:embed list.svg
var List ora.SVG

//go:embed lock-open.svg
var LockOpen ora.SVG

//go:embed lock-time.svg
var LockTime ora.SVG

//go:embed lock.svg
var Lock ora.SVG

//go:embed mail-box.svg
var MailBox ora.SVG

//go:embed map-pin-alt.svg
var MapPinAlt ora.SVG

//go:embed map-pin.svg
var MapPin ora.SVG

//go:embed message-caption.svg
var MessageCaption ora.SVG

//go:embed message-dots.svg
var MessageDots ora.SVG

//go:embed messages.svg
var Messages ora.SVG

//go:embed microphone-slash.svg
var MicrophoneSlash ora.SVG

//go:embed microphone.svg
var Microphone ora.SVG

//go:embed minimize.svg
var Minimize ora.SVG

//go:embed minus.svg
var Minus ora.SVG

//go:embed mobile-phone.svg
var MobilePhone ora.SVG

//go:embed moon.svg
var Moon ora.SVG

//go:embed newspaper.svg
var Newspaper ora.SVG

//go:embed objects-column.svg
var ObjectsColumn ora.SVG

//go:embed ordered-list.svg
var OrderedList ora.SVG

//go:embed outdent.svg
var Outdent ora.SVG

//go:embed palette.svg
var Palette ora.SVG

//go:embed paper-clip.svg
var PaperClip ora.SVG

//go:embed paper-plane.svg
var PaperPlane ora.SVG

//go:embed paragraph.svg
var Paragraph ora.SVG

//go:embed pause.svg
var Pause ora.SVG

//go:embed pen-nib.svg
var PenNib ora.SVG

//go:embed pen.svg
var Pen ora.SVG

//go:embed phone-hangup.svg
var PhoneHangup ora.SVG

//go:embed phone.svg
var Phone ora.SVG

//go:embed play.svg
var Play ora.SVG

//go:embed plus.svg
var Plus ora.SVG

//go:embed printer.svg
var Printer ora.SVG

//go:embed profile-card.svg
var ProfileCard ora.SVG

//go:embed qr-code.svg
var QrCode ora.SVG

//go:embed question-circle.svg
var QuestionCircle ora.SVG

//go:embed quote.svg
var Quote ora.SVG

//go:embed receipt.svg
var Receipt ora.SVG

//go:embed rectangle-list.svg
var RectangleList ora.SVG

//go:embed redo.svg
var Redo ora.SVG

//go:embed refresh.svg
var Refresh ora.SVG

//go:embed reply-all.svg
var ReplyAll ora.SVG

//go:embed reply.svg
var Reply ora.SVG

//go:embed restore-window.svg
var RestoreWindow ora.SVG

//go:embed rocket.svg
var Rocket ora.SVG

//go:embed ruler-combined.svg
var RulerCombined ora.SVG

//go:embed sale-percent.svg
var SalePercent ora.SVG

//go:embed scale-balanced.svg
var ScaleBalanced ora.SVG

//go:embed search.svg
var Search ora.SVG

//go:embed server.svg
var Server ora.SVG

//go:embed share-all.svg
var ShareAll ora.SVG

//go:embed share-nodes.svg
var ShareNodes ora.SVG

//go:embed shield-check.svg
var ShieldCheck ora.SVG

//go:embed shield.svg
var Shield ora.SVG

//go:embed shopping-bag.svg
var ShoppingBag ora.SVG

//go:embed shuffle.svg
var Shuffle ora.SVG

//go:embed sort-horizontal.svg
var SortHorizontal ora.SVG

//go:embed sort.svg
var Sort ora.SVG

//go:embed star-half-stroke.svg
var StarHalfStroke ora.SVG

//go:embed star-half.svg
var StarHalf ora.SVG

//go:embed star.svg
var Star ora.SVG

//go:embed stop.svg
var Stop ora.SVG

//go:embed store.svg
var Store ora.SVG

//go:embed sun.svg
var Sun ora.SVG

//go:embed swatchbook.svg
var Swatchbook ora.SVG

//go:embed table-column.svg
var TableColumn ora.SVG

//go:embed table-row.svg
var TableRow ora.SVG

//go:embed tablet.svg
var Tablet ora.SVG

//go:embed tag.svg
var Tag ora.SVG

//go:embed terminal.svg
var Terminal ora.SVG

//go:embed text-size.svg
var TextSize ora.SVG

//go:embed text-slash.svg
var TextSlash ora.SVG

//go:embed thumbs-down.svg
var ThumbsDown ora.SVG

//go:embed thumbs-up.svg
var ThumbsUp ora.SVG

//go:embed ticket.svg
var Ticket ora.SVG

//go:embed trash-bin.svg
var TrashBin ora.SVG

//go:embed truck.svg
var Truck ora.SVG

//go:embed undo.svg
var Undo ora.SVG

//go:embed upload.svg
var Upload ora.SVG

//go:embed user-add.svg
var UserAdd ora.SVG

//go:embed user-circle.svg
var UserCircle ora.SVG

//go:embed user-edit.svg
var UserEdit ora.SVG

//go:embed user-headset.svg
var UserHeadset ora.SVG

//go:embed user-remove.svg
var UserRemove ora.SVG

//go:embed user-settings.svg
var UserSettings ora.SVG

//go:embed user.svg
var User ora.SVG

//go:embed users-group.svg
var UsersGroup ora.SVG

//go:embed users.svg
var Users ora.SVG

//go:embed video-camera.svg
var VideoCamera ora.SVG

//go:embed volume-down.svg
var VolumeDown ora.SVG

//go:embed volume-mute.svg
var VolumeMute ora.SVG

//go:embed volume-up.svg
var VolumeUp ora.SVG

//go:embed wallet.svg
var Wallet ora.SVG

//go:embed wand-magic-sparkles.svg
var WandMagicSparkles ora.SVG

//go:embed window.svg
var Window ora.SVG

//go:embed zoom-in.svg
var ZoomIn ora.SVG

//go:embed zoom-out.svg
var ZoomOut ora.SVG

var All = map[string]ora.SVG{
	"AddressBook":            AddressBook,
	"AdjustmentsHorizontal":  AdjustmentsHorizontal,
	"AdjustmentsVertical":    AdjustmentsVertical,
	"AlignCenter":            AlignCenter,
	"AngleDown":              AngleDown,
	"AngleLeft":              AngleLeft,
	"AngleRight":             AngleRight,
	"AngleUp":                AngleUp,
	"Annotation":             Annotation,
	"ArchiveArrowDown":       ArchiveArrowDown,
	"Archive":                Archive,
	"ArrowDownToBracket":     ArrowDownToBracket,
	"ArrowDown":              ArrowDown,
	"ArrowLeftToBracket":     ArrowLeftToBracket,
	"ArrowLeft":              ArrowLeft,
	"ArrowRightAlt":          ArrowRightAlt,
	"ArrowRightToBracket":    ArrowRightToBracket,
	"ArrowRight":             ArrowRight,
	"ArrowSortLetters":       ArrowSortLetters,
	"ArrowUpDown":            ArrowUpDown,
	"ArrowUpFromBracket":     ArrowUpFromBracket,
	"ArrowUpRightDownLeft":   ArrowUpRightDownLeft,
	"ArrowUpRightFromSquare": ArrowUpRightFromSquare,
	"ArrowUp":                ArrowUp,
	"ArrowsRepeatCount":      ArrowsRepeatCount,
	"ArrowsRepeat":           ArrowsRepeat,
	"Atom":                   Atom,
	"Award":                  Award,
	"BackwardStep":           BackwardStep,
	"BadgeCheck":             BadgeCheck,
	"Ban":                    Ban,
	"BarsFromLeft":           BarsFromLeft,
	"Bars":                   Bars,
	"BellActiveAlt":          BellActiveAlt,
	"BellActive":             BellActive,
	"BellRing":               BellRing,
	"Bell":                   Bell,
	"BlenderPhone":           BlenderPhone,
	"BookOpen":               BookOpen,
	"Book":                   Book,
	"Bookmark":               Bookmark,
	"Brain":                  Brain,
	"Briefcase":              Briefcase,
	"Bug":                    Bug,
	"Building":               Building,
	"Bullhorn":               Bullhorn,
	"CalendarEdit":           CalendarEdit,
	"CalendarMonth":          CalendarMonth,
	"CalendarPlus":           CalendarPlus,
	"CalendarWeek":           CalendarWeek,
	"CameraPhoto":            CameraPhoto,
	"Caption":                Caption,
	"CaretDown":              CaretDown,
	"CaretLeft":              CaretLeft,
	"CaretRight":             CaretRight,
	"CaretSort":              CaretSort,
	"CaretUp":                CaretUp,
	"CartPlusAlt":            CartPlusAlt,
	"CartPlus":               CartPlus,
	"Cart":                   Cart,
	"Cash":                   Cash,
	"ChartLineDown":          ChartLineDown,
	"ChartLineUp":            ChartLineUp,
	"ChartMixedDollar":       ChartMixedDollar,
	"ChartMixed":             ChartMixed,
	"ChartPie":               ChartPie,
	"Chart":                  Chart,
	"CheckCircle":            CheckCircle,
	"CheckPlusCircle":        CheckPlusCircle,
	"Check":                  Check,
	"ChevronDoubleDown":      ChevronDoubleDown,
	"ChevronDoubleLeft":      ChevronDoubleLeft,
	"ChevronDoubleRight":     ChevronDoubleRight,
	"ChevronDoubleUp":        ChevronDoubleUp,
	"ChevronDown":            ChevronDown,
	"ChevronLeft":            ChevronLeft,
	"ChevronRight":           ChevronRight,
	"ChevronSort":            ChevronSort,
	"ChevronUp":              ChevronUp,
	"CircleMinus":            CircleMinus,
	"CirclePause":            CirclePause,
	"CirclePlus":             CirclePlus,
	"ClapperboardPlay":       ClapperboardPlay,
	"ClipboardCheck":         ClipboardCheck,
	"ClipboardClean":         ClipboardClean,
	"ClipboardList":          ClipboardList,
	"Clipboard":              Clipboard,
	"Clock":                  Clock,
	"CloseCircle":            CloseCircle,
	"Close":                  Close,
	"CloudArrowUp":           CloudArrowUp,
	"CodeBranch":             CodeBranch,
	"CodeFork":               CodeFork,
	"CodeMerge":              CodeMerge,
	"CodePullRequest":        CodePullRequest,
	"Code":                   Code,
	"Cog":                    Cog,
	"Column":                 Column,
	"Command":                Command,
	"Compress":               Compress,
	"ComputerSpeaker":        ComputerSpeaker,
	"CreditCardPlus":         CreditCardPlus,
	"CreditCard":             CreditCard,
	"Database":               Database,
	"DesktopPc":              DesktopPc,
	"Dna":                    Dna,
	"Dollar":                 Dollar,
	"DotsHorizontal":         DotsHorizontal,
	"DotsVertical":           DotsVertical,
	"Download":               Download,
	"DrawSquare":             DrawSquare,
	"Edit":                   Edit,
	"EnvelopeOpen":           EnvelopeOpen,
	"Envelope":               Envelope,
	"Euro":                   Euro,
	"ExclamationCircle":      ExclamationCircle,
	"Expand":                 Expand,
	"EyeSlash":               EyeSlash,
	"Eye":                    Eye,
	"FaceExplode":            FaceExplode,
	"FaceGrinStars":          FaceGrinStars,
	"FaceGrin":               FaceGrin,
	"FaceLaugh":              FaceLaugh,
	"FileChartBar":           FileChartBar,
	"FileCheck":              FileCheck,
	"FileCirclePlus":         FileCirclePlus,
	"FileClone":              FileClone,
	"FileCode":               FileCode,
	"FileCopyAlt":            FileCopyAlt,
	"FileCopy":               FileCopy,
	"FileCsv":                FileCsv,
	"FileDoc":                FileDoc,
	"FileExport":             FileExport,
	"FileImage":              FileImage,
	"FileImport":             FileImport,
	"FileInvoice":            FileInvoice,
	"FileLines":              FileLines,
	"FileMusic":              FileMusic,
	"FilePaste":              FilePaste,
	"FilePdf":                FilePdf,
	"FilePen":                FilePen,
	"FilePpt":                FilePpt,
	"FileSearch":             FileSearch,
	"FileShield":             FileShield,
	"FileVideo":              FileVideo,
	"FileWord":               FileWord,
	"FileZip":                FileZip,
	"File":                   File,
	"Filter":                 Filter,
	"Fingerprint":            Fingerprint,
	"Fire":                   Fire,
	"Flag":                   Flag,
	"FloppyDiskAlt":          FloppyDiskAlt,
	"FloppyDisk":             FloppyDisk,
	"FolderArrowRight":       FolderArrowRight,
	"FolderDuplicate":        FolderDuplicate,
	"FolderOpen":             FolderOpen,
	"FolderPlus":             FolderPlus,
	"Folder":                 Folder,
	"ForwardStep":            ForwardStep,
	"Forward":                Forward,
	"GiftBox":                GiftBox,
	"Globe":                  Globe,
	"GridPlus":               GridPlus,
	"Grid":                   Grid,
	"Headphones":             Headphones,
	"Heart":                  Heart,
	"Home":                   Home,
	"Hourglass":              Hourglass,
	"Image":                  Image,
	"InboxFull":              InboxFull,
	"Inbox":                  Inbox,
	"Indent":                 Indent,
	"InfoCircle":             InfoCircle,
	"Keyboard":               Keyboard,
	"Label":                  Label,
	"Landmark":               Landmark,
	"Language":               Language,
	"Layers":                 Layers,
	"LetterBold":             LetterBold,
	"LetterItalic":           LetterItalic,
	"LetterUnderline":        LetterUnderline,
	"LifeSaver":              LifeSaver,
	"Lightbulb":              Lightbulb,
	"Link":                   Link,
	"ListMusic":              ListMusic,
	"List":                   List,
	"LockOpen":               LockOpen,
	"LockTime":               LockTime,
	"Lock":                   Lock,
	"MailBox":                MailBox,
	"MapPinAlt":              MapPinAlt,
	"MapPin":                 MapPin,
	"MessageCaption":         MessageCaption,
	"MessageDots":            MessageDots,
	"Messages":               Messages,
	"MicrophoneSlash":        MicrophoneSlash,
	"Microphone":             Microphone,
	"Minimize":               Minimize,
	"Minus":                  Minus,
	"MobilePhone":            MobilePhone,
	"Moon":                   Moon,
	"Newspaper":              Newspaper,
	"ObjectsColumn":          ObjectsColumn,
	"OrderedList":            OrderedList,
	"Outdent":                Outdent,
	"Palette":                Palette,
	"PaperClip":              PaperClip,
	"PaperPlane":             PaperPlane,
	"Paragraph":              Paragraph,
	"Pause":                  Pause,
	"PenNib":                 PenNib,
	"Pen":                    Pen,
	"PhoneHangup":            PhoneHangup,
	"Phone":                  Phone,
	"Play":                   Play,
	"Plus":                   Plus,
	"Printer":                Printer,
	"ProfileCard":            ProfileCard,
	"QrCode":                 QrCode,
	"QuestionCircle":         QuestionCircle,
	"Quote":                  Quote,
	"Receipt":                Receipt,
	"RectangleList":          RectangleList,
	"Redo":                   Redo,
	"Refresh":                Refresh,
	"ReplyAll":               ReplyAll,
	"Reply":                  Reply,
	"RestoreWindow":          RestoreWindow,
	"Rocket":                 Rocket,
	"RulerCombined":          RulerCombined,
	"SalePercent":            SalePercent,
	"ScaleBalanced":          ScaleBalanced,
	"Search":                 Search,
	"Server":                 Server,
	"ShareAll":               ShareAll,
	"ShareNodes":             ShareNodes,
	"ShieldCheck":            ShieldCheck,
	"Shield":                 Shield,
	"ShoppingBag":            ShoppingBag,
	"Shuffle":                Shuffle,
	"SortHorizontal":         SortHorizontal,
	"Sort":                   Sort,
	"StarHalfStroke":         StarHalfStroke,
	"StarHalf":               StarHalf,
	"Star":                   Star,
	"Stop":                   Stop,
	"Store":                  Store,
	"Sun":                    Sun,
	"Swatchbook":             Swatchbook,
	"TableColumn":            TableColumn,
	"TableRow":               TableRow,
	"Tablet":                 Tablet,
	"Tag":                    Tag,
	"Terminal":               Terminal,
	"TextSize":               TextSize,
	"TextSlash":              TextSlash,
	"ThumbsDown":             ThumbsDown,
	"ThumbsUp":               ThumbsUp,
	"Ticket":                 Ticket,
	"TrashBin":               TrashBin,
	"Truck":                  Truck,
	"Undo":                   Undo,
	"Upload":                 Upload,
	"UserAdd":                UserAdd,
	"UserCircle":             UserCircle,
	"UserEdit":               UserEdit,
	"UserHeadset":            UserHeadset,
	"UserRemove":             UserRemove,
	"UserSettings":           UserSettings,
	"User":                   User,
	"UsersGroup":             UsersGroup,
	"Users":                  Users,
	"VideoCamera":            VideoCamera,
	"VolumeDown":             VolumeDown,
	"VolumeMute":             VolumeMute,
	"VolumeUp":               VolumeUp,
	"Wallet":                 Wallet,
	"WandMagicSparkles":      WandMagicSparkles,
	"Window":                 Window,
	"ZoomIn":                 ZoomIn,
	"ZoomOut":                ZoomOut,
}
