// Code generated by cmd/embed-icons. DO NOT EDIT.

package icons

import (
	_ "embed"
	"go.wdy.de/nago/presentation/core"
)

//go:embed address-book.svg
var AddressBook core.SVG

//go:embed adjustments-horizontal.svg
var AdjustmentsHorizontal core.SVG

//go:embed adjustments-vertical.svg
var AdjustmentsVertical core.SVG

//go:embed align-center.svg
var AlignCenter core.SVG

//go:embed angle-down.svg
var AngleDown core.SVG

//go:embed angle-left.svg
var AngleLeft core.SVG

//go:embed angle-right.svg
var AngleRight core.SVG

//go:embed angle-up.svg
var AngleUp core.SVG

//go:embed annotation.svg
var Annotation core.SVG

//go:embed archive-arrow-down.svg
var ArchiveArrowDown core.SVG

//go:embed archive.svg
var Archive core.SVG

//go:embed arrow-down-to-bracket.svg
var ArrowDownToBracket core.SVG

//go:embed arrow-down.svg
var ArrowDown core.SVG

//go:embed arrow-left-to-bracket.svg
var ArrowLeftToBracket core.SVG

//go:embed arrow-left.svg
var ArrowLeft core.SVG

//go:embed arrow-right-alt.svg
var ArrowRightAlt core.SVG

//go:embed arrow-right-to-bracket.svg
var ArrowRightToBracket core.SVG

//go:embed arrow-right.svg
var ArrowRight core.SVG

//go:embed arrow-sort-letters.svg
var ArrowSortLetters core.SVG

//go:embed arrow-up-down.svg
var ArrowUpDown core.SVG

//go:embed arrow-up-from-bracket.svg
var ArrowUpFromBracket core.SVG

//go:embed arrow-up-right-down-left.svg
var ArrowUpRightDownLeft core.SVG

//go:embed arrow-up-right-from-square.svg
var ArrowUpRightFromSquare core.SVG

//go:embed arrow-up.svg
var ArrowUp core.SVG

//go:embed arrows-repeat-count.svg
var ArrowsRepeatCount core.SVG

//go:embed arrows-repeat.svg
var ArrowsRepeat core.SVG

//go:embed atom.svg
var Atom core.SVG

//go:embed award.svg
var Award core.SVG

//go:embed backward-step.svg
var BackwardStep core.SVG

//go:embed badge-check.svg
var BadgeCheck core.SVG

//go:embed ban.svg
var Ban core.SVG

//go:embed bars-from-left.svg
var BarsFromLeft core.SVG

//go:embed bars.svg
var Bars core.SVG

//go:embed bell-active-alt.svg
var BellActiveAlt core.SVG

//go:embed bell-active.svg
var BellActive core.SVG

//go:embed bell-ring.svg
var BellRing core.SVG

//go:embed bell.svg
var Bell core.SVG

//go:embed blender-phone.svg
var BlenderPhone core.SVG

//go:embed book-open.svg
var BookOpen core.SVG

//go:embed book.svg
var Book core.SVG

//go:embed bookmark.svg
var Bookmark core.SVG

//go:embed brain.svg
var Brain core.SVG

//go:embed briefcase.svg
var Briefcase core.SVG

//go:embed bug.svg
var Bug core.SVG

//go:embed building.svg
var Building core.SVG

//go:embed bullhorn.svg
var Bullhorn core.SVG

//go:embed calendar-edit.svg
var CalendarEdit core.SVG

//go:embed calendar-month.svg
var CalendarMonth core.SVG

//go:embed calendar-plus.svg
var CalendarPlus core.SVG

//go:embed calendar-week.svg
var CalendarWeek core.SVG

//go:embed camera-photo.svg
var CameraPhoto core.SVG

//go:embed caption.svg
var Caption core.SVG

//go:embed caret-down.svg
var CaretDown core.SVG

//go:embed caret-left.svg
var CaretLeft core.SVG

//go:embed caret-right.svg
var CaretRight core.SVG

//go:embed caret-sort.svg
var CaretSort core.SVG

//go:embed caret-up.svg
var CaretUp core.SVG

//go:embed cart-plus-alt.svg
var CartPlusAlt core.SVG

//go:embed cart-plus.svg
var CartPlus core.SVG

//go:embed cart.svg
var Cart core.SVG

//go:embed cash.svg
var Cash core.SVG

//go:embed chart-line-down.svg
var ChartLineDown core.SVG

//go:embed chart-line-up.svg
var ChartLineUp core.SVG

//go:embed chart-mixed-dollar.svg
var ChartMixedDollar core.SVG

//go:embed chart-mixed.svg
var ChartMixed core.SVG

//go:embed chart-pie.svg
var ChartPie core.SVG

//go:embed chart.svg
var Chart core.SVG

//go:embed check-circle.svg
var CheckCircle core.SVG

//go:embed check-plus-circle.svg
var CheckPlusCircle core.SVG

//go:embed check.svg
var Check core.SVG

//go:embed chevron-double-down.svg
var ChevronDoubleDown core.SVG

//go:embed chevron-double-left.svg
var ChevronDoubleLeft core.SVG

//go:embed chevron-double-right.svg
var ChevronDoubleRight core.SVG

//go:embed chevron-double-up.svg
var ChevronDoubleUp core.SVG

//go:embed chevron-down.svg
var ChevronDown core.SVG

//go:embed chevron-left.svg
var ChevronLeft core.SVG

//go:embed chevron-right.svg
var ChevronRight core.SVG

//go:embed chevron-sort.svg
var ChevronSort core.SVG

//go:embed chevron-up.svg
var ChevronUp core.SVG

//go:embed circle-minus.svg
var CircleMinus core.SVG

//go:embed circle-pause.svg
var CirclePause core.SVG

//go:embed circle-plus.svg
var CirclePlus core.SVG

//go:embed clapperboard-play.svg
var ClapperboardPlay core.SVG

//go:embed clipboard-check.svg
var ClipboardCheck core.SVG

//go:embed clipboard-clean.svg
var ClipboardClean core.SVG

//go:embed clipboard-list.svg
var ClipboardList core.SVG

//go:embed clipboard.svg
var Clipboard core.SVG

//go:embed clock.svg
var Clock core.SVG

//go:embed close-circle.svg
var CloseCircle core.SVG

//go:embed close.svg
var Close core.SVG

//go:embed cloud-arrow-up.svg
var CloudArrowUp core.SVG

//go:embed code-branch.svg
var CodeBranch core.SVG

//go:embed code-fork.svg
var CodeFork core.SVG

//go:embed code-merge.svg
var CodeMerge core.SVG

//go:embed code-pull-request.svg
var CodePullRequest core.SVG

//go:embed code.svg
var Code core.SVG

//go:embed cog.svg
var Cog core.SVG

//go:embed column.svg
var Column core.SVG

//go:embed command.svg
var Command core.SVG

//go:embed compress.svg
var Compress core.SVG

//go:embed computer-speaker.svg
var ComputerSpeaker core.SVG

//go:embed credit-card-plus.svg
var CreditCardPlus core.SVG

//go:embed credit-card.svg
var CreditCard core.SVG

//go:embed database.svg
var Database core.SVG

//go:embed desktop-pc.svg
var DesktopPc core.SVG

//go:embed dna.svg
var Dna core.SVG

//go:embed dollar.svg
var Dollar core.SVG

//go:embed dots-horizontal.svg
var DotsHorizontal core.SVG

//go:embed dots-vertical.svg
var DotsVertical core.SVG

//go:embed download.svg
var Download core.SVG

//go:embed draw-square.svg
var DrawSquare core.SVG

//go:embed edit.svg
var Edit core.SVG

//go:embed envelope-open.svg
var EnvelopeOpen core.SVG

//go:embed envelope.svg
var Envelope core.SVG

//go:embed euro.svg
var Euro core.SVG

//go:embed exclamation-circle.svg
var ExclamationCircle core.SVG

//go:embed expand.svg
var Expand core.SVG

//go:embed eye-slash.svg
var EyeSlash core.SVG

//go:embed eye.svg
var Eye core.SVG

//go:embed face-explode.svg
var FaceExplode core.SVG

//go:embed face-grin-stars.svg
var FaceGrinStars core.SVG

//go:embed face-grin.svg
var FaceGrin core.SVG

//go:embed face-laugh.svg
var FaceLaugh core.SVG

//go:embed file-chart-bar.svg
var FileChartBar core.SVG

//go:embed file-check.svg
var FileCheck core.SVG

//go:embed file-circle-plus.svg
var FileCirclePlus core.SVG

//go:embed file-clone.svg
var FileClone core.SVG

//go:embed file-code.svg
var FileCode core.SVG

//go:embed file-copy-alt.svg
var FileCopyAlt core.SVG

//go:embed file-copy.svg
var FileCopy core.SVG

//go:embed file-csv.svg
var FileCsv core.SVG

//go:embed file-doc.svg
var FileDoc core.SVG

//go:embed file-export.svg
var FileExport core.SVG

//go:embed file-image.svg
var FileImage core.SVG

//go:embed file-import.svg
var FileImport core.SVG

//go:embed file-invoice.svg
var FileInvoice core.SVG

//go:embed file-lines.svg
var FileLines core.SVG

//go:embed file-music.svg
var FileMusic core.SVG

//go:embed file-paste.svg
var FilePaste core.SVG

//go:embed file-pdf.svg
var FilePdf core.SVG

//go:embed file-pen.svg
var FilePen core.SVG

//go:embed file-ppt.svg
var FilePpt core.SVG

//go:embed file-search.svg
var FileSearch core.SVG

//go:embed file-shield.svg
var FileShield core.SVG

//go:embed file-video.svg
var FileVideo core.SVG

//go:embed file-word.svg
var FileWord core.SVG

//go:embed file-zip.svg
var FileZip core.SVG

//go:embed file.svg
var File core.SVG

//go:embed filter.svg
var Filter core.SVG

//go:embed fingerprint.svg
var Fingerprint core.SVG

//go:embed fire.svg
var Fire core.SVG

//go:embed flag.svg
var Flag core.SVG

//go:embed floppy-disk-alt.svg
var FloppyDiskAlt core.SVG

//go:embed floppy-disk.svg
var FloppyDisk core.SVG

//go:embed folder-arrow-right.svg
var FolderArrowRight core.SVG

//go:embed folder-duplicate.svg
var FolderDuplicate core.SVG

//go:embed folder-open.svg
var FolderOpen core.SVG

//go:embed folder-plus.svg
var FolderPlus core.SVG

//go:embed folder.svg
var Folder core.SVG

//go:embed forward-step.svg
var ForwardStep core.SVG

//go:embed forward.svg
var Forward core.SVG

//go:embed gift-box.svg
var GiftBox core.SVG

//go:embed globe.svg
var Globe core.SVG

//go:embed grid-plus.svg
var GridPlus core.SVG

//go:embed grid.svg
var Grid core.SVG

//go:embed headphones.svg
var Headphones core.SVG

//go:embed heart.svg
var Heart core.SVG

//go:embed home.svg
var Home core.SVG

//go:embed hourglass.svg
var Hourglass core.SVG

//go:embed image.svg
var Image core.SVG

//go:embed inbox-full.svg
var InboxFull core.SVG

//go:embed inbox.svg
var Inbox core.SVG

//go:embed indent.svg
var Indent core.SVG

//go:embed info-circle.svg
var InfoCircle core.SVG

//go:embed keyboard.svg
var Keyboard core.SVG

//go:embed label.svg
var Label core.SVG

//go:embed landmark.svg
var Landmark core.SVG

//go:embed language.svg
var Language core.SVG

//go:embed layers.svg
var Layers core.SVG

//go:embed letter-bold.svg
var LetterBold core.SVG

//go:embed letter-italic.svg
var LetterItalic core.SVG

//go:embed letter-underline.svg
var LetterUnderline core.SVG

//go:embed life-saver.svg
var LifeSaver core.SVG

//go:embed lightbulb.svg
var Lightbulb core.SVG

//go:embed link.svg
var Link core.SVG

//go:embed list-music.svg
var ListMusic core.SVG

//go:embed list.svg
var List core.SVG

//go:embed lock-open.svg
var LockOpen core.SVG

//go:embed lock-time.svg
var LockTime core.SVG

//go:embed lock.svg
var Lock core.SVG

//go:embed mail-box.svg
var MailBox core.SVG

//go:embed map-pin-alt.svg
var MapPinAlt core.SVG

//go:embed map-pin.svg
var MapPin core.SVG

//go:embed message-caption.svg
var MessageCaption core.SVG

//go:embed message-dots.svg
var MessageDots core.SVG

//go:embed messages.svg
var Messages core.SVG

//go:embed microphone-slash.svg
var MicrophoneSlash core.SVG

//go:embed microphone.svg
var Microphone core.SVG

//go:embed minimize.svg
var Minimize core.SVG

//go:embed minus.svg
var Minus core.SVG

//go:embed mobile-phone.svg
var MobilePhone core.SVG

//go:embed moon.svg
var Moon core.SVG

//go:embed newspaper.svg
var Newspaper core.SVG

//go:embed objects-column.svg
var ObjectsColumn core.SVG

//go:embed ordered-list.svg
var OrderedList core.SVG

//go:embed outdent.svg
var Outdent core.SVG

//go:embed palette.svg
var Palette core.SVG

//go:embed paper-clip.svg
var PaperClip core.SVG

//go:embed paper-plane.svg
var PaperPlane core.SVG

//go:embed paragraph.svg
var Paragraph core.SVG

//go:embed pause.svg
var Pause core.SVG

//go:embed pen-nib.svg
var PenNib core.SVG

//go:embed pen.svg
var Pen core.SVG

//go:embed phone-hangup.svg
var PhoneHangup core.SVG

//go:embed phone.svg
var Phone core.SVG

//go:embed play.svg
var Play core.SVG

//go:embed plus.svg
var Plus core.SVG

//go:embed printer.svg
var Printer core.SVG

//go:embed profile-card.svg
var ProfileCard core.SVG

//go:embed qr-code.svg
var QrCode core.SVG

//go:embed question-circle.svg
var QuestionCircle core.SVG

//go:embed quote.svg
var Quote core.SVG

//go:embed receipt.svg
var Receipt core.SVG

//go:embed rectangle-list.svg
var RectangleList core.SVG

//go:embed redo.svg
var Redo core.SVG

//go:embed refresh.svg
var Refresh core.SVG

//go:embed reply-all.svg
var ReplyAll core.SVG

//go:embed reply.svg
var Reply core.SVG

//go:embed restore-window.svg
var RestoreWindow core.SVG

//go:embed rocket.svg
var Rocket core.SVG

//go:embed ruler-combined.svg
var RulerCombined core.SVG

//go:embed sale-percent.svg
var SalePercent core.SVG

//go:embed scale-balanced.svg
var ScaleBalanced core.SVG

//go:embed search.svg
var Search core.SVG

//go:embed server.svg
var Server core.SVG

//go:embed share-all.svg
var ShareAll core.SVG

//go:embed share-nodes.svg
var ShareNodes core.SVG

//go:embed shield-check.svg
var ShieldCheck core.SVG

//go:embed shield.svg
var Shield core.SVG

//go:embed shopping-bag.svg
var ShoppingBag core.SVG

//go:embed shuffle.svg
var Shuffle core.SVG

//go:embed sort-horizontal.svg
var SortHorizontal core.SVG

//go:embed sort.svg
var Sort core.SVG

//go:embed star-half-stroke.svg
var StarHalfStroke core.SVG

//go:embed star-half.svg
var StarHalf core.SVG

//go:embed star.svg
var Star core.SVG

//go:embed stop.svg
var Stop core.SVG

//go:embed store.svg
var Store core.SVG

//go:embed sun.svg
var Sun core.SVG

//go:embed swatchbook.svg
var Swatchbook core.SVG

//go:embed table-column.svg
var TableColumn core.SVG

//go:embed table-row.svg
var TableRow core.SVG

//go:embed tablet.svg
var Tablet core.SVG

//go:embed tag.svg
var Tag core.SVG

//go:embed terminal.svg
var Terminal core.SVG

//go:embed text-size.svg
var TextSize core.SVG

//go:embed text-slash.svg
var TextSlash core.SVG

//go:embed thumbs-down.svg
var ThumbsDown core.SVG

//go:embed thumbs-up.svg
var ThumbsUp core.SVG

//go:embed ticket.svg
var Ticket core.SVG

//go:embed trash-bin.svg
var TrashBin core.SVG

//go:embed truck.svg
var Truck core.SVG

//go:embed undo.svg
var Undo core.SVG

//go:embed upload.svg
var Upload core.SVG

//go:embed user-add.svg
var UserAdd core.SVG

//go:embed user-circle.svg
var UserCircle core.SVG

//go:embed user-edit.svg
var UserEdit core.SVG

//go:embed user-headset.svg
var UserHeadset core.SVG

//go:embed user-remove.svg
var UserRemove core.SVG

//go:embed user-settings.svg
var UserSettings core.SVG

//go:embed user.svg
var User core.SVG

//go:embed users-group.svg
var UsersGroup core.SVG

//go:embed users.svg
var Users core.SVG

//go:embed video-camera.svg
var VideoCamera core.SVG

//go:embed volume-down.svg
var VolumeDown core.SVG

//go:embed volume-mute.svg
var VolumeMute core.SVG

//go:embed volume-up.svg
var VolumeUp core.SVG

//go:embed wallet.svg
var Wallet core.SVG

//go:embed wand-magic-sparkles.svg
var WandMagicSparkles core.SVG

//go:embed window.svg
var Window core.SVG

//go:embed zoom-in.svg
var ZoomIn core.SVG

//go:embed zoom-out.svg
var ZoomOut core.SVG

var All = map[string]core.SVG{
	"AddressBook":            AddressBook,
	"AdjustmentsHorizontal":  AdjustmentsHorizontal,
	"AdjustmentsVertical":    AdjustmentsVertical,
	"AlignCenter":            AlignCenter,
	"AngleDown":              AngleDown,
	"AngleLeft":              AngleLeft,
	"AngleRight":             AngleRight,
	"AngleUp":                AngleUp,
	"Annotation":             Annotation,
	"ArchiveArrowDown":       ArchiveArrowDown,
	"Archive":                Archive,
	"ArrowDownToBracket":     ArrowDownToBracket,
	"ArrowDown":              ArrowDown,
	"ArrowLeftToBracket":     ArrowLeftToBracket,
	"ArrowLeft":              ArrowLeft,
	"ArrowRightAlt":          ArrowRightAlt,
	"ArrowRightToBracket":    ArrowRightToBracket,
	"ArrowRight":             ArrowRight,
	"ArrowSortLetters":       ArrowSortLetters,
	"ArrowUpDown":            ArrowUpDown,
	"ArrowUpFromBracket":     ArrowUpFromBracket,
	"ArrowUpRightDownLeft":   ArrowUpRightDownLeft,
	"ArrowUpRightFromSquare": ArrowUpRightFromSquare,
	"ArrowUp":                ArrowUp,
	"ArrowsRepeatCount":      ArrowsRepeatCount,
	"ArrowsRepeat":           ArrowsRepeat,
	"Atom":                   Atom,
	"Award":                  Award,
	"BackwardStep":           BackwardStep,
	"BadgeCheck":             BadgeCheck,
	"Ban":                    Ban,
	"BarsFromLeft":           BarsFromLeft,
	"Bars":                   Bars,
	"BellActiveAlt":          BellActiveAlt,
	"BellActive":             BellActive,
	"BellRing":               BellRing,
	"Bell":                   Bell,
	"BlenderPhone":           BlenderPhone,
	"BookOpen":               BookOpen,
	"Book":                   Book,
	"Bookmark":               Bookmark,
	"Brain":                  Brain,
	"Briefcase":              Briefcase,
	"Bug":                    Bug,
	"Building":               Building,
	"Bullhorn":               Bullhorn,
	"CalendarEdit":           CalendarEdit,
	"CalendarMonth":          CalendarMonth,
	"CalendarPlus":           CalendarPlus,
	"CalendarWeek":           CalendarWeek,
	"CameraPhoto":            CameraPhoto,
	"Caption":                Caption,
	"CaretDown":              CaretDown,
	"CaretLeft":              CaretLeft,
	"CaretRight":             CaretRight,
	"CaretSort":              CaretSort,
	"CaretUp":                CaretUp,
	"CartPlusAlt":            CartPlusAlt,
	"CartPlus":               CartPlus,
	"Cart":                   Cart,
	"Cash":                   Cash,
	"ChartLineDown":          ChartLineDown,
	"ChartLineUp":            ChartLineUp,
	"ChartMixedDollar":       ChartMixedDollar,
	"ChartMixed":             ChartMixed,
	"ChartPie":               ChartPie,
	"Chart":                  Chart,
	"CheckCircle":            CheckCircle,
	"CheckPlusCircle":        CheckPlusCircle,
	"Check":                  Check,
	"ChevronDoubleDown":      ChevronDoubleDown,
	"ChevronDoubleLeft":      ChevronDoubleLeft,
	"ChevronDoubleRight":     ChevronDoubleRight,
	"ChevronDoubleUp":        ChevronDoubleUp,
	"ChevronDown":            ChevronDown,
	"ChevronLeft":            ChevronLeft,
	"ChevronRight":           ChevronRight,
	"ChevronSort":            ChevronSort,
	"ChevronUp":              ChevronUp,
	"CircleMinus":            CircleMinus,
	"CirclePause":            CirclePause,
	"CirclePlus":             CirclePlus,
	"ClapperboardPlay":       ClapperboardPlay,
	"ClipboardCheck":         ClipboardCheck,
	"ClipboardClean":         ClipboardClean,
	"ClipboardList":          ClipboardList,
	"Clipboard":              Clipboard,
	"Clock":                  Clock,
	"CloseCircle":            CloseCircle,
	"Close":                  Close,
	"CloudArrowUp":           CloudArrowUp,
	"CodeBranch":             CodeBranch,
	"CodeFork":               CodeFork,
	"CodeMerge":              CodeMerge,
	"CodePullRequest":        CodePullRequest,
	"Code":                   Code,
	"Cog":                    Cog,
	"Column":                 Column,
	"Command":                Command,
	"Compress":               Compress,
	"ComputerSpeaker":        ComputerSpeaker,
	"CreditCardPlus":         CreditCardPlus,
	"CreditCard":             CreditCard,
	"Database":               Database,
	"DesktopPc":              DesktopPc,
	"Dna":                    Dna,
	"Dollar":                 Dollar,
	"DotsHorizontal":         DotsHorizontal,
	"DotsVertical":           DotsVertical,
	"Download":               Download,
	"DrawSquare":             DrawSquare,
	"Edit":                   Edit,
	"EnvelopeOpen":           EnvelopeOpen,
	"Envelope":               Envelope,
	"Euro":                   Euro,
	"ExclamationCircle":      ExclamationCircle,
	"Expand":                 Expand,
	"EyeSlash":               EyeSlash,
	"Eye":                    Eye,
	"FaceExplode":            FaceExplode,
	"FaceGrinStars":          FaceGrinStars,
	"FaceGrin":               FaceGrin,
	"FaceLaugh":              FaceLaugh,
	"FileChartBar":           FileChartBar,
	"FileCheck":              FileCheck,
	"FileCirclePlus":         FileCirclePlus,
	"FileClone":              FileClone,
	"FileCode":               FileCode,
	"FileCopyAlt":            FileCopyAlt,
	"FileCopy":               FileCopy,
	"FileCsv":                FileCsv,
	"FileDoc":                FileDoc,
	"FileExport":             FileExport,
	"FileImage":              FileImage,
	"FileImport":             FileImport,
	"FileInvoice":            FileInvoice,
	"FileLines":              FileLines,
	"FileMusic":              FileMusic,
	"FilePaste":              FilePaste,
	"FilePdf":                FilePdf,
	"FilePen":                FilePen,
	"FilePpt":                FilePpt,
	"FileSearch":             FileSearch,
	"FileShield":             FileShield,
	"FileVideo":              FileVideo,
	"FileWord":               FileWord,
	"FileZip":                FileZip,
	"File":                   File,
	"Filter":                 Filter,
	"Fingerprint":            Fingerprint,
	"Fire":                   Fire,
	"Flag":                   Flag,
	"FloppyDiskAlt":          FloppyDiskAlt,
	"FloppyDisk":             FloppyDisk,
	"FolderArrowRight":       FolderArrowRight,
	"FolderDuplicate":        FolderDuplicate,
	"FolderOpen":             FolderOpen,
	"FolderPlus":             FolderPlus,
	"Folder":                 Folder,
	"ForwardStep":            ForwardStep,
	"Forward":                Forward,
	"GiftBox":                GiftBox,
	"Globe":                  Globe,
	"GridPlus":               GridPlus,
	"Grid":                   Grid,
	"Headphones":             Headphones,
	"Heart":                  Heart,
	"Home":                   Home,
	"Hourglass":              Hourglass,
	"Image":                  Image,
	"InboxFull":              InboxFull,
	"Inbox":                  Inbox,
	"Indent":                 Indent,
	"InfoCircle":             InfoCircle,
	"Keyboard":               Keyboard,
	"Label":                  Label,
	"Landmark":               Landmark,
	"Language":               Language,
	"Layers":                 Layers,
	"LetterBold":             LetterBold,
	"LetterItalic":           LetterItalic,
	"LetterUnderline":        LetterUnderline,
	"LifeSaver":              LifeSaver,
	"Lightbulb":              Lightbulb,
	"Link":                   Link,
	"ListMusic":              ListMusic,
	"List":                   List,
	"LockOpen":               LockOpen,
	"LockTime":               LockTime,
	"Lock":                   Lock,
	"MailBox":                MailBox,
	"MapPinAlt":              MapPinAlt,
	"MapPin":                 MapPin,
	"MessageCaption":         MessageCaption,
	"MessageDots":            MessageDots,
	"Messages":               Messages,
	"MicrophoneSlash":        MicrophoneSlash,
	"Microphone":             Microphone,
	"Minimize":               Minimize,
	"Minus":                  Minus,
	"MobilePhone":            MobilePhone,
	"Moon":                   Moon,
	"Newspaper":              Newspaper,
	"ObjectsColumn":          ObjectsColumn,
	"OrderedList":            OrderedList,
	"Outdent":                Outdent,
	"Palette":                Palette,
	"PaperClip":              PaperClip,
	"PaperPlane":             PaperPlane,
	"Paragraph":              Paragraph,
	"Pause":                  Pause,
	"PenNib":                 PenNib,
	"Pen":                    Pen,
	"PhoneHangup":            PhoneHangup,
	"Phone":                  Phone,
	"Play":                   Play,
	"Plus":                   Plus,
	"Printer":                Printer,
	"ProfileCard":            ProfileCard,
	"QrCode":                 QrCode,
	"QuestionCircle":         QuestionCircle,
	"Quote":                  Quote,
	"Receipt":                Receipt,
	"RectangleList":          RectangleList,
	"Redo":                   Redo,
	"Refresh":                Refresh,
	"ReplyAll":               ReplyAll,
	"Reply":                  Reply,
	"RestoreWindow":          RestoreWindow,
	"Rocket":                 Rocket,
	"RulerCombined":          RulerCombined,
	"SalePercent":            SalePercent,
	"ScaleBalanced":          ScaleBalanced,
	"Search":                 Search,
	"Server":                 Server,
	"ShareAll":               ShareAll,
	"ShareNodes":             ShareNodes,
	"ShieldCheck":            ShieldCheck,
	"Shield":                 Shield,
	"ShoppingBag":            ShoppingBag,
	"Shuffle":                Shuffle,
	"SortHorizontal":         SortHorizontal,
	"Sort":                   Sort,
	"StarHalfStroke":         StarHalfStroke,
	"StarHalf":               StarHalf,
	"Star":                   Star,
	"Stop":                   Stop,
	"Store":                  Store,
	"Sun":                    Sun,
	"Swatchbook":             Swatchbook,
	"TableColumn":            TableColumn,
	"TableRow":               TableRow,
	"Tablet":                 Tablet,
	"Tag":                    Tag,
	"Terminal":               Terminal,
	"TextSize":               TextSize,
	"TextSlash":              TextSlash,
	"ThumbsDown":             ThumbsDown,
	"ThumbsUp":               ThumbsUp,
	"Ticket":                 Ticket,
	"TrashBin":               TrashBin,
	"Truck":                  Truck,
	"Undo":                   Undo,
	"Upload":                 Upload,
	"UserAdd":                UserAdd,
	"UserCircle":             UserCircle,
	"UserEdit":               UserEdit,
	"UserHeadset":            UserHeadset,
	"UserRemove":             UserRemove,
	"UserSettings":           UserSettings,
	"User":                   User,
	"UsersGroup":             UsersGroup,
	"Users":                  Users,
	"VideoCamera":            VideoCamera,
	"VolumeDown":             VolumeDown,
	"VolumeMute":             VolumeMute,
	"VolumeUp":               VolumeUp,
	"Wallet":                 Wallet,
	"WandMagicSparkles":      WandMagicSparkles,
	"Window":                 Window,
	"ZoomIn":                 ZoomIn,
	"ZoomOut":                ZoomOut,
}
