// Code generated by cmd/embed-icons. DO NOT EDIT.

package icons

import (
	_ "embed"
	"go.wdy.de/nago/presentation/core"
)

//go:embed academic-cap.svg
var AcademicCap core.SVG

//go:embed adjustments-horizontal.svg
var AdjustmentsHorizontal core.SVG

//go:embed adjustments-vertical.svg
var AdjustmentsVertical core.SVG

//go:embed archive-box-arrow-down.svg
var ArchiveBoxArrowDown core.SVG

//go:embed archive-box-x-mark.svg
var ArchiveBoxXMark core.SVG

//go:embed archive-box.svg
var ArchiveBox core.SVG

//go:embed arrow-down-circle.svg
var ArrowDownCircle core.SVG

//go:embed arrow-down-left.svg
var ArrowDownLeft core.SVG

//go:embed arrow-down-on-square-stack.svg
var ArrowDownOnSquareStack core.SVG

//go:embed arrow-down-on-square.svg
var ArrowDownOnSquare core.SVG

//go:embed arrow-down-right.svg
var ArrowDownRight core.SVG

//go:embed arrow-down-tray.svg
var ArrowDownTray core.SVG

//go:embed arrow-down.svg
var ArrowDown core.SVG

//go:embed arrow-left-circle.svg
var ArrowLeftCircle core.SVG

//go:embed arrow-left-end-on-rectangle.svg
var ArrowLeftEndOnRectangle core.SVG

//go:embed arrow-left-on-rectangle.svg
var ArrowLeftOnRectangle core.SVG

//go:embed arrow-left-start-on-rectangle.svg
var ArrowLeftStartOnRectangle core.SVG

//go:embed arrow-left.svg
var ArrowLeft core.SVG

//go:embed arrow-long-down.svg
var ArrowLongDown core.SVG

//go:embed arrow-long-left.svg
var ArrowLongLeft core.SVG

//go:embed arrow-long-right.svg
var ArrowLongRight core.SVG

//go:embed arrow-long-up.svg
var ArrowLongUp core.SVG

//go:embed arrow-path-rounded-square.svg
var ArrowPathRoundedSquare core.SVG

//go:embed arrow-path.svg
var ArrowPath core.SVG

//go:embed arrow-right-circle.svg
var ArrowRightCircle core.SVG

//go:embed arrow-right-end-on-rectangle.svg
var ArrowRightEndOnRectangle core.SVG

//go:embed arrow-right-on-rectangle.svg
var ArrowRightOnRectangle core.SVG

//go:embed arrow-right-start-on-rectangle.svg
var ArrowRightStartOnRectangle core.SVG

//go:embed arrow-right.svg
var ArrowRight core.SVG

//go:embed arrow-small-down.svg
var ArrowSmallDown core.SVG

//go:embed arrow-small-left.svg
var ArrowSmallLeft core.SVG

//go:embed arrow-small-right.svg
var ArrowSmallRight core.SVG

//go:embed arrow-small-up.svg
var ArrowSmallUp core.SVG

//go:embed arrow-top-right-on-square.svg
var ArrowTopRightOnSquare core.SVG

//go:embed arrow-trending-down.svg
var ArrowTrendingDown core.SVG

//go:embed arrow-trending-up.svg
var ArrowTrendingUp core.SVG

//go:embed arrow-turn-down-left.svg
var ArrowTurnDownLeft core.SVG

//go:embed arrow-turn-down-right.svg
var ArrowTurnDownRight core.SVG

//go:embed arrow-turn-left-down.svg
var ArrowTurnLeftDown core.SVG

//go:embed arrow-turn-left-up.svg
var ArrowTurnLeftUp core.SVG

//go:embed arrow-turn-right-down.svg
var ArrowTurnRightDown core.SVG

//go:embed arrow-turn-right-up.svg
var ArrowTurnRightUp core.SVG

//go:embed arrow-turn-up-left.svg
var ArrowTurnUpLeft core.SVG

//go:embed arrow-turn-up-right.svg
var ArrowTurnUpRight core.SVG

//go:embed arrow-up-circle.svg
var ArrowUpCircle core.SVG

//go:embed arrow-up-left.svg
var ArrowUpLeft core.SVG

//go:embed arrow-up-on-square-stack.svg
var ArrowUpOnSquareStack core.SVG

//go:embed arrow-up-on-square.svg
var ArrowUpOnSquare core.SVG

//go:embed arrow-up-right.svg
var ArrowUpRight core.SVG

//go:embed arrow-up-tray.svg
var ArrowUpTray core.SVG

//go:embed arrow-up.svg
var ArrowUp core.SVG

//go:embed arrow-uturn-down.svg
var ArrowUturnDown core.SVG

//go:embed arrow-uturn-left.svg
var ArrowUturnLeft core.SVG

//go:embed arrow-uturn-right.svg
var ArrowUturnRight core.SVG

//go:embed arrow-uturn-up.svg
var ArrowUturnUp core.SVG

//go:embed arrows-pointing-in.svg
var ArrowsPointingIn core.SVG

//go:embed arrows-pointing-out.svg
var ArrowsPointingOut core.SVG

//go:embed arrows-right-left.svg
var ArrowsRightLeft core.SVG

//go:embed arrows-up-down.svg
var ArrowsUpDown core.SVG

//go:embed at-symbol.svg
var AtSymbol core.SVG

//go:embed backspace.svg
var Backspace core.SVG

//go:embed backward.svg
var Backward core.SVG

//go:embed banknotes.svg
var Banknotes core.SVG

//go:embed bars-2.svg
var Bars2 core.SVG

//go:embed bars-3-bottom-left.svg
var Bars3BottomLeft core.SVG

//go:embed bars-3-bottom-right.svg
var Bars3BottomRight core.SVG

//go:embed bars-3-center-left.svg
var Bars3CenterLeft core.SVG

//go:embed bars-3.svg
var Bars3 core.SVG

//go:embed bars-4.svg
var Bars4 core.SVG

//go:embed bars-arrow-down.svg
var BarsArrowDown core.SVG

//go:embed bars-arrow-up.svg
var BarsArrowUp core.SVG

//go:embed battery-0.svg
var Battery0 core.SVG

//go:embed battery-100.svg
var Battery100 core.SVG

//go:embed battery-50.svg
var Battery50 core.SVG

//go:embed beaker.svg
var Beaker core.SVG

//go:embed bell-alert.svg
var BellAlert core.SVG

//go:embed bell-slash.svg
var BellSlash core.SVG

//go:embed bell-snooze.svg
var BellSnooze core.SVG

//go:embed bell.svg
var Bell core.SVG

//go:embed bold.svg
var Bold core.SVG

//go:embed bolt-slash.svg
var BoltSlash core.SVG

//go:embed bolt.svg
var Bolt core.SVG

//go:embed book-open.svg
var BookOpen core.SVG

//go:embed bookmark-slash.svg
var BookmarkSlash core.SVG

//go:embed bookmark-square.svg
var BookmarkSquare core.SVG

//go:embed bookmark.svg
var Bookmark core.SVG

//go:embed briefcase.svg
var Briefcase core.SVG

//go:embed bug-ant.svg
var BugAnt core.SVG

//go:embed building-library.svg
var BuildingLibrary core.SVG

//go:embed building-office-2.svg
var BuildingOffice2 core.SVG

//go:embed building-office.svg
var BuildingOffice core.SVG

//go:embed building-storefront.svg
var BuildingStorefront core.SVG

//go:embed cake.svg
var Cake core.SVG

//go:embed calculator.svg
var Calculator core.SVG

//go:embed calendar-date-range.svg
var CalendarDateRange core.SVG

//go:embed calendar-days.svg
var CalendarDays core.SVG

//go:embed calendar.svg
var Calendar core.SVG

//go:embed camera.svg
var Camera core.SVG

//go:embed chart-bar-square.svg
var ChartBarSquare core.SVG

//go:embed chart-bar.svg
var ChartBar core.SVG

//go:embed chart-pie.svg
var ChartPie core.SVG

//go:embed chat-bubble-bottom-center-text.svg
var ChatBubbleBottomCenterText core.SVG

//go:embed chat-bubble-bottom-center.svg
var ChatBubbleBottomCenter core.SVG

//go:embed chat-bubble-left-ellipsis.svg
var ChatBubbleLeftEllipsis core.SVG

//go:embed chat-bubble-left-right.svg
var ChatBubbleLeftRight core.SVG

//go:embed chat-bubble-left.svg
var ChatBubbleLeft core.SVG

//go:embed chat-bubble-oval-left-ellipsis.svg
var ChatBubbleOvalLeftEllipsis core.SVG

//go:embed chat-bubble-oval-left.svg
var ChatBubbleOvalLeft core.SVG

//go:embed check-badge.svg
var CheckBadge core.SVG

//go:embed check-circle.svg
var CheckCircle core.SVG

//go:embed check.svg
var Check core.SVG

//go:embed chevron-double-down.svg
var ChevronDoubleDown core.SVG

//go:embed chevron-double-left.svg
var ChevronDoubleLeft core.SVG

//go:embed chevron-double-right.svg
var ChevronDoubleRight core.SVG

//go:embed chevron-double-up.svg
var ChevronDoubleUp core.SVG

//go:embed chevron-down.svg
var ChevronDown core.SVG

//go:embed chevron-left.svg
var ChevronLeft core.SVG

//go:embed chevron-right.svg
var ChevronRight core.SVG

//go:embed chevron-up-down.svg
var ChevronUpDown core.SVG

//go:embed chevron-up.svg
var ChevronUp core.SVG

//go:embed circle-stack.svg
var CircleStack core.SVG

//go:embed clipboard-document-check.svg
var ClipboardDocumentCheck core.SVG

//go:embed clipboard-document-list.svg
var ClipboardDocumentList core.SVG

//go:embed clipboard-document.svg
var ClipboardDocument core.SVG

//go:embed clipboard.svg
var Clipboard core.SVG

//go:embed clock.svg
var Clock core.SVG

//go:embed cloud-arrow-down.svg
var CloudArrowDown core.SVG

//go:embed cloud-arrow-up.svg
var CloudArrowUp core.SVG

//go:embed cloud.svg
var Cloud core.SVG

//go:embed code-bracket-square.svg
var CodeBracketSquare core.SVG

//go:embed code-bracket.svg
var CodeBracket core.SVG

//go:embed cog-6-tooth.svg
var Cog6Tooth core.SVG

//go:embed cog-8-tooth.svg
var Cog8Tooth core.SVG

//go:embed cog.svg
var Cog core.SVG

//go:embed command-line.svg
var CommandLine core.SVG

//go:embed computer-desktop.svg
var ComputerDesktop core.SVG

//go:embed cpu-chip.svg
var CpuChip core.SVG

//go:embed credit-card.svg
var CreditCard core.SVG

//go:embed cube-transparent.svg
var CubeTransparent core.SVG

//go:embed cube.svg
var Cube core.SVG

//go:embed currency-bangladeshi.svg
var CurrencyBangladeshi core.SVG

//go:embed currency-dollar.svg
var CurrencyDollar core.SVG

//go:embed currency-euro.svg
var CurrencyEuro core.SVG

//go:embed currency-pound.svg
var CurrencyPound core.SVG

//go:embed currency-rupee.svg
var CurrencyRupee core.SVG

//go:embed currency-yen.svg
var CurrencyYen core.SVG

//go:embed cursor-arrow-rays.svg
var CursorArrowRays core.SVG

//go:embed cursor-arrow-ripple.svg
var CursorArrowRipple core.SVG

//go:embed device-phone-mobile.svg
var DevicePhoneMobile core.SVG

//go:embed device-tablet.svg
var DeviceTablet core.SVG

//go:embed divide.svg
var Divide core.SVG

//go:embed document-arrow-down.svg
var DocumentArrowDown core.SVG

//go:embed document-arrow-up.svg
var DocumentArrowUp core.SVG

//go:embed document-chart-bar.svg
var DocumentChartBar core.SVG

//go:embed document-check.svg
var DocumentCheck core.SVG

//go:embed document-currency-bangladeshi.svg
var DocumentCurrencyBangladeshi core.SVG

//go:embed document-currency-dollar.svg
var DocumentCurrencyDollar core.SVG

//go:embed document-currency-euro.svg
var DocumentCurrencyEuro core.SVG

//go:embed document-currency-pound.svg
var DocumentCurrencyPound core.SVG

//go:embed document-currency-rupee.svg
var DocumentCurrencyRupee core.SVG

//go:embed document-currency-yen.svg
var DocumentCurrencyYen core.SVG

//go:embed document-duplicate.svg
var DocumentDuplicate core.SVG

//go:embed document-magnifying-glass.svg
var DocumentMagnifyingGlass core.SVG

//go:embed document-minus.svg
var DocumentMinus core.SVG

//go:embed document-plus.svg
var DocumentPlus core.SVG

//go:embed document-text.svg
var DocumentText core.SVG

//go:embed document.svg
var Document core.SVG

//go:embed ellipsis-horizontal-circle.svg
var EllipsisHorizontalCircle core.SVG

//go:embed ellipsis-horizontal.svg
var EllipsisHorizontal core.SVG

//go:embed ellipsis-vertical.svg
var EllipsisVertical core.SVG

//go:embed envelope-open.svg
var EnvelopeOpen core.SVG

//go:embed envelope.svg
var Envelope core.SVG

//go:embed equals.svg
var Equals core.SVG

//go:embed exclamation-circle.svg
var ExclamationCircle core.SVG

//go:embed exclamation-triangle.svg
var ExclamationTriangle core.SVG

//go:embed eye-dropper.svg
var EyeDropper core.SVG

//go:embed eye-slash.svg
var EyeSlash core.SVG

//go:embed eye.svg
var Eye core.SVG

//go:embed face-frown.svg
var FaceFrown core.SVG

//go:embed face-smile.svg
var FaceSmile core.SVG

//go:embed film.svg
var Film core.SVG

//go:embed finger-print.svg
var FingerPrint core.SVG

//go:embed fire.svg
var Fire core.SVG

//go:embed flag.svg
var Flag core.SVG

//go:embed folder-arrow-down.svg
var FolderArrowDown core.SVG

//go:embed folder-minus.svg
var FolderMinus core.SVG

//go:embed folder-open.svg
var FolderOpen core.SVG

//go:embed folder-plus.svg
var FolderPlus core.SVG

//go:embed folder.svg
var Folder core.SVG

//go:embed forward.svg
var Forward core.SVG

//go:embed funnel.svg
var Funnel core.SVG

//go:embed gif.svg
var Gif core.SVG

//go:embed gift-top.svg
var GiftTop core.SVG

//go:embed gift.svg
var Gift core.SVG

//go:embed globe-alt.svg
var GlobeAlt core.SVG

//go:embed globe-americas.svg
var GlobeAmericas core.SVG

//go:embed globe-asia-australia.svg
var GlobeAsiaAustralia core.SVG

//go:embed globe-europe-africa.svg
var GlobeEuropeAfrica core.SVG

//go:embed h1.svg
var H1 core.SVG

//go:embed h2.svg
var H2 core.SVG

//go:embed h3.svg
var H3 core.SVG

//go:embed hand-raised.svg
var HandRaised core.SVG

//go:embed hand-thumb-down.svg
var HandThumbDown core.SVG

//go:embed hand-thumb-up.svg
var HandThumbUp core.SVG

//go:embed hashtag.svg
var Hashtag core.SVG

//go:embed heart.svg
var Heart core.SVG

//go:embed home-modern.svg
var HomeModern core.SVG

//go:embed home.svg
var Home core.SVG

//go:embed identification.svg
var Identification core.SVG

//go:embed inbox-arrow-down.svg
var InboxArrowDown core.SVG

//go:embed inbox-stack.svg
var InboxStack core.SVG

//go:embed inbox.svg
var Inbox core.SVG

//go:embed information-circle.svg
var InformationCircle core.SVG

//go:embed italic.svg
var Italic core.SVG

//go:embed key.svg
var Key core.SVG

//go:embed language.svg
var Language core.SVG

//go:embed lifebuoy.svg
var Lifebuoy core.SVG

//go:embed light-bulb.svg
var LightBulb core.SVG

//go:embed link-slash.svg
var LinkSlash core.SVG

//go:embed link.svg
var Link core.SVG

//go:embed list-bullet.svg
var ListBullet core.SVG

//go:embed lock-closed.svg
var LockClosed core.SVG

//go:embed lock-open.svg
var LockOpen core.SVG

//go:embed magnifying-glass-circle.svg
var MagnifyingGlassCircle core.SVG

//go:embed magnifying-glass-minus.svg
var MagnifyingGlassMinus core.SVG

//go:embed magnifying-glass-plus.svg
var MagnifyingGlassPlus core.SVG

//go:embed magnifying-glass.svg
var MagnifyingGlass core.SVG

//go:embed map-pin.svg
var MapPin core.SVG

//go:embed map.svg
var Map core.SVG

//go:embed megaphone.svg
var Megaphone core.SVG

//go:embed microphone.svg
var Microphone core.SVG

//go:embed minus-circle.svg
var MinusCircle core.SVG

//go:embed minus-small.svg
var MinusSmall core.SVG

//go:embed minus.svg
var Minus core.SVG

//go:embed moon.svg
var Moon core.SVG

//go:embed musical-note.svg
var MusicalNote core.SVG

//go:embed newspaper.svg
var Newspaper core.SVG

//go:embed no-symbol.svg
var NoSymbol core.SVG

//go:embed numbered-list.svg
var NumberedList core.SVG

//go:embed paint-brush.svg
var PaintBrush core.SVG

//go:embed paper-airplane.svg
var PaperAirplane core.SVG

//go:embed paper-clip.svg
var PaperClip core.SVG

//go:embed pause-circle.svg
var PauseCircle core.SVG

//go:embed pause.svg
var Pause core.SVG

//go:embed pencil-square.svg
var PencilSquare core.SVG

//go:embed pencil.svg
var Pencil core.SVG

//go:embed percent-badge.svg
var PercentBadge core.SVG

//go:embed phone-arrow-down-left.svg
var PhoneArrowDownLeft core.SVG

//go:embed phone-arrow-up-right.svg
var PhoneArrowUpRight core.SVG

//go:embed phone-x-mark.svg
var PhoneXMark core.SVG

//go:embed phone.svg
var Phone core.SVG

//go:embed photo.svg
var Photo core.SVG

//go:embed play-circle.svg
var PlayCircle core.SVG

//go:embed play-pause.svg
var PlayPause core.SVG

//go:embed play.svg
var Play core.SVG

//go:embed plus-circle.svg
var PlusCircle core.SVG

//go:embed plus-small.svg
var PlusSmall core.SVG

//go:embed plus.svg
var Plus core.SVG

//go:embed power.svg
var Power core.SVG

//go:embed presentation-chart-bar.svg
var PresentationChartBar core.SVG

//go:embed presentation-chart-line.svg
var PresentationChartLine core.SVG

//go:embed printer.svg
var Printer core.SVG

//go:embed puzzle-piece.svg
var PuzzlePiece core.SVG

//go:embed qr-code.svg
var QrCode core.SVG

//go:embed question-mark-circle.svg
var QuestionMarkCircle core.SVG

//go:embed queue-list.svg
var QueueList core.SVG

//go:embed radio.svg
var Radio core.SVG

//go:embed receipt-percent.svg
var ReceiptPercent core.SVG

//go:embed receipt-refund.svg
var ReceiptRefund core.SVG

//go:embed rectangle-group.svg
var RectangleGroup core.SVG

//go:embed rectangle-stack.svg
var RectangleStack core.SVG

//go:embed rocket-launch.svg
var RocketLaunch core.SVG

//go:embed rss.svg
var Rss core.SVG

//go:embed scale.svg
var Scale core.SVG

//go:embed scissors.svg
var Scissors core.SVG

//go:embed server-stack.svg
var ServerStack core.SVG

//go:embed server.svg
var Server core.SVG

//go:embed share.svg
var Share core.SVG

//go:embed shield-check.svg
var ShieldCheck core.SVG

//go:embed shield-exclamation.svg
var ShieldExclamation core.SVG

//go:embed shopping-bag.svg
var ShoppingBag core.SVG

//go:embed shopping-cart.svg
var ShoppingCart core.SVG

//go:embed signal-slash.svg
var SignalSlash core.SVG

//go:embed signal.svg
var Signal core.SVG

//go:embed slash.svg
var Slash core.SVG

//go:embed sparkles.svg
var Sparkles core.SVG

//go:embed speaker-wave.svg
var SpeakerWave core.SVG

//go:embed speaker-x-mark.svg
var SpeakerXMark core.SVG

//go:embed square-2-stack.svg
var Square2Stack core.SVG

//go:embed square-3-stack-3d.svg
var Square3Stack3d core.SVG

//go:embed squares-2x2.svg
var Squares2x2 core.SVG

//go:embed squares-plus.svg
var SquaresPlus core.SVG

//go:embed star.svg
var Star core.SVG

//go:embed stop-circle.svg
var StopCircle core.SVG

//go:embed stop.svg
var Stop core.SVG

//go:embed strikethrough.svg
var Strikethrough core.SVG

//go:embed sun.svg
var Sun core.SVG

//go:embed swatch.svg
var Swatch core.SVG

//go:embed table-cells.svg
var TableCells core.SVG

//go:embed tag.svg
var Tag core.SVG

//go:embed ticket.svg
var Ticket core.SVG

//go:embed trash.svg
var Trash core.SVG

//go:embed trophy.svg
var Trophy core.SVG

//go:embed truck.svg
var Truck core.SVG

//go:embed tv.svg
var Tv core.SVG

//go:embed underline.svg
var Underline core.SVG

//go:embed user-circle.svg
var UserCircle core.SVG

//go:embed user-group.svg
var UserGroup core.SVG

//go:embed user-minus.svg
var UserMinus core.SVG

//go:embed user-plus.svg
var UserPlus core.SVG

//go:embed user.svg
var User core.SVG

//go:embed users.svg
var Users core.SVG

//go:embed variable.svg
var Variable core.SVG

//go:embed video-camera-slash.svg
var VideoCameraSlash core.SVG

//go:embed video-camera.svg
var VideoCamera core.SVG

//go:embed view-columns.svg
var ViewColumns core.SVG

//go:embed viewfinder-circle.svg
var ViewfinderCircle core.SVG

//go:embed wallet.svg
var Wallet core.SVG

//go:embed wifi.svg
var Wifi core.SVG

//go:embed window.svg
var Window core.SVG

//go:embed wrench-screwdriver.svg
var WrenchScrewdriver core.SVG

//go:embed wrench.svg
var Wrench core.SVG

//go:embed x-circle.svg
var XCircle core.SVG

//go:embed x-mark.svg
var XMark core.SVG

var All = map[string]core.SVG{
	"AcademicCap":                 AcademicCap,
	"AdjustmentsHorizontal":       AdjustmentsHorizontal,
	"AdjustmentsVertical":         AdjustmentsVertical,
	"ArchiveBoxArrowDown":         ArchiveBoxArrowDown,
	"ArchiveBoxXMark":             ArchiveBoxXMark,
	"ArchiveBox":                  ArchiveBox,
	"ArrowDownCircle":             ArrowDownCircle,
	"ArrowDownLeft":               ArrowDownLeft,
	"ArrowDownOnSquareStack":      ArrowDownOnSquareStack,
	"ArrowDownOnSquare":           ArrowDownOnSquare,
	"ArrowDownRight":              ArrowDownRight,
	"ArrowDownTray":               ArrowDownTray,
	"ArrowDown":                   ArrowDown,
	"ArrowLeftCircle":             ArrowLeftCircle,
	"ArrowLeftEndOnRectangle":     ArrowLeftEndOnRectangle,
	"ArrowLeftOnRectangle":        ArrowLeftOnRectangle,
	"ArrowLeftStartOnRectangle":   ArrowLeftStartOnRectangle,
	"ArrowLeft":                   ArrowLeft,
	"ArrowLongDown":               ArrowLongDown,
	"ArrowLongLeft":               ArrowLongLeft,
	"ArrowLongRight":              ArrowLongRight,
	"ArrowLongUp":                 ArrowLongUp,
	"ArrowPathRoundedSquare":      ArrowPathRoundedSquare,
	"ArrowPath":                   ArrowPath,
	"ArrowRightCircle":            ArrowRightCircle,
	"ArrowRightEndOnRectangle":    ArrowRightEndOnRectangle,
	"ArrowRightOnRectangle":       ArrowRightOnRectangle,
	"ArrowRightStartOnRectangle":  ArrowRightStartOnRectangle,
	"ArrowRight":                  ArrowRight,
	"ArrowSmallDown":              ArrowSmallDown,
	"ArrowSmallLeft":              ArrowSmallLeft,
	"ArrowSmallRight":             ArrowSmallRight,
	"ArrowSmallUp":                ArrowSmallUp,
	"ArrowTopRightOnSquare":       ArrowTopRightOnSquare,
	"ArrowTrendingDown":           ArrowTrendingDown,
	"ArrowTrendingUp":             ArrowTrendingUp,
	"ArrowTurnDownLeft":           ArrowTurnDownLeft,
	"ArrowTurnDownRight":          ArrowTurnDownRight,
	"ArrowTurnLeftDown":           ArrowTurnLeftDown,
	"ArrowTurnLeftUp":             ArrowTurnLeftUp,
	"ArrowTurnRightDown":          ArrowTurnRightDown,
	"ArrowTurnRightUp":            ArrowTurnRightUp,
	"ArrowTurnUpLeft":             ArrowTurnUpLeft,
	"ArrowTurnUpRight":            ArrowTurnUpRight,
	"ArrowUpCircle":               ArrowUpCircle,
	"ArrowUpLeft":                 ArrowUpLeft,
	"ArrowUpOnSquareStack":        ArrowUpOnSquareStack,
	"ArrowUpOnSquare":             ArrowUpOnSquare,
	"ArrowUpRight":                ArrowUpRight,
	"ArrowUpTray":                 ArrowUpTray,
	"ArrowUp":                     ArrowUp,
	"ArrowUturnDown":              ArrowUturnDown,
	"ArrowUturnLeft":              ArrowUturnLeft,
	"ArrowUturnRight":             ArrowUturnRight,
	"ArrowUturnUp":                ArrowUturnUp,
	"ArrowsPointingIn":            ArrowsPointingIn,
	"ArrowsPointingOut":           ArrowsPointingOut,
	"ArrowsRightLeft":             ArrowsRightLeft,
	"ArrowsUpDown":                ArrowsUpDown,
	"AtSymbol":                    AtSymbol,
	"Backspace":                   Backspace,
	"Backward":                    Backward,
	"Banknotes":                   Banknotes,
	"Bars2":                       Bars2,
	"Bars3BottomLeft":             Bars3BottomLeft,
	"Bars3BottomRight":            Bars3BottomRight,
	"Bars3CenterLeft":             Bars3CenterLeft,
	"Bars3":                       Bars3,
	"Bars4":                       Bars4,
	"BarsArrowDown":               BarsArrowDown,
	"BarsArrowUp":                 BarsArrowUp,
	"Battery0":                    Battery0,
	"Battery100":                  Battery100,
	"Battery50":                   Battery50,
	"Beaker":                      Beaker,
	"BellAlert":                   BellAlert,
	"BellSlash":                   BellSlash,
	"BellSnooze":                  BellSnooze,
	"Bell":                        Bell,
	"Bold":                        Bold,
	"BoltSlash":                   BoltSlash,
	"Bolt":                        Bolt,
	"BookOpen":                    BookOpen,
	"BookmarkSlash":               BookmarkSlash,
	"BookmarkSquare":              BookmarkSquare,
	"Bookmark":                    Bookmark,
	"Briefcase":                   Briefcase,
	"BugAnt":                      BugAnt,
	"BuildingLibrary":             BuildingLibrary,
	"BuildingOffice2":             BuildingOffice2,
	"BuildingOffice":              BuildingOffice,
	"BuildingStorefront":          BuildingStorefront,
	"Cake":                        Cake,
	"Calculator":                  Calculator,
	"CalendarDateRange":           CalendarDateRange,
	"CalendarDays":                CalendarDays,
	"Calendar":                    Calendar,
	"Camera":                      Camera,
	"ChartBarSquare":              ChartBarSquare,
	"ChartBar":                    ChartBar,
	"ChartPie":                    ChartPie,
	"ChatBubbleBottomCenterText":  ChatBubbleBottomCenterText,
	"ChatBubbleBottomCenter":      ChatBubbleBottomCenter,
	"ChatBubbleLeftEllipsis":      ChatBubbleLeftEllipsis,
	"ChatBubbleLeftRight":         ChatBubbleLeftRight,
	"ChatBubbleLeft":              ChatBubbleLeft,
	"ChatBubbleOvalLeftEllipsis":  ChatBubbleOvalLeftEllipsis,
	"ChatBubbleOvalLeft":          ChatBubbleOvalLeft,
	"CheckBadge":                  CheckBadge,
	"CheckCircle":                 CheckCircle,
	"Check":                       Check,
	"ChevronDoubleDown":           ChevronDoubleDown,
	"ChevronDoubleLeft":           ChevronDoubleLeft,
	"ChevronDoubleRight":          ChevronDoubleRight,
	"ChevronDoubleUp":             ChevronDoubleUp,
	"ChevronDown":                 ChevronDown,
	"ChevronLeft":                 ChevronLeft,
	"ChevronRight":                ChevronRight,
	"ChevronUpDown":               ChevronUpDown,
	"ChevronUp":                   ChevronUp,
	"CircleStack":                 CircleStack,
	"ClipboardDocumentCheck":      ClipboardDocumentCheck,
	"ClipboardDocumentList":       ClipboardDocumentList,
	"ClipboardDocument":           ClipboardDocument,
	"Clipboard":                   Clipboard,
	"Clock":                       Clock,
	"CloudArrowDown":              CloudArrowDown,
	"CloudArrowUp":                CloudArrowUp,
	"Cloud":                       Cloud,
	"CodeBracketSquare":           CodeBracketSquare,
	"CodeBracket":                 CodeBracket,
	"Cog6Tooth":                   Cog6Tooth,
	"Cog8Tooth":                   Cog8Tooth,
	"Cog":                         Cog,
	"CommandLine":                 CommandLine,
	"ComputerDesktop":             ComputerDesktop,
	"CpuChip":                     CpuChip,
	"CreditCard":                  CreditCard,
	"CubeTransparent":             CubeTransparent,
	"Cube":                        Cube,
	"CurrencyBangladeshi":         CurrencyBangladeshi,
	"CurrencyDollar":              CurrencyDollar,
	"CurrencyEuro":                CurrencyEuro,
	"CurrencyPound":               CurrencyPound,
	"CurrencyRupee":               CurrencyRupee,
	"CurrencyYen":                 CurrencyYen,
	"CursorArrowRays":             CursorArrowRays,
	"CursorArrowRipple":           CursorArrowRipple,
	"DevicePhoneMobile":           DevicePhoneMobile,
	"DeviceTablet":                DeviceTablet,
	"Divide":                      Divide,
	"DocumentArrowDown":           DocumentArrowDown,
	"DocumentArrowUp":             DocumentArrowUp,
	"DocumentChartBar":            DocumentChartBar,
	"DocumentCheck":               DocumentCheck,
	"DocumentCurrencyBangladeshi": DocumentCurrencyBangladeshi,
	"DocumentCurrencyDollar":      DocumentCurrencyDollar,
	"DocumentCurrencyEuro":        DocumentCurrencyEuro,
	"DocumentCurrencyPound":       DocumentCurrencyPound,
	"DocumentCurrencyRupee":       DocumentCurrencyRupee,
	"DocumentCurrencyYen":         DocumentCurrencyYen,
	"DocumentDuplicate":           DocumentDuplicate,
	"DocumentMagnifyingGlass":     DocumentMagnifyingGlass,
	"DocumentMinus":               DocumentMinus,
	"DocumentPlus":                DocumentPlus,
	"DocumentText":                DocumentText,
	"Document":                    Document,
	"EllipsisHorizontalCircle":    EllipsisHorizontalCircle,
	"EllipsisHorizontal":          EllipsisHorizontal,
	"EllipsisVertical":            EllipsisVertical,
	"EnvelopeOpen":                EnvelopeOpen,
	"Envelope":                    Envelope,
	"Equals":                      Equals,
	"ExclamationCircle":           ExclamationCircle,
	"ExclamationTriangle":         ExclamationTriangle,
	"EyeDropper":                  EyeDropper,
	"EyeSlash":                    EyeSlash,
	"Eye":                         Eye,
	"FaceFrown":                   FaceFrown,
	"FaceSmile":                   FaceSmile,
	"Film":                        Film,
	"FingerPrint":                 FingerPrint,
	"Fire":                        Fire,
	"Flag":                        Flag,
	"FolderArrowDown":             FolderArrowDown,
	"FolderMinus":                 FolderMinus,
	"FolderOpen":                  FolderOpen,
	"FolderPlus":                  FolderPlus,
	"Folder":                      Folder,
	"Forward":                     Forward,
	"Funnel":                      Funnel,
	"Gif":                         Gif,
	"GiftTop":                     GiftTop,
	"Gift":                        Gift,
	"GlobeAlt":                    GlobeAlt,
	"GlobeAmericas":               GlobeAmericas,
	"GlobeAsiaAustralia":          GlobeAsiaAustralia,
	"GlobeEuropeAfrica":           GlobeEuropeAfrica,
	"H1":                          H1,
	"H2":                          H2,
	"H3":                          H3,
	"HandRaised":                  HandRaised,
	"HandThumbDown":               HandThumbDown,
	"HandThumbUp":                 HandThumbUp,
	"Hashtag":                     Hashtag,
	"Heart":                       Heart,
	"HomeModern":                  HomeModern,
	"Home":                        Home,
	"Identification":              Identification,
	"InboxArrowDown":              InboxArrowDown,
	"InboxStack":                  InboxStack,
	"Inbox":                       Inbox,
	"InformationCircle":           InformationCircle,
	"Italic":                      Italic,
	"Key":                         Key,
	"Language":                    Language,
	"Lifebuoy":                    Lifebuoy,
	"LightBulb":                   LightBulb,
	"LinkSlash":                   LinkSlash,
	"Link":                        Link,
	"ListBullet":                  ListBullet,
	"LockClosed":                  LockClosed,
	"LockOpen":                    LockOpen,
	"MagnifyingGlassCircle":       MagnifyingGlassCircle,
	"MagnifyingGlassMinus":        MagnifyingGlassMinus,
	"MagnifyingGlassPlus":         MagnifyingGlassPlus,
	"MagnifyingGlass":             MagnifyingGlass,
	"MapPin":                      MapPin,
	"Map":                         Map,
	"Megaphone":                   Megaphone,
	"Microphone":                  Microphone,
	"MinusCircle":                 MinusCircle,
	"MinusSmall":                  MinusSmall,
	"Minus":                       Minus,
	"Moon":                        Moon,
	"MusicalNote":                 MusicalNote,
	"Newspaper":                   Newspaper,
	"NoSymbol":                    NoSymbol,
	"NumberedList":                NumberedList,
	"PaintBrush":                  PaintBrush,
	"PaperAirplane":               PaperAirplane,
	"PaperClip":                   PaperClip,
	"PauseCircle":                 PauseCircle,
	"Pause":                       Pause,
	"PencilSquare":                PencilSquare,
	"Pencil":                      Pencil,
	"PercentBadge":                PercentBadge,
	"PhoneArrowDownLeft":          PhoneArrowDownLeft,
	"PhoneArrowUpRight":           PhoneArrowUpRight,
	"PhoneXMark":                  PhoneXMark,
	"Phone":                       Phone,
	"Photo":                       Photo,
	"PlayCircle":                  PlayCircle,
	"PlayPause":                   PlayPause,
	"Play":                        Play,
	"PlusCircle":                  PlusCircle,
	"PlusSmall":                   PlusSmall,
	"Plus":                        Plus,
	"Power":                       Power,
	"PresentationChartBar":        PresentationChartBar,
	"PresentationChartLine":       PresentationChartLine,
	"Printer":                     Printer,
	"PuzzlePiece":                 PuzzlePiece,
	"QrCode":                      QrCode,
	"QuestionMarkCircle":          QuestionMarkCircle,
	"QueueList":                   QueueList,
	"Radio":                       Radio,
	"ReceiptPercent":              ReceiptPercent,
	"ReceiptRefund":               ReceiptRefund,
	"RectangleGroup":              RectangleGroup,
	"RectangleStack":              RectangleStack,
	"RocketLaunch":                RocketLaunch,
	"Rss":                         Rss,
	"Scale":                       Scale,
	"Scissors":                    Scissors,
	"ServerStack":                 ServerStack,
	"Server":                      Server,
	"Share":                       Share,
	"ShieldCheck":                 ShieldCheck,
	"ShieldExclamation":           ShieldExclamation,
	"ShoppingBag":                 ShoppingBag,
	"ShoppingCart":                ShoppingCart,
	"SignalSlash":                 SignalSlash,
	"Signal":                      Signal,
	"Slash":                       Slash,
	"Sparkles":                    Sparkles,
	"SpeakerWave":                 SpeakerWave,
	"SpeakerXMark":                SpeakerXMark,
	"Square2Stack":                Square2Stack,
	"Square3Stack3d":              Square3Stack3d,
	"Squares2x2":                  Squares2x2,
	"SquaresPlus":                 SquaresPlus,
	"Star":                        Star,
	"StopCircle":                  StopCircle,
	"Stop":                        Stop,
	"Strikethrough":               Strikethrough,
	"Sun":                         Sun,
	"Swatch":                      Swatch,
	"TableCells":                  TableCells,
	"Tag":                         Tag,
	"Ticket":                      Ticket,
	"Trash":                       Trash,
	"Trophy":                      Trophy,
	"Truck":                       Truck,
	"Tv":                          Tv,
	"Underline":                   Underline,
	"UserCircle":                  UserCircle,
	"UserGroup":                   UserGroup,
	"UserMinus":                   UserMinus,
	"UserPlus":                    UserPlus,
	"User":                        User,
	"Users":                       Users,
	"Variable":                    Variable,
	"VideoCameraSlash":            VideoCameraSlash,
	"VideoCamera":                 VideoCamera,
	"ViewColumns":                 ViewColumns,
	"ViewfinderCircle":            ViewfinderCircle,
	"Wallet":                      Wallet,
	"Wifi":                        Wifi,
	"Window":                      Window,
	"WrenchScrewdriver":           WrenchScrewdriver,
	"Wrench":                      Wrench,
	"XCircle":                     XCircle,
	"XMark":                       XMark,
}
