// Code generated by cmd/embed-icons. DO NOT EDIT.

package icons

import (
	_ "embed"
	"go.wdy.de/nago/presentation/core"
)

//go:embed X.svg
var X core.SVG

//go:embed address-book.svg
var AddressBook core.SVG

//go:embed adjustments-horizontal.svg
var AdjustmentsHorizontal core.SVG

//go:embed adjustments-vertical.svg
var AdjustmentsVertical core.SVG

//go:embed annotation.svg
var Annotation core.SVG

//go:embed apple.svg
var Apple core.SVG

//go:embed archive-arrow-down.svg
var ArchiveArrowDown core.SVG

//go:embed archive.svg
var Archive core.SVG

//go:embed arrow-right-alt.svg
var ArrowRightAlt core.SVG

//go:embed arrow-up-right-from-square.svg
var ArrowUpRightFromSquare core.SVG

//go:embed award.svg
var Award core.SVG

//go:embed backward-step.svg
var BackwardStep core.SVG

//go:embed badge-check.svg
var BadgeCheck core.SVG

//go:embed bell-active-alt.svg
var BellActiveAlt core.SVG

//go:embed bell-active.svg
var BellActive core.SVG

//go:embed bell-ring.svg
var BellRing core.SVG

//go:embed bell.svg
var Bell core.SVG

//go:embed blender-phone.svg
var BlenderPhone core.SVG

//go:embed book-open.svg
var BookOpen core.SVG

//go:embed book.svg
var Book core.SVG

//go:embed bookmark.svg
var Bookmark core.SVG

//go:embed brain.svg
var Brain core.SVG

//go:embed briefcase.svg
var Briefcase core.SVG

//go:embed bug.svg
var Bug core.SVG

//go:embed building.svg
var Building core.SVG

//go:embed bullhorn.svg
var Bullhorn core.SVG

//go:embed calendar-edit.svg
var CalendarEdit core.SVG

//go:embed calendar-month.svg
var CalendarMonth core.SVG

//go:embed calendar-plus.svg
var CalendarPlus core.SVG

//go:embed calendar-week.svg
var CalendarWeek core.SVG

//go:embed camera-photo.svg
var CameraPhoto core.SVG

//go:embed caption.svg
var Caption core.SVG

//go:embed caret-down.svg
var CaretDown core.SVG

//go:embed caret-left.svg
var CaretLeft core.SVG

//go:embed caret-right.svg
var CaretRight core.SVG

//go:embed caret-sort.svg
var CaretSort core.SVG

//go:embed caret-up.svg
var CaretUp core.SVG

//go:embed cart-plus-alt.svg
var CartPlusAlt core.SVG

//go:embed cart-plus.svg
var CartPlus core.SVG

//go:embed cart.svg
var Cart core.SVG

//go:embed cash.svg
var Cash core.SVG

//go:embed chart-mixed-dollar.svg
var ChartMixedDollar core.SVG

//go:embed chart-pie.svg
var ChartPie core.SVG

//go:embed check-circle.svg
var CheckCircle core.SVG

//go:embed check-plus-circle.svg
var CheckPlusCircle core.SVG

//go:embed circle-minus.svg
var CircleMinus core.SVG

//go:embed circle-pause.svg
var CirclePause core.SVG

//go:embed circle-plus.svg
var CirclePlus core.SVG

//go:embed clapperboard-play.svg
var ClapperboardPlay core.SVG

//go:embed clipboard-check.svg
var ClipboardCheck core.SVG

//go:embed clipboard-clean.svg
var ClipboardClean core.SVG

//go:embed clipboard-list.svg
var ClipboardList core.SVG

//go:embed clipboard.svg
var Clipboard core.SVG

//go:embed clock.svg
var Clock core.SVG

//go:embed close-circle.svg
var CloseCircle core.SVG

//go:embed cloud-arrow-up.svg
var CloudArrowUp core.SVG

//go:embed code-branch.svg
var CodeBranch core.SVG

//go:embed code-fork.svg
var CodeFork core.SVG

//go:embed code-merge.svg
var CodeMerge core.SVG

//go:embed code-pull-request.svg
var CodePullRequest core.SVG

//go:embed cog.svg
var Cog core.SVG

//go:embed column.svg
var Column core.SVG

//go:embed computer-speaker.svg
var ComputerSpeaker core.SVG

//go:embed credit-card-plus.svg
var CreditCardPlus core.SVG

//go:embed credit-card.svg
var CreditCard core.SVG

//go:embed css.svg
var Css core.SVG

//go:embed database.svg
var Database core.SVG

//go:embed desktop-pc.svg
var DesktopPc core.SVG

//go:embed discord.svg
var Discord core.SVG

//go:embed download.svg
var Download core.SVG

//go:embed draw-square.svg
var DrawSquare core.SVG

//go:embed dribbble.svg
var Dribbble core.SVG

//go:embed dropbox.svg
var Dropbox core.SVG

//go:embed edit.svg
var Edit core.SVG

//go:embed envelope-open.svg
var EnvelopeOpen core.SVG

//go:embed envelope.svg
var Envelope core.SVG

//go:embed exclamation-circle.svg
var ExclamationCircle core.SVG

//go:embed eye-slash.svg
var EyeSlash core.SVG

//go:embed eye.svg
var Eye core.SVG

//go:embed face-explode.svg
var FaceExplode core.SVG

//go:embed face-grin-stars.svg
var FaceGrinStars core.SVG

//go:embed face-grin.svg
var FaceGrin core.SVG

//go:embed face-laugh.svg
var FaceLaugh core.SVG

//go:embed facebook.svg
var Facebook core.SVG

//go:embed file-chart-bar.svg
var FileChartBar core.SVG

//go:embed file-check.svg
var FileCheck core.SVG

//go:embed file-circle-plus.svg
var FileCirclePlus core.SVG

//go:embed file-clone.svg
var FileClone core.SVG

//go:embed file-code.svg
var FileCode core.SVG

//go:embed file-copy-alt.svg
var FileCopyAlt core.SVG

//go:embed file-copy.svg
var FileCopy core.SVG

//go:embed file-csv.svg
var FileCsv core.SVG

//go:embed file-doc.svg
var FileDoc core.SVG

//go:embed file-export.svg
var FileExport core.SVG

//go:embed file-image.svg
var FileImage core.SVG

//go:embed file-import.svg
var FileImport core.SVG

//go:embed file-invoice.svg
var FileInvoice core.SVG

//go:embed file-lines.svg
var FileLines core.SVG

//go:embed file-music.svg
var FileMusic core.SVG

//go:embed file-paste.svg
var FilePaste core.SVG

//go:embed file-pdf.svg
var FilePdf core.SVG

//go:embed file-pen.svg
var FilePen core.SVG

//go:embed file-ppt.svg
var FilePpt core.SVG

//go:embed file-search.svg
var FileSearch core.SVG

//go:embed file-shield.svg
var FileShield core.SVG

//go:embed file-video.svg
var FileVideo core.SVG

//go:embed file-word.svg
var FileWord core.SVG

//go:embed file-zip.svg
var FileZip core.SVG

//go:embed file.svg
var File core.SVG

//go:embed filter.svg
var Filter core.SVG

//go:embed fire.svg
var Fire core.SVG

//go:embed flag.svg
var Flag core.SVG

//go:embed floppy-disk-alt.svg
var FloppyDiskAlt core.SVG

//go:embed floppy-disk.svg
var FloppyDisk core.SVG

//go:embed flowbite.svg
var Flowbite core.SVG

//go:embed folder-arrow-right.svg
var FolderArrowRight core.SVG

//go:embed folder-duplicate.svg
var FolderDuplicate core.SVG

//go:embed folder-open.svg
var FolderOpen core.SVG

//go:embed folder-plus.svg
var FolderPlus core.SVG

//go:embed folder.svg
var Folder core.SVG

//go:embed forward-step.svg
var ForwardStep core.SVG

//go:embed forward.svg
var Forward core.SVG

//go:embed gift-box.svg
var GiftBox core.SVG

//go:embed github.svg
var Github core.SVG

//go:embed globe.svg
var Globe core.SVG

//go:embed google.svg
var Google core.SVG

//go:embed grid-plus.svg
var GridPlus core.SVG

//go:embed grid.svg
var Grid core.SVG

//go:embed headphones.svg
var Headphones core.SVG

//go:embed heart.svg
var Heart core.SVG

//go:embed home.svg
var Home core.SVG

//go:embed hourglass.svg
var Hourglass core.SVG

//go:embed html.svg
var Html core.SVG

//go:embed image.svg
var Image core.SVG

//go:embed inbox-full.svg
var InboxFull core.SVG

//go:embed inbox.svg
var Inbox core.SVG

//go:embed indent.svg
var Indent core.SVG

//go:embed info-circle.svg
var InfoCircle core.SVG

//go:embed instagram.svg
var Instagram core.SVG

//go:embed keyboard.svg
var Keyboard core.SVG

//go:embed label.svg
var Label core.SVG

//go:embed landmark.svg
var Landmark core.SVG

//go:embed layers.svg
var Layers core.SVG

//go:embed life-saver.svg
var LifeSaver core.SVG

//go:embed lightbulb.svg
var Lightbulb core.SVG

//go:embed linkedin.svg
var Linkedin core.SVG

//go:embed list-music.svg
var ListMusic core.SVG

//go:embed lock-open.svg
var LockOpen core.SVG

//go:embed lock-time.svg
var LockTime core.SVG

//go:embed lock.svg
var Lock core.SVG

//go:embed mail-box.svg
var MailBox core.SVG

//go:embed map-pin-alt.svg
var MapPinAlt core.SVG

//go:embed map-pin.svg
var MapPin core.SVG

//go:embed mastercard.svg
var Mastercard core.SVG

//go:embed message-caption.svg
var MessageCaption core.SVG

//go:embed message-dots.svg
var MessageDots core.SVG

//go:embed messages.svg
var Messages core.SVG

//go:embed microphone-slash.svg
var MicrophoneSlash core.SVG

//go:embed microphone.svg
var Microphone core.SVG

//go:embed mobile-phone.svg
var MobilePhone core.SVG

//go:embed moon.svg
var Moon core.SVG

//go:embed newspaper.svg
var Newspaper core.SVG

//go:embed npm.svg
var Npm core.SVG

//go:embed objects-column.svg
var ObjectsColumn core.SVG

//go:embed outdent.svg
var Outdent core.SVG

//go:embed palette.svg
var Palette core.SVG

//go:embed paper-plane.svg
var PaperPlane core.SVG

//go:embed paragraph.svg
var Paragraph core.SVG

//go:embed pause.svg
var Pause core.SVG

//go:embed pen-nib.svg
var PenNib core.SVG

//go:embed pen.svg
var Pen core.SVG

//go:embed phone-hangup.svg
var PhoneHangup core.SVG

//go:embed phone.svg
var Phone core.SVG

//go:embed play.svg
var Play core.SVG

//go:embed printer.svg
var Printer core.SVG

//go:embed profile-card.svg
var ProfileCard core.SVG

//go:embed question-circle.svg
var QuestionCircle core.SVG

//go:embed quote.svg
var Quote core.SVG

//go:embed react.svg
var React core.SVG

//go:embed receipt.svg
var Receipt core.SVG

//go:embed rectangle-list.svg
var RectangleList core.SVG

//go:embed reddit.svg
var Reddit core.SVG

//go:embed reply-all.svg
var ReplyAll core.SVG

//go:embed reply.svg
var Reply core.SVG

//go:embed rocket.svg
var Rocket core.SVG

//go:embed sale-percent.svg
var SalePercent core.SVG

//go:embed scale-balanced.svg
var ScaleBalanced core.SVG

//go:embed search.svg
var Search core.SVG

//go:embed server.svg
var Server core.SVG

//go:embed share-all.svg
var ShareAll core.SVG

//go:embed share-nodes.svg
var ShareNodes core.SVG

//go:embed shield-check.svg
var ShieldCheck core.SVG

//go:embed shield.svg
var Shield core.SVG

//go:embed shopping-bag.svg
var ShoppingBag core.SVG

//go:embed stackoverflow.svg
var Stackoverflow core.SVG

//go:embed star-half-stroke.svg
var StarHalfStroke core.SVG

//go:embed star-half.svg
var StarHalf core.SVG

//go:embed star.svg
var Star core.SVG

//go:embed stop.svg
var Stop core.SVG

//go:embed store.svg
var Store core.SVG

//go:embed sun.svg
var Sun core.SVG

//go:embed swatchbook.svg
var Swatchbook core.SVG

//go:embed table-column.svg
var TableColumn core.SVG

//go:embed table-row.svg
var TableRow core.SVG

//go:embed tablet.svg
var Tablet core.SVG

//go:embed tag.svg
var Tag core.SVG

//go:embed tailwind.svg
var Tailwind core.SVG

//go:embed terminal.svg
var Terminal core.SVG

//go:embed thumbs-down.svg
var ThumbsDown core.SVG

//go:embed thumbs-up.svg
var ThumbsUp core.SVG

//go:embed ticket.svg
var Ticket core.SVG

//go:embed trash-bin.svg
var TrashBin core.SVG

//go:embed truck.svg
var Truck core.SVG

//go:embed twitter.svg
var Twitter core.SVG

//go:embed upload.svg
var Upload core.SVG

//go:embed user-add.svg
var UserAdd core.SVG

//go:embed user-circle.svg
var UserCircle core.SVG

//go:embed user-edit.svg
var UserEdit core.SVG

//go:embed user-headset.svg
var UserHeadset core.SVG

//go:embed user-remove.svg
var UserRemove core.SVG

//go:embed user-settings.svg
var UserSettings core.SVG

//go:embed user.svg
var User core.SVG

//go:embed users-group.svg
var UsersGroup core.SVG

//go:embed users.svg
var Users core.SVG

//go:embed video-camera.svg
var VideoCamera core.SVG

//go:embed visa.svg
var Visa core.SVG

//go:embed volume-down.svg
var VolumeDown core.SVG

//go:embed volume-mute.svg
var VolumeMute core.SVG

//go:embed volume-up.svg
var VolumeUp core.SVG

//go:embed vue.svg
var Vue core.SVG

//go:embed wallet.svg
var Wallet core.SVG

//go:embed wand-magic-sparkles.svg
var WandMagicSparkles core.SVG

//go:embed whatsapp.svg
var Whatsapp core.SVG

//go:embed window-restore.svg
var WindowRestore core.SVG

//go:embed window.svg
var Window core.SVG

//go:embed windows.svg
var Windows core.SVG

//go:embed youtube.svg
var Youtube core.SVG

//go:embed zoom-in.svg
var ZoomIn core.SVG

//go:embed zoom-out.svg
var ZoomOut core.SVG

var All = map[string]core.SVG{
	"X":                      X,
	"AddressBook":            AddressBook,
	"AdjustmentsHorizontal":  AdjustmentsHorizontal,
	"AdjustmentsVertical":    AdjustmentsVertical,
	"Annotation":             Annotation,
	"Apple":                  Apple,
	"ArchiveArrowDown":       ArchiveArrowDown,
	"Archive":                Archive,
	"ArrowRightAlt":          ArrowRightAlt,
	"ArrowUpRightFromSquare": ArrowUpRightFromSquare,
	"Award":                  Award,
	"BackwardStep":           BackwardStep,
	"BadgeCheck":             BadgeCheck,
	"BellActiveAlt":          BellActiveAlt,
	"BellActive":             BellActive,
	"BellRing":               BellRing,
	"Bell":                   Bell,
	"BlenderPhone":           BlenderPhone,
	"BookOpen":               BookOpen,
	"Book":                   Book,
	"Bookmark":               Bookmark,
	"Brain":                  Brain,
	"Briefcase":              Briefcase,
	"Bug":                    Bug,
	"Building":               Building,
	"Bullhorn":               Bullhorn,
	"CalendarEdit":           CalendarEdit,
	"CalendarMonth":          CalendarMonth,
	"CalendarPlus":           CalendarPlus,
	"CalendarWeek":           CalendarWeek,
	"CameraPhoto":            CameraPhoto,
	"Caption":                Caption,
	"CaretDown":              CaretDown,
	"CaretLeft":              CaretLeft,
	"CaretRight":             CaretRight,
	"CaretSort":              CaretSort,
	"CaretUp":                CaretUp,
	"CartPlusAlt":            CartPlusAlt,
	"CartPlus":               CartPlus,
	"Cart":                   Cart,
	"Cash":                   Cash,
	"ChartMixedDollar":       ChartMixedDollar,
	"ChartPie":               ChartPie,
	"CheckCircle":            CheckCircle,
	"CheckPlusCircle":        CheckPlusCircle,
	"CircleMinus":            CircleMinus,
	"CirclePause":            CirclePause,
	"CirclePlus":             CirclePlus,
	"ClapperboardPlay":       ClapperboardPlay,
	"ClipboardCheck":         ClipboardCheck,
	"ClipboardClean":         ClipboardClean,
	"ClipboardList":          ClipboardList,
	"Clipboard":              Clipboard,
	"Clock":                  Clock,
	"CloseCircle":            CloseCircle,
	"CloudArrowUp":           CloudArrowUp,
	"CodeBranch":             CodeBranch,
	"CodeFork":               CodeFork,
	"CodeMerge":              CodeMerge,
	"CodePullRequest":        CodePullRequest,
	"Cog":                    Cog,
	"Column":                 Column,
	"ComputerSpeaker":        ComputerSpeaker,
	"CreditCardPlus":         CreditCardPlus,
	"CreditCard":             CreditCard,
	"Css":                    Css,
	"Database":               Database,
	"DesktopPc":              DesktopPc,
	"Discord":                Discord,
	"Download":               Download,
	"DrawSquare":             DrawSquare,
	"Dribbble":               Dribbble,
	"Dropbox":                Dropbox,
	"Edit":                   Edit,
	"EnvelopeOpen":           EnvelopeOpen,
	"Envelope":               Envelope,
	"ExclamationCircle":      ExclamationCircle,
	"EyeSlash":               EyeSlash,
	"Eye":                    Eye,
	"FaceExplode":            FaceExplode,
	"FaceGrinStars":          FaceGrinStars,
	"FaceGrin":               FaceGrin,
	"FaceLaugh":              FaceLaugh,
	"Facebook":               Facebook,
	"FileChartBar":           FileChartBar,
	"FileCheck":              FileCheck,
	"FileCirclePlus":         FileCirclePlus,
	"FileClone":              FileClone,
	"FileCode":               FileCode,
	"FileCopyAlt":            FileCopyAlt,
	"FileCopy":               FileCopy,
	"FileCsv":                FileCsv,
	"FileDoc":                FileDoc,
	"FileExport":             FileExport,
	"FileImage":              FileImage,
	"FileImport":             FileImport,
	"FileInvoice":            FileInvoice,
	"FileLines":              FileLines,
	"FileMusic":              FileMusic,
	"FilePaste":              FilePaste,
	"FilePdf":                FilePdf,
	"FilePen":                FilePen,
	"FilePpt":                FilePpt,
	"FileSearch":             FileSearch,
	"FileShield":             FileShield,
	"FileVideo":              FileVideo,
	"FileWord":               FileWord,
	"FileZip":                FileZip,
	"File":                   File,
	"Filter":                 Filter,
	"Fire":                   Fire,
	"Flag":                   Flag,
	"FloppyDiskAlt":          FloppyDiskAlt,
	"FloppyDisk":             FloppyDisk,
	"Flowbite":               Flowbite,
	"FolderArrowRight":       FolderArrowRight,
	"FolderDuplicate":        FolderDuplicate,
	"FolderOpen":             FolderOpen,
	"FolderPlus":             FolderPlus,
	"Folder":                 Folder,
	"ForwardStep":            ForwardStep,
	"Forward":                Forward,
	"GiftBox":                GiftBox,
	"Github":                 Github,
	"Globe":                  Globe,
	"Google":                 Google,
	"GridPlus":               GridPlus,
	"Grid":                   Grid,
	"Headphones":             Headphones,
	"Heart":                  Heart,
	"Home":                   Home,
	"Hourglass":              Hourglass,
	"Html":                   Html,
	"Image":                  Image,
	"InboxFull":              InboxFull,
	"Inbox":                  Inbox,
	"Indent":                 Indent,
	"InfoCircle":             InfoCircle,
	"Instagram":              Instagram,
	"Keyboard":               Keyboard,
	"Label":                  Label,
	"Landmark":               Landmark,
	"Layers":                 Layers,
	"LifeSaver":              LifeSaver,
	"Lightbulb":              Lightbulb,
	"Linkedin":               Linkedin,
	"ListMusic":              ListMusic,
	"LockOpen":               LockOpen,
	"LockTime":               LockTime,
	"Lock":                   Lock,
	"MailBox":                MailBox,
	"MapPinAlt":              MapPinAlt,
	"MapPin":                 MapPin,
	"Mastercard":             Mastercard,
	"MessageCaption":         MessageCaption,
	"MessageDots":            MessageDots,
	"Messages":               Messages,
	"MicrophoneSlash":        MicrophoneSlash,
	"Microphone":             Microphone,
	"MobilePhone":            MobilePhone,
	"Moon":                   Moon,
	"Newspaper":              Newspaper,
	"Npm":                    Npm,
	"ObjectsColumn":          ObjectsColumn,
	"Outdent":                Outdent,
	"Palette":                Palette,
	"PaperPlane":             PaperPlane,
	"Paragraph":              Paragraph,
	"Pause":                  Pause,
	"PenNib":                 PenNib,
	"Pen":                    Pen,
	"PhoneHangup":            PhoneHangup,
	"Phone":                  Phone,
	"Play":                   Play,
	"Printer":                Printer,
	"ProfileCard":            ProfileCard,
	"QuestionCircle":         QuestionCircle,
	"Quote":                  Quote,
	"React":                  React,
	"Receipt":                Receipt,
	"RectangleList":          RectangleList,
	"Reddit":                 Reddit,
	"ReplyAll":               ReplyAll,
	"Reply":                  Reply,
	"Rocket":                 Rocket,
	"SalePercent":            SalePercent,
	"ScaleBalanced":          ScaleBalanced,
	"Search":                 Search,
	"Server":                 Server,
	"ShareAll":               ShareAll,
	"ShareNodes":             ShareNodes,
	"ShieldCheck":            ShieldCheck,
	"Shield":                 Shield,
	"ShoppingBag":            ShoppingBag,
	"Stackoverflow":          Stackoverflow,
	"StarHalfStroke":         StarHalfStroke,
	"StarHalf":               StarHalf,
	"Star":                   Star,
	"Stop":                   Stop,
	"Store":                  Store,
	"Sun":                    Sun,
	"Swatchbook":             Swatchbook,
	"TableColumn":            TableColumn,
	"TableRow":               TableRow,
	"Tablet":                 Tablet,
	"Tag":                    Tag,
	"Tailwind":               Tailwind,
	"Terminal":               Terminal,
	"ThumbsDown":             ThumbsDown,
	"ThumbsUp":               ThumbsUp,
	"Ticket":                 Ticket,
	"TrashBin":               TrashBin,
	"Truck":                  Truck,
	"Twitter":                Twitter,
	"Upload":                 Upload,
	"UserAdd":                UserAdd,
	"UserCircle":             UserCircle,
	"UserEdit":               UserEdit,
	"UserHeadset":            UserHeadset,
	"UserRemove":             UserRemove,
	"UserSettings":           UserSettings,
	"User":                   User,
	"UsersGroup":             UsersGroup,
	"Users":                  Users,
	"VideoCamera":            VideoCamera,
	"Visa":                   Visa,
	"VolumeDown":             VolumeDown,
	"VolumeMute":             VolumeMute,
	"VolumeUp":               VolumeUp,
	"Vue":                    Vue,
	"Wallet":                 Wallet,
	"WandMagicSparkles":      WandMagicSparkles,
	"Whatsapp":               Whatsapp,
	"WindowRestore":          WindowRestore,
	"Window":                 Window,
	"Windows":                Windows,
	"Youtube":                Youtube,
	"ZoomIn":                 ZoomIn,
	"ZoomOut":                ZoomOut,
}
