// Code generated by cmd/embed-icons. DO NOT EDIT.

package icons

import (
	_ "embed"
	"go.wdy.de/nago/presentation/core"
)

{{range .Vars}}
//go:embed {{.Filename}}
var {{.Varname}} core.SVG
{{end}}


var All = map[string]core.SVG{
    {{range .Vars -}}
    "{{- .Varname}}" : {{.Varname -}},
    {{end}}
}
