// Code generated by NAGO nprotoc DO NOT EDIT.

package {{.PackageName}}

import(
	"bytes"
	"encoding/binary"
	"fmt"
	"math"
	"unsafe"
)

func isZeroComponent(c Component) bool {
    return c==nil || c.IsZero()
}

{{.BinaryWriter}}

{{range .Marshals}}
{{.}}
{{end}}