// Code generated by NAGO nprotoc DO NOT EDIT.

package {{.PackageName}}

import(
	"bytes"
	"encoding/binary"
	"fmt"
	"math"
	"unsafe"
	"reflect"
)

{{.BinaryWriter}}

{{range .Marshals}}
{{.}}
{{end}}