// Code generated by cmd/embed-icons. DO NOT EDIT.

package icons

import (
	_ "embed"
	"go.wdy.de/nago/presentation/ora"
)

//go:embed academic-cap.svg
var AcademicCap ora.SVG

//go:embed adjustments-horizontal.svg
var AdjustmentsHorizontal ora.SVG

//go:embed adjustments-vertical.svg
var AdjustmentsVertical ora.SVG

//go:embed archive-box-arrow-down.svg
var ArchiveBoxArrowDown ora.SVG

//go:embed archive-box-x-mark.svg
var ArchiveBoxXMark ora.SVG

//go:embed archive-box.svg
var ArchiveBox ora.SVG

//go:embed arrow-down-circle.svg
var ArrowDownCircle ora.SVG

//go:embed arrow-down-left.svg
var ArrowDownLeft ora.SVG

//go:embed arrow-down-on-square-stack.svg
var ArrowDownOnSquareStack ora.SVG

//go:embed arrow-down-on-square.svg
var ArrowDownOnSquare ora.SVG

//go:embed arrow-down-right.svg
var ArrowDownRight ora.SVG

//go:embed arrow-down-tray.svg
var ArrowDownTray ora.SVG

//go:embed arrow-down.svg
var ArrowDown ora.SVG

//go:embed arrow-left-circle.svg
var ArrowLeftCircle ora.SVG

//go:embed arrow-left-end-on-rectangle.svg
var ArrowLeftEndOnRectangle ora.SVG

//go:embed arrow-left-on-rectangle.svg
var ArrowLeftOnRectangle ora.SVG

//go:embed arrow-left-start-on-rectangle.svg
var ArrowLeftStartOnRectangle ora.SVG

//go:embed arrow-left.svg
var ArrowLeft ora.SVG

//go:embed arrow-long-down.svg
var ArrowLongDown ora.SVG

//go:embed arrow-long-left.svg
var ArrowLongLeft ora.SVG

//go:embed arrow-long-right.svg
var ArrowLongRight ora.SVG

//go:embed arrow-long-up.svg
var ArrowLongUp ora.SVG

//go:embed arrow-path-rounded-square.svg
var ArrowPathRoundedSquare ora.SVG

//go:embed arrow-path.svg
var ArrowPath ora.SVG

//go:embed arrow-right-circle.svg
var ArrowRightCircle ora.SVG

//go:embed arrow-right-end-on-rectangle.svg
var ArrowRightEndOnRectangle ora.SVG

//go:embed arrow-right-on-rectangle.svg
var ArrowRightOnRectangle ora.SVG

//go:embed arrow-right-start-on-rectangle.svg
var ArrowRightStartOnRectangle ora.SVG

//go:embed arrow-right.svg
var ArrowRight ora.SVG

//go:embed arrow-small-down.svg
var ArrowSmallDown ora.SVG

//go:embed arrow-small-left.svg
var ArrowSmallLeft ora.SVG

//go:embed arrow-small-right.svg
var ArrowSmallRight ora.SVG

//go:embed arrow-small-up.svg
var ArrowSmallUp ora.SVG

//go:embed arrow-top-right-on-square.svg
var ArrowTopRightOnSquare ora.SVG

//go:embed arrow-trending-down.svg
var ArrowTrendingDown ora.SVG

//go:embed arrow-trending-up.svg
var ArrowTrendingUp ora.SVG

//go:embed arrow-turn-down-left.svg
var ArrowTurnDownLeft ora.SVG

//go:embed arrow-turn-down-right.svg
var ArrowTurnDownRight ora.SVG

//go:embed arrow-turn-left-down.svg
var ArrowTurnLeftDown ora.SVG

//go:embed arrow-turn-left-up.svg
var ArrowTurnLeftUp ora.SVG

//go:embed arrow-turn-right-down.svg
var ArrowTurnRightDown ora.SVG

//go:embed arrow-turn-right-up.svg
var ArrowTurnRightUp ora.SVG

//go:embed arrow-turn-up-left.svg
var ArrowTurnUpLeft ora.SVG

//go:embed arrow-turn-up-right.svg
var ArrowTurnUpRight ora.SVG

//go:embed arrow-up-circle.svg
var ArrowUpCircle ora.SVG

//go:embed arrow-up-left.svg
var ArrowUpLeft ora.SVG

//go:embed arrow-up-on-square-stack.svg
var ArrowUpOnSquareStack ora.SVG

//go:embed arrow-up-on-square.svg
var ArrowUpOnSquare ora.SVG

//go:embed arrow-up-right.svg
var ArrowUpRight ora.SVG

//go:embed arrow-up-tray.svg
var ArrowUpTray ora.SVG

//go:embed arrow-up.svg
var ArrowUp ora.SVG

//go:embed arrow-uturn-down.svg
var ArrowUturnDown ora.SVG

//go:embed arrow-uturn-left.svg
var ArrowUturnLeft ora.SVG

//go:embed arrow-uturn-right.svg
var ArrowUturnRight ora.SVG

//go:embed arrow-uturn-up.svg
var ArrowUturnUp ora.SVG

//go:embed arrows-pointing-in.svg
var ArrowsPointingIn ora.SVG

//go:embed arrows-pointing-out.svg
var ArrowsPointingOut ora.SVG

//go:embed arrows-right-left.svg
var ArrowsRightLeft ora.SVG

//go:embed arrows-up-down.svg
var ArrowsUpDown ora.SVG

//go:embed at-symbol.svg
var AtSymbol ora.SVG

//go:embed backspace.svg
var Backspace ora.SVG

//go:embed backward.svg
var Backward ora.SVG

//go:embed banknotes.svg
var Banknotes ora.SVG

//go:embed bars-2.svg
var Bars2 ora.SVG

//go:embed bars-3-bottom-left.svg
var Bars3BottomLeft ora.SVG

//go:embed bars-3-bottom-right.svg
var Bars3BottomRight ora.SVG

//go:embed bars-3-center-left.svg
var Bars3CenterLeft ora.SVG

//go:embed bars-3.svg
var Bars3 ora.SVG

//go:embed bars-4.svg
var Bars4 ora.SVG

//go:embed bars-arrow-down.svg
var BarsArrowDown ora.SVG

//go:embed bars-arrow-up.svg
var BarsArrowUp ora.SVG

//go:embed battery-0.svg
var Battery0 ora.SVG

//go:embed battery-100.svg
var Battery100 ora.SVG

//go:embed battery-50.svg
var Battery50 ora.SVG

//go:embed beaker.svg
var Beaker ora.SVG

//go:embed bell-alert.svg
var BellAlert ora.SVG

//go:embed bell-slash.svg
var BellSlash ora.SVG

//go:embed bell-snooze.svg
var BellSnooze ora.SVG

//go:embed bell.svg
var Bell ora.SVG

//go:embed bold.svg
var Bold ora.SVG

//go:embed bolt-slash.svg
var BoltSlash ora.SVG

//go:embed bolt.svg
var Bolt ora.SVG

//go:embed book-open.svg
var BookOpen ora.SVG

//go:embed bookmark-slash.svg
var BookmarkSlash ora.SVG

//go:embed bookmark-square.svg
var BookmarkSquare ora.SVG

//go:embed bookmark.svg
var Bookmark ora.SVG

//go:embed briefcase.svg
var Briefcase ora.SVG

//go:embed bug-ant.svg
var BugAnt ora.SVG

//go:embed building-library.svg
var BuildingLibrary ora.SVG

//go:embed building-office-2.svg
var BuildingOffice2 ora.SVG

//go:embed building-office.svg
var BuildingOffice ora.SVG

//go:embed building-storefront.svg
var BuildingStorefront ora.SVG

//go:embed cake.svg
var Cake ora.SVG

//go:embed calculator.svg
var Calculator ora.SVG

//go:embed calendar-date-range.svg
var CalendarDateRange ora.SVG

//go:embed calendar-days.svg
var CalendarDays ora.SVG

//go:embed calendar.svg
var Calendar ora.SVG

//go:embed camera.svg
var Camera ora.SVG

//go:embed chart-bar-square.svg
var ChartBarSquare ora.SVG

//go:embed chart-bar.svg
var ChartBar ora.SVG

//go:embed chart-pie.svg
var ChartPie ora.SVG

//go:embed chat-bubble-bottom-center-text.svg
var ChatBubbleBottomCenterText ora.SVG

//go:embed chat-bubble-bottom-center.svg
var ChatBubbleBottomCenter ora.SVG

//go:embed chat-bubble-left-ellipsis.svg
var ChatBubbleLeftEllipsis ora.SVG

//go:embed chat-bubble-left-right.svg
var ChatBubbleLeftRight ora.SVG

//go:embed chat-bubble-left.svg
var ChatBubbleLeft ora.SVG

//go:embed chat-bubble-oval-left-ellipsis.svg
var ChatBubbleOvalLeftEllipsis ora.SVG

//go:embed chat-bubble-oval-left.svg
var ChatBubbleOvalLeft ora.SVG

//go:embed check-badge.svg
var CheckBadge ora.SVG

//go:embed check-circle.svg
var CheckCircle ora.SVG

//go:embed check.svg
var Check ora.SVG

//go:embed chevron-double-down.svg
var ChevronDoubleDown ora.SVG

//go:embed chevron-double-left.svg
var ChevronDoubleLeft ora.SVG

//go:embed chevron-double-right.svg
var ChevronDoubleRight ora.SVG

//go:embed chevron-double-up.svg
var ChevronDoubleUp ora.SVG

//go:embed chevron-down.svg
var ChevronDown ora.SVG

//go:embed chevron-left.svg
var ChevronLeft ora.SVG

//go:embed chevron-right.svg
var ChevronRight ora.SVG

//go:embed chevron-up-down.svg
var ChevronUpDown ora.SVG

//go:embed chevron-up.svg
var ChevronUp ora.SVG

//go:embed circle-stack.svg
var CircleStack ora.SVG

//go:embed clipboard-document-check.svg
var ClipboardDocumentCheck ora.SVG

//go:embed clipboard-document-list.svg
var ClipboardDocumentList ora.SVG

//go:embed clipboard-document.svg
var ClipboardDocument ora.SVG

//go:embed clipboard.svg
var Clipboard ora.SVG

//go:embed clock.svg
var Clock ora.SVG

//go:embed cloud-arrow-down.svg
var CloudArrowDown ora.SVG

//go:embed cloud-arrow-up.svg
var CloudArrowUp ora.SVG

//go:embed cloud.svg
var Cloud ora.SVG

//go:embed code-bracket-square.svg
var CodeBracketSquare ora.SVG

//go:embed code-bracket.svg
var CodeBracket ora.SVG

//go:embed cog-6-tooth.svg
var Cog6Tooth ora.SVG

//go:embed cog-8-tooth.svg
var Cog8Tooth ora.SVG

//go:embed cog.svg
var Cog ora.SVG

//go:embed command-line.svg
var CommandLine ora.SVG

//go:embed computer-desktop.svg
var ComputerDesktop ora.SVG

//go:embed cpu-chip.svg
var CpuChip ora.SVG

//go:embed credit-card.svg
var CreditCard ora.SVG

//go:embed cube-transparent.svg
var CubeTransparent ora.SVG

//go:embed cube.svg
var Cube ora.SVG

//go:embed currency-bangladeshi.svg
var CurrencyBangladeshi ora.SVG

//go:embed currency-dollar.svg
var CurrencyDollar ora.SVG

//go:embed currency-euro.svg
var CurrencyEuro ora.SVG

//go:embed currency-pound.svg
var CurrencyPound ora.SVG

//go:embed currency-rupee.svg
var CurrencyRupee ora.SVG

//go:embed currency-yen.svg
var CurrencyYen ora.SVG

//go:embed cursor-arrow-rays.svg
var CursorArrowRays ora.SVG

//go:embed cursor-arrow-ripple.svg
var CursorArrowRipple ora.SVG

//go:embed device-phone-mobile.svg
var DevicePhoneMobile ora.SVG

//go:embed device-tablet.svg
var DeviceTablet ora.SVG

//go:embed divide.svg
var Divide ora.SVG

//go:embed document-arrow-down.svg
var DocumentArrowDown ora.SVG

//go:embed document-arrow-up.svg
var DocumentArrowUp ora.SVG

//go:embed document-chart-bar.svg
var DocumentChartBar ora.SVG

//go:embed document-check.svg
var DocumentCheck ora.SVG

//go:embed document-currency-bangladeshi.svg
var DocumentCurrencyBangladeshi ora.SVG

//go:embed document-currency-dollar.svg
var DocumentCurrencyDollar ora.SVG

//go:embed document-currency-euro.svg
var DocumentCurrencyEuro ora.SVG

//go:embed document-currency-pound.svg
var DocumentCurrencyPound ora.SVG

//go:embed document-currency-rupee.svg
var DocumentCurrencyRupee ora.SVG

//go:embed document-currency-yen.svg
var DocumentCurrencyYen ora.SVG

//go:embed document-duplicate.svg
var DocumentDuplicate ora.SVG

//go:embed document-magnifying-glass.svg
var DocumentMagnifyingGlass ora.SVG

//go:embed document-minus.svg
var DocumentMinus ora.SVG

//go:embed document-plus.svg
var DocumentPlus ora.SVG

//go:embed document-text.svg
var DocumentText ora.SVG

//go:embed document.svg
var Document ora.SVG

//go:embed ellipsis-horizontal-circle.svg
var EllipsisHorizontalCircle ora.SVG

//go:embed ellipsis-horizontal.svg
var EllipsisHorizontal ora.SVG

//go:embed ellipsis-vertical.svg
var EllipsisVertical ora.SVG

//go:embed envelope-open.svg
var EnvelopeOpen ora.SVG

//go:embed envelope.svg
var Envelope ora.SVG

//go:embed equals.svg
var Equals ora.SVG

//go:embed exclamation-circle.svg
var ExclamationCircle ora.SVG

//go:embed exclamation-triangle.svg
var ExclamationTriangle ora.SVG

//go:embed eye-dropper.svg
var EyeDropper ora.SVG

//go:embed eye-slash.svg
var EyeSlash ora.SVG

//go:embed eye.svg
var Eye ora.SVG

//go:embed face-frown.svg
var FaceFrown ora.SVG

//go:embed face-smile.svg
var FaceSmile ora.SVG

//go:embed film.svg
var Film ora.SVG

//go:embed finger-print.svg
var FingerPrint ora.SVG

//go:embed fire.svg
var Fire ora.SVG

//go:embed flag.svg
var Flag ora.SVG

//go:embed folder-arrow-down.svg
var FolderArrowDown ora.SVG

//go:embed folder-minus.svg
var FolderMinus ora.SVG

//go:embed folder-open.svg
var FolderOpen ora.SVG

//go:embed folder-plus.svg
var FolderPlus ora.SVG

//go:embed folder.svg
var Folder ora.SVG

//go:embed forward.svg
var Forward ora.SVG

//go:embed funnel.svg
var Funnel ora.SVG

//go:embed gif.svg
var Gif ora.SVG

//go:embed gift-top.svg
var GiftTop ora.SVG

//go:embed gift.svg
var Gift ora.SVG

//go:embed globe-alt.svg
var GlobeAlt ora.SVG

//go:embed globe-americas.svg
var GlobeAmericas ora.SVG

//go:embed globe-asia-australia.svg
var GlobeAsiaAustralia ora.SVG

//go:embed globe-europe-africa.svg
var GlobeEuropeAfrica ora.SVG

//go:embed h1.svg
var H1 ora.SVG

//go:embed h2.svg
var H2 ora.SVG

//go:embed h3.svg
var H3 ora.SVG

//go:embed hand-raised.svg
var HandRaised ora.SVG

//go:embed hand-thumb-down.svg
var HandThumbDown ora.SVG

//go:embed hand-thumb-up.svg
var HandThumbUp ora.SVG

//go:embed hashtag.svg
var Hashtag ora.SVG

//go:embed heart.svg
var Heart ora.SVG

//go:embed home-modern.svg
var HomeModern ora.SVG

//go:embed home.svg
var Home ora.SVG

//go:embed identification.svg
var Identification ora.SVG

//go:embed inbox-arrow-down.svg
var InboxArrowDown ora.SVG

//go:embed inbox-stack.svg
var InboxStack ora.SVG

//go:embed inbox.svg
var Inbox ora.SVG

//go:embed information-circle.svg
var InformationCircle ora.SVG

//go:embed italic.svg
var Italic ora.SVG

//go:embed key.svg
var Key ora.SVG

//go:embed language.svg
var Language ora.SVG

//go:embed lifebuoy.svg
var Lifebuoy ora.SVG

//go:embed light-bulb.svg
var LightBulb ora.SVG

//go:embed link-slash.svg
var LinkSlash ora.SVG

//go:embed link.svg
var Link ora.SVG

//go:embed list-bullet.svg
var ListBullet ora.SVG

//go:embed lock-closed.svg
var LockClosed ora.SVG

//go:embed lock-open.svg
var LockOpen ora.SVG

//go:embed magnifying-glass-circle.svg
var MagnifyingGlassCircle ora.SVG

//go:embed magnifying-glass-minus.svg
var MagnifyingGlassMinus ora.SVG

//go:embed magnifying-glass-plus.svg
var MagnifyingGlassPlus ora.SVG

//go:embed magnifying-glass.svg
var MagnifyingGlass ora.SVG

//go:embed map-pin.svg
var MapPin ora.SVG

//go:embed map.svg
var Map ora.SVG

//go:embed megaphone.svg
var Megaphone ora.SVG

//go:embed microphone.svg
var Microphone ora.SVG

//go:embed minus-circle.svg
var MinusCircle ora.SVG

//go:embed minus-small.svg
var MinusSmall ora.SVG

//go:embed minus.svg
var Minus ora.SVG

//go:embed moon.svg
var Moon ora.SVG

//go:embed musical-note.svg
var MusicalNote ora.SVG

//go:embed newspaper.svg
var Newspaper ora.SVG

//go:embed no-symbol.svg
var NoSymbol ora.SVG

//go:embed numbered-list.svg
var NumberedList ora.SVG

//go:embed paint-brush.svg
var PaintBrush ora.SVG

//go:embed paper-airplane.svg
var PaperAirplane ora.SVG

//go:embed paper-clip.svg
var PaperClip ora.SVG

//go:embed pause-circle.svg
var PauseCircle ora.SVG

//go:embed pause.svg
var Pause ora.SVG

//go:embed pencil-square.svg
var PencilSquare ora.SVG

//go:embed pencil.svg
var Pencil ora.SVG

//go:embed percent-badge.svg
var PercentBadge ora.SVG

//go:embed phone-arrow-down-left.svg
var PhoneArrowDownLeft ora.SVG

//go:embed phone-arrow-up-right.svg
var PhoneArrowUpRight ora.SVG

//go:embed phone-x-mark.svg
var PhoneXMark ora.SVG

//go:embed phone.svg
var Phone ora.SVG

//go:embed photo.svg
var Photo ora.SVG

//go:embed play-circle.svg
var PlayCircle ora.SVG

//go:embed play-pause.svg
var PlayPause ora.SVG

//go:embed play.svg
var Play ora.SVG

//go:embed plus-circle.svg
var PlusCircle ora.SVG

//go:embed plus-small.svg
var PlusSmall ora.SVG

//go:embed plus.svg
var Plus ora.SVG

//go:embed power.svg
var Power ora.SVG

//go:embed presentation-chart-bar.svg
var PresentationChartBar ora.SVG

//go:embed presentation-chart-line.svg
var PresentationChartLine ora.SVG

//go:embed printer.svg
var Printer ora.SVG

//go:embed puzzle-piece.svg
var PuzzlePiece ora.SVG

//go:embed qr-code.svg
var QrCode ora.SVG

//go:embed question-mark-circle.svg
var QuestionMarkCircle ora.SVG

//go:embed queue-list.svg
var QueueList ora.SVG

//go:embed radio.svg
var Radio ora.SVG

//go:embed receipt-percent.svg
var ReceiptPercent ora.SVG

//go:embed receipt-refund.svg
var ReceiptRefund ora.SVG

//go:embed rectangle-group.svg
var RectangleGroup ora.SVG

//go:embed rectangle-stack.svg
var RectangleStack ora.SVG

//go:embed rocket-launch.svg
var RocketLaunch ora.SVG

//go:embed rss.svg
var Rss ora.SVG

//go:embed scale.svg
var Scale ora.SVG

//go:embed scissors.svg
var Scissors ora.SVG

//go:embed server-stack.svg
var ServerStack ora.SVG

//go:embed server.svg
var Server ora.SVG

//go:embed share.svg
var Share ora.SVG

//go:embed shield-check.svg
var ShieldCheck ora.SVG

//go:embed shield-exclamation.svg
var ShieldExclamation ora.SVG

//go:embed shopping-bag.svg
var ShoppingBag ora.SVG

//go:embed shopping-cart.svg
var ShoppingCart ora.SVG

//go:embed signal-slash.svg
var SignalSlash ora.SVG

//go:embed signal.svg
var Signal ora.SVG

//go:embed slash.svg
var Slash ora.SVG

//go:embed sparkles.svg
var Sparkles ora.SVG

//go:embed speaker-wave.svg
var SpeakerWave ora.SVG

//go:embed speaker-x-mark.svg
var SpeakerXMark ora.SVG

//go:embed square-2-stack.svg
var Square2Stack ora.SVG

//go:embed square-3-stack-3d.svg
var Square3Stack3d ora.SVG

//go:embed squares-2x2.svg
var Squares2x2 ora.SVG

//go:embed squares-plus.svg
var SquaresPlus ora.SVG

//go:embed star.svg
var Star ora.SVG

//go:embed stop-circle.svg
var StopCircle ora.SVG

//go:embed stop.svg
var Stop ora.SVG

//go:embed strikethrough.svg
var Strikethrough ora.SVG

//go:embed sun.svg
var Sun ora.SVG

//go:embed swatch.svg
var Swatch ora.SVG

//go:embed table-cells.svg
var TableCells ora.SVG

//go:embed tag.svg
var Tag ora.SVG

//go:embed ticket.svg
var Ticket ora.SVG

//go:embed trash.svg
var Trash ora.SVG

//go:embed trophy.svg
var Trophy ora.SVG

//go:embed truck.svg
var Truck ora.SVG

//go:embed tv.svg
var Tv ora.SVG

//go:embed underline.svg
var Underline ora.SVG

//go:embed user-circle.svg
var UserCircle ora.SVG

//go:embed user-group.svg
var UserGroup ora.SVG

//go:embed user-minus.svg
var UserMinus ora.SVG

//go:embed user-plus.svg
var UserPlus ora.SVG

//go:embed user.svg
var User ora.SVG

//go:embed users.svg
var Users ora.SVG

//go:embed variable.svg
var Variable ora.SVG

//go:embed video-camera-slash.svg
var VideoCameraSlash ora.SVG

//go:embed video-camera.svg
var VideoCamera ora.SVG

//go:embed view-columns.svg
var ViewColumns ora.SVG

//go:embed viewfinder-circle.svg
var ViewfinderCircle ora.SVG

//go:embed wallet.svg
var Wallet ora.SVG

//go:embed wifi.svg
var Wifi ora.SVG

//go:embed window.svg
var Window ora.SVG

//go:embed wrench-screwdriver.svg
var WrenchScrewdriver ora.SVG

//go:embed wrench.svg
var Wrench ora.SVG

//go:embed x-circle.svg
var XCircle ora.SVG

//go:embed x-mark.svg
var XMark ora.SVG

var All = map[string]ora.SVG{
	"AcademicCap":                 AcademicCap,
	"AdjustmentsHorizontal":       AdjustmentsHorizontal,
	"AdjustmentsVertical":         AdjustmentsVertical,
	"ArchiveBoxArrowDown":         ArchiveBoxArrowDown,
	"ArchiveBoxXMark":             ArchiveBoxXMark,
	"ArchiveBox":                  ArchiveBox,
	"ArrowDownCircle":             ArrowDownCircle,
	"ArrowDownLeft":               ArrowDownLeft,
	"ArrowDownOnSquareStack":      ArrowDownOnSquareStack,
	"ArrowDownOnSquare":           ArrowDownOnSquare,
	"ArrowDownRight":              ArrowDownRight,
	"ArrowDownTray":               ArrowDownTray,
	"ArrowDown":                   ArrowDown,
	"ArrowLeftCircle":             ArrowLeftCircle,
	"ArrowLeftEndOnRectangle":     ArrowLeftEndOnRectangle,
	"ArrowLeftOnRectangle":        ArrowLeftOnRectangle,
	"ArrowLeftStartOnRectangle":   ArrowLeftStartOnRectangle,
	"ArrowLeft":                   ArrowLeft,
	"ArrowLongDown":               ArrowLongDown,
	"ArrowLongLeft":               ArrowLongLeft,
	"ArrowLongRight":              ArrowLongRight,
	"ArrowLongUp":                 ArrowLongUp,
	"ArrowPathRoundedSquare":      ArrowPathRoundedSquare,
	"ArrowPath":                   ArrowPath,
	"ArrowRightCircle":            ArrowRightCircle,
	"ArrowRightEndOnRectangle":    ArrowRightEndOnRectangle,
	"ArrowRightOnRectangle":       ArrowRightOnRectangle,
	"ArrowRightStartOnRectangle":  ArrowRightStartOnRectangle,
	"ArrowRight":                  ArrowRight,
	"ArrowSmallDown":              ArrowSmallDown,
	"ArrowSmallLeft":              ArrowSmallLeft,
	"ArrowSmallRight":             ArrowSmallRight,
	"ArrowSmallUp":                ArrowSmallUp,
	"ArrowTopRightOnSquare":       ArrowTopRightOnSquare,
	"ArrowTrendingDown":           ArrowTrendingDown,
	"ArrowTrendingUp":             ArrowTrendingUp,
	"ArrowTurnDownLeft":           ArrowTurnDownLeft,
	"ArrowTurnDownRight":          ArrowTurnDownRight,
	"ArrowTurnLeftDown":           ArrowTurnLeftDown,
	"ArrowTurnLeftUp":             ArrowTurnLeftUp,
	"ArrowTurnRightDown":          ArrowTurnRightDown,
	"ArrowTurnRightUp":            ArrowTurnRightUp,
	"ArrowTurnUpLeft":             ArrowTurnUpLeft,
	"ArrowTurnUpRight":            ArrowTurnUpRight,
	"ArrowUpCircle":               ArrowUpCircle,
	"ArrowUpLeft":                 ArrowUpLeft,
	"ArrowUpOnSquareStack":        ArrowUpOnSquareStack,
	"ArrowUpOnSquare":             ArrowUpOnSquare,
	"ArrowUpRight":                ArrowUpRight,
	"ArrowUpTray":                 ArrowUpTray,
	"ArrowUp":                     ArrowUp,
	"ArrowUturnDown":              ArrowUturnDown,
	"ArrowUturnLeft":              ArrowUturnLeft,
	"ArrowUturnRight":             ArrowUturnRight,
	"ArrowUturnUp":                ArrowUturnUp,
	"ArrowsPointingIn":            ArrowsPointingIn,
	"ArrowsPointingOut":           ArrowsPointingOut,
	"ArrowsRightLeft":             ArrowsRightLeft,
	"ArrowsUpDown":                ArrowsUpDown,
	"AtSymbol":                    AtSymbol,
	"Backspace":                   Backspace,
	"Backward":                    Backward,
	"Banknotes":                   Banknotes,
	"Bars2":                       Bars2,
	"Bars3BottomLeft":             Bars3BottomLeft,
	"Bars3BottomRight":            Bars3BottomRight,
	"Bars3CenterLeft":             Bars3CenterLeft,
	"Bars3":                       Bars3,
	"Bars4":                       Bars4,
	"BarsArrowDown":               BarsArrowDown,
	"BarsArrowUp":                 BarsArrowUp,
	"Battery0":                    Battery0,
	"Battery100":                  Battery100,
	"Battery50":                   Battery50,
	"Beaker":                      Beaker,
	"BellAlert":                   BellAlert,
	"BellSlash":                   BellSlash,
	"BellSnooze":                  BellSnooze,
	"Bell":                        Bell,
	"Bold":                        Bold,
	"BoltSlash":                   BoltSlash,
	"Bolt":                        Bolt,
	"BookOpen":                    BookOpen,
	"BookmarkSlash":               BookmarkSlash,
	"BookmarkSquare":              BookmarkSquare,
	"Bookmark":                    Bookmark,
	"Briefcase":                   Briefcase,
	"BugAnt":                      BugAnt,
	"BuildingLibrary":             BuildingLibrary,
	"BuildingOffice2":             BuildingOffice2,
	"BuildingOffice":              BuildingOffice,
	"BuildingStorefront":          BuildingStorefront,
	"Cake":                        Cake,
	"Calculator":                  Calculator,
	"CalendarDateRange":           CalendarDateRange,
	"CalendarDays":                CalendarDays,
	"Calendar":                    Calendar,
	"Camera":                      Camera,
	"ChartBarSquare":              ChartBarSquare,
	"ChartBar":                    ChartBar,
	"ChartPie":                    ChartPie,
	"ChatBubbleBottomCenterText":  ChatBubbleBottomCenterText,
	"ChatBubbleBottomCenter":      ChatBubbleBottomCenter,
	"ChatBubbleLeftEllipsis":      ChatBubbleLeftEllipsis,
	"ChatBubbleLeftRight":         ChatBubbleLeftRight,
	"ChatBubbleLeft":              ChatBubbleLeft,
	"ChatBubbleOvalLeftEllipsis":  ChatBubbleOvalLeftEllipsis,
	"ChatBubbleOvalLeft":          ChatBubbleOvalLeft,
	"CheckBadge":                  CheckBadge,
	"CheckCircle":                 CheckCircle,
	"Check":                       Check,
	"ChevronDoubleDown":           ChevronDoubleDown,
	"ChevronDoubleLeft":           ChevronDoubleLeft,
	"ChevronDoubleRight":          ChevronDoubleRight,
	"ChevronDoubleUp":             ChevronDoubleUp,
	"ChevronDown":                 ChevronDown,
	"ChevronLeft":                 ChevronLeft,
	"ChevronRight":                ChevronRight,
	"ChevronUpDown":               ChevronUpDown,
	"ChevronUp":                   ChevronUp,
	"CircleStack":                 CircleStack,
	"ClipboardDocumentCheck":      ClipboardDocumentCheck,
	"ClipboardDocumentList":       ClipboardDocumentList,
	"ClipboardDocument":           ClipboardDocument,
	"Clipboard":                   Clipboard,
	"Clock":                       Clock,
	"CloudArrowDown":              CloudArrowDown,
	"CloudArrowUp":                CloudArrowUp,
	"Cloud":                       Cloud,
	"CodeBracketSquare":           CodeBracketSquare,
	"CodeBracket":                 CodeBracket,
	"Cog6Tooth":                   Cog6Tooth,
	"Cog8Tooth":                   Cog8Tooth,
	"Cog":                         Cog,
	"CommandLine":                 CommandLine,
	"ComputerDesktop":             ComputerDesktop,
	"CpuChip":                     CpuChip,
	"CreditCard":                  CreditCard,
	"CubeTransparent":             CubeTransparent,
	"Cube":                        Cube,
	"CurrencyBangladeshi":         CurrencyBangladeshi,
	"CurrencyDollar":              CurrencyDollar,
	"CurrencyEuro":                CurrencyEuro,
	"CurrencyPound":               CurrencyPound,
	"CurrencyRupee":               CurrencyRupee,
	"CurrencyYen":                 CurrencyYen,
	"CursorArrowRays":             CursorArrowRays,
	"CursorArrowRipple":           CursorArrowRipple,
	"DevicePhoneMobile":           DevicePhoneMobile,
	"DeviceTablet":                DeviceTablet,
	"Divide":                      Divide,
	"DocumentArrowDown":           DocumentArrowDown,
	"DocumentArrowUp":             DocumentArrowUp,
	"DocumentChartBar":            DocumentChartBar,
	"DocumentCheck":               DocumentCheck,
	"DocumentCurrencyBangladeshi": DocumentCurrencyBangladeshi,
	"DocumentCurrencyDollar":      DocumentCurrencyDollar,
	"DocumentCurrencyEuro":        DocumentCurrencyEuro,
	"DocumentCurrencyPound":       DocumentCurrencyPound,
	"DocumentCurrencyRupee":       DocumentCurrencyRupee,
	"DocumentCurrencyYen":         DocumentCurrencyYen,
	"DocumentDuplicate":           DocumentDuplicate,
	"DocumentMagnifyingGlass":     DocumentMagnifyingGlass,
	"DocumentMinus":               DocumentMinus,
	"DocumentPlus":                DocumentPlus,
	"DocumentText":                DocumentText,
	"Document":                    Document,
	"EllipsisHorizontalCircle":    EllipsisHorizontalCircle,
	"EllipsisHorizontal":          EllipsisHorizontal,
	"EllipsisVertical":            EllipsisVertical,
	"EnvelopeOpen":                EnvelopeOpen,
	"Envelope":                    Envelope,
	"Equals":                      Equals,
	"ExclamationCircle":           ExclamationCircle,
	"ExclamationTriangle":         ExclamationTriangle,
	"EyeDropper":                  EyeDropper,
	"EyeSlash":                    EyeSlash,
	"Eye":                         Eye,
	"FaceFrown":                   FaceFrown,
	"FaceSmile":                   FaceSmile,
	"Film":                        Film,
	"FingerPrint":                 FingerPrint,
	"Fire":                        Fire,
	"Flag":                        Flag,
	"FolderArrowDown":             FolderArrowDown,
	"FolderMinus":                 FolderMinus,
	"FolderOpen":                  FolderOpen,
	"FolderPlus":                  FolderPlus,
	"Folder":                      Folder,
	"Forward":                     Forward,
	"Funnel":                      Funnel,
	"Gif":                         Gif,
	"GiftTop":                     GiftTop,
	"Gift":                        Gift,
	"GlobeAlt":                    GlobeAlt,
	"GlobeAmericas":               GlobeAmericas,
	"GlobeAsiaAustralia":          GlobeAsiaAustralia,
	"GlobeEuropeAfrica":           GlobeEuropeAfrica,
	"H1":                          H1,
	"H2":                          H2,
	"H3":                          H3,
	"HandRaised":                  HandRaised,
	"HandThumbDown":               HandThumbDown,
	"HandThumbUp":                 HandThumbUp,
	"Hashtag":                     Hashtag,
	"Heart":                       Heart,
	"HomeModern":                  HomeModern,
	"Home":                        Home,
	"Identification":              Identification,
	"InboxArrowDown":              InboxArrowDown,
	"InboxStack":                  InboxStack,
	"Inbox":                       Inbox,
	"InformationCircle":           InformationCircle,
	"Italic":                      Italic,
	"Key":                         Key,
	"Language":                    Language,
	"Lifebuoy":                    Lifebuoy,
	"LightBulb":                   LightBulb,
	"LinkSlash":                   LinkSlash,
	"Link":                        Link,
	"ListBullet":                  ListBullet,
	"LockClosed":                  LockClosed,
	"LockOpen":                    LockOpen,
	"MagnifyingGlassCircle":       MagnifyingGlassCircle,
	"MagnifyingGlassMinus":        MagnifyingGlassMinus,
	"MagnifyingGlassPlus":         MagnifyingGlassPlus,
	"MagnifyingGlass":             MagnifyingGlass,
	"MapPin":                      MapPin,
	"Map":                         Map,
	"Megaphone":                   Megaphone,
	"Microphone":                  Microphone,
	"MinusCircle":                 MinusCircle,
	"MinusSmall":                  MinusSmall,
	"Minus":                       Minus,
	"Moon":                        Moon,
	"MusicalNote":                 MusicalNote,
	"Newspaper":                   Newspaper,
	"NoSymbol":                    NoSymbol,
	"NumberedList":                NumberedList,
	"PaintBrush":                  PaintBrush,
	"PaperAirplane":               PaperAirplane,
	"PaperClip":                   PaperClip,
	"PauseCircle":                 PauseCircle,
	"Pause":                       Pause,
	"PencilSquare":                PencilSquare,
	"Pencil":                      Pencil,
	"PercentBadge":                PercentBadge,
	"PhoneArrowDownLeft":          PhoneArrowDownLeft,
	"PhoneArrowUpRight":           PhoneArrowUpRight,
	"PhoneXMark":                  PhoneXMark,
	"Phone":                       Phone,
	"Photo":                       Photo,
	"PlayCircle":                  PlayCircle,
	"PlayPause":                   PlayPause,
	"Play":                        Play,
	"PlusCircle":                  PlusCircle,
	"PlusSmall":                   PlusSmall,
	"Plus":                        Plus,
	"Power":                       Power,
	"PresentationChartBar":        PresentationChartBar,
	"PresentationChartLine":       PresentationChartLine,
	"Printer":                     Printer,
	"PuzzlePiece":                 PuzzlePiece,
	"QrCode":                      QrCode,
	"QuestionMarkCircle":          QuestionMarkCircle,
	"QueueList":                   QueueList,
	"Radio":                       Radio,
	"ReceiptPercent":              ReceiptPercent,
	"ReceiptRefund":               ReceiptRefund,
	"RectangleGroup":              RectangleGroup,
	"RectangleStack":              RectangleStack,
	"RocketLaunch":                RocketLaunch,
	"Rss":                         Rss,
	"Scale":                       Scale,
	"Scissors":                    Scissors,
	"ServerStack":                 ServerStack,
	"Server":                      Server,
	"Share":                       Share,
	"ShieldCheck":                 ShieldCheck,
	"ShieldExclamation":           ShieldExclamation,
	"ShoppingBag":                 ShoppingBag,
	"ShoppingCart":                ShoppingCart,
	"SignalSlash":                 SignalSlash,
	"Signal":                      Signal,
	"Slash":                       Slash,
	"Sparkles":                    Sparkles,
	"SpeakerWave":                 SpeakerWave,
	"SpeakerXMark":                SpeakerXMark,
	"Square2Stack":                Square2Stack,
	"Square3Stack3d":              Square3Stack3d,
	"Squares2x2":                  Squares2x2,
	"SquaresPlus":                 SquaresPlus,
	"Star":                        Star,
	"StopCircle":                  StopCircle,
	"Stop":                        Stop,
	"Strikethrough":               Strikethrough,
	"Sun":                         Sun,
	"Swatch":                      Swatch,
	"TableCells":                  TableCells,
	"Tag":                         Tag,
	"Ticket":                      Ticket,
	"Trash":                       Trash,
	"Trophy":                      Trophy,
	"Truck":                       Truck,
	"Tv":                          Tv,
	"Underline":                   Underline,
	"UserCircle":                  UserCircle,
	"UserGroup":                   UserGroup,
	"UserMinus":                   UserMinus,
	"UserPlus":                    UserPlus,
	"User":                        User,
	"Users":                       Users,
	"Variable":                    Variable,
	"VideoCameraSlash":            VideoCameraSlash,
	"VideoCamera":                 VideoCamera,
	"ViewColumns":                 ViewColumns,
	"ViewfinderCircle":            ViewfinderCircle,
	"Wallet":                      Wallet,
	"Wifi":                        Wifi,
	"Window":                      Window,
	"WrenchScrewdriver":           WrenchScrewdriver,
	"Wrench":                      Wrench,
	"XCircle":                     XCircle,
	"XMark":                       XMark,
}
