baseURL = "/"
locale = "en"
title = "Nago Docs"
defaultContentLanguage = "en"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[menu]
 [[menu.main]]
   name = "Documentation"
   pageRef = "/docs/getting-started"
   weight = 1

 [[menu.main]]
   name = "Showcase"
   pageRef = "/showcase"
   weight = 2

 [[menu.main]]
   name = "Search"
   weight = 3
   [menu.main.params]
     type = "search"

 [[menu.main]]
   name = "GitHub"
   url = "https://github.com/worldiety/nago"
   weight = 4
   [menu.main.params]
     icon = "github"

 [[menu.sidebar]]
   name = "More"
   weight = 1
   [menu.sidebar.params]
     type = "separator"

 [[menu.sidebar]]
   name = "worldiety GmbH ↗"
   url = "https://www.worldiety.de"
   weight = 2

[params]
  description = "Documentation for Nago"
  navbarTitle = "Nago Docs"
  favicon = "favicon.svg"

  [params.navbar]
    [params.navbar.logo]
      path = "images/nago_logo.svg"
      dark = "images/nago_logo_white.svg"
      width = "40"

  [params.theme]
    default = "system"

  [params.footer]
    displayCopyright = true
    displayPoweredBy = false
    height = "auto"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
