/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */



/**
 * Alignment is specified as follows:
 * 
 * ┌─TopLeading───────────Top─────────TopTrailing─┐
 * │                                              │
 * │                                              │
 * │                                              │
 * │                                              │
 * │                                              │
 * │                                              │
 * │                                              │
 * │ Leading            Center            Trailing│
 * │                                              │
 * │                                              │
 * │                                              │
 * │                                              │
 * │                                              │
 * │                                              │
 * │                                              │
 * └BottomLeading───────Bottom──────BottomTrailing┘
 * 
 * An empty Alignment must be interpreted as Center (="c").
 */
export type Alignment = string 
