/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Length } from '@/shared/protocol/ora/length';
import type { NamedColor } from '@/shared/protocol/ora/namedColor';
import type { Shadow } from '@/shared/protocol/ora/shadow';

export interface Border {
    // TopLeftRadius
    tlr/*omitempty*/? /*TopLeftRadius*/: Length;
    // TopRightRadius
    trr/*omitempty*/? /*TopRightRadius*/: Length;
    // BottomLeftRadius
    blr/*omitempty*/? /*BottomLeftRadius*/: Length;
    // BottomRightRadius
    brr/*omitempty*/? /*BottomRightRadius*/: Length;
    // LeftWidth
    lw/*omitempty*/? /*LeftWidth*/: Length;
    // TopWidth
    tw/*omitempty*/? /*TopWidth*/: Length;
    // RightWidth
    rw/*omitempty*/? /*RightWidth*/: Length;
    // BottomWidth
    bw/*omitempty*/? /*BottomWidth*/: Length;
    // LeftColor
    lc/*omitempty*/? /*LeftColor*/: NamedColor;
    // TopColor
    tc/*omitempty*/? /*TopColor*/: NamedColor;
    // RightColor
    rc/*omitempty*/? /*RightColor*/: NamedColor;
    // BottomColor
    bc/*omitempty*/? /*BottomColor*/: NamedColor;
    // BoxShadow
    s/*omitempty*/? /*BoxShadow*/: Shadow;
}

