/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { AlignedComponent } from '@/shared/protocol/ora/alignedComponent';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Frame } from '@/shared/protocol/ora/frame';
import type { NamedColor } from '@/shared/protocol/ora/namedColor';
import type { Padding } from '@/shared/protocol/ora/padding';

/**
 * A Box aligns children elements in absolute within its bounds.
 * - there is no intrinsic component dimension, so you have to set it by hand
 * - z-order is defined as defined children order, thus later children are put on top of others
 * - it is undefined behavior, to define multiple children with the same alignment. So this must not be rendered.
 */
export interface Box {
    type: 'bx'/*ComponentType*/;
    c/*omitempty*/? /*Children*/: AlignedComponent[];

    /**
     * Frame is omitted if empty
     */
    frame/*omitempty*/? /*Frame*/: Frame;

    /**
     * BackgroundColor regular is always transparent
     */
    bgc/*omitempty*/? /*BackgroundColor*/: NamedColor;
    p/*omitempty*/? /*Padding*/: Padding;
}

