/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { BreadcrumbItem } from '@/shared/protocol/ora/breadcrumbItem';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { SVG } from '@/shared/protocol/ora/sVG';

export interface Breadcrumbs {
    id /*Ptr*/: Ptr;
    type: 'Breadcrumbs'/*ComponentType*/;
    items: Property<BreadcrumbItem[]>;
    selectedItemIndex: Property<number /*int64*/>;
    icon: Property<SVG>;
}

