/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { BreadcrumbItem } from '@/shared/protocol/ora/breadcrumbItem';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface Breadcrumbs {
    // Ptr
    id /*Ptr*/: Ptr;
    // Type
    type: 'Breadcrumbs'/*ComponentType*/;
    // Items
    items: Property<BreadcrumbItem[]>;
    // SelectedItemIndex
    selectedItemIndex: Property<number /*int64*/>;
    // Icon
    icon: Property<number /*uint8*/[]>;
}

