/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface BreadcrumbItem {
	// Ptr
	id /*Ptr*/ : Ptr;
	// Type
	type: 'BreadcrumbItem' /*ComponentType*/;
	// Label
	label: Property<string>;
	// Action
	action: Property<Ptr>;
}
