/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Intent } from '@/shared/protocol/ora/intent';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { SVG } from '@/shared/protocol/ora/sVG';

/**
 * Button represents an user interface element which spans a visible area to click or tap from the user.
 */
export interface Button {
    id /*Ptr*/: Ptr;
    type: 'Button'/*ComponentType*/;
    caption: Property<string>;
    preIcon: Property<SVG>;
    postIcon: Property<SVG>;
    color: Property<Intent>;
    disabled: Property<boolean>;
    action: Property<Ptr>;
    visible: Property<boolean>;
}

