// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { SVG } from '@/shared/protocol/ora/sVG';
import type { Intent } from '@/shared/protocol/ora/intent';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';

// Button represents an user interface element which spans a visible area to click or tap from the user.
export class Button {
    private _id : Ptr;
    private _type : ComponentType;
    private _caption : Property<string>;
    private _preIcon : Property<SVG>;
    private _postIcon : Property<SVG>;
    private _color : Property<Intent>;
    private _disabled : Property<boolean>;
    private _action : Property<Ptr>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get caption(): Property<string>{
        return this._caption;
    }
    set caption(value: Property<string>){
        this._caption = value;
    }
    get preIcon(): Property<SVG>{
        return this._preIcon;
    }
    set preIcon(value: Property<SVG>){
        this._preIcon = value;
    }
    get postIcon(): Property<SVG>{
        return this._postIcon;
    }
    set postIcon(value: Property<SVG>){
        this._postIcon = value;
    }
    get color(): Property<Intent>{
        return this._color;
    }
    set color(value: Property<Intent>){
        this._color = value;
    }
    get disabled(): Property<boolean>{
        return this._disabled;
    }
    set disabled(value: Property<boolean>){
        this._disabled = value;
    }
    get action(): Property<Ptr>{
        return this._action;
    }
    set action(value: Property<Ptr>){
        this._action = value;
    }
}

