/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Component } from '@/shared/protocol/ora/component';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface Card {
    id /*Ptr*/: Ptr;
    type: 'Card'/*ComponentType*/;
    children: Property<Component[]>;
    action: Property<Ptr>;
    visible: Property<boolean>;
}

