/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Component } from '@/shared/protocol/ora/component';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface Card {
    // Ptr
    id /*Ptr*/: Ptr;
    // Type
    type: 'Card'/*ComponentType*/;
    // Children
    children: Property<Component[]>;
    // Action
    action: Property<Ptr>;
    // Visible
    visible: Property<boolean>;
}

