/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface Chip {
    // Ptr
    id /*Ptr*/: Ptr;
    // Type
    type: 'Chip'/*ComponentType*/;
    // Caption
    caption: Property<string>;
    // Action
    action: Property<Ptr>;
    // OnClose
    onClose: Property<Ptr>;
    // Color
    color: Property<string>;
    // Visible
    visible: Property<boolean>;
}

