/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface Chip {
    id /*Ptr*/: Ptr;
    type: 'Chip'/*ComponentType*/;
    caption: Property<string>;
    action: Property<Ptr>;
    onClose: Property<Ptr>;
    color: Property<string>;
    visible: Property<boolean>;
}

