// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';

export class Chip {
    private _id : Ptr;
    private _type : ComponentType;
    private _caption : Property<string>;
    private _action : Property<Ptr>;
    private _onClose : Property<Ptr>;
    private _color : Property<string>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get caption(): Property<string>{
        return this._caption;
    }
    set caption(value: Property<string>){
        this._caption = value;
    }
    get action(): Property<Ptr>{
        return this._action;
    }
    set action(value: Property<Ptr>){
        this._action = value;
    }
    get onClose(): Property<Ptr>{
        return this._onClose;
    }
    set onClose(value: Property<Ptr>){
        this._onClose = value;
    }
    get color(): Property<string>{
        return this._color;
    }
    set color(value: Property<string>){
        this._color = value;
    }
}

