// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { Color } from '@/shared/protocol/ora/color';

export class Colors {
    private _black : Color;
    private _white : Color;
    private _primary : Color;
    private _interactive : Color;
    private _alertNegative : Color;
    private _alertPositive : Color;
    get black(): Color{
        return this._black;
    }
    set black(value: Color){
        this._black = value;
    }
    get white(): Color{
        return this._white;
    }
    set white(value: Color){
        this._white = value;
    }
    get primary(): Color{
        return this._primary;
    }
    set primary(value: Color){
        this._primary = value;
    }
    get interactive(): Color{
        return this._interactive;
    }
    set interactive(value: Color){
        this._interactive = value;
    }
    get alertNegative(): Color{
        return this._alertNegative;
    }
    set alertNegative(value: Color){
        this._alertNegative = value;
    }
    get alertPositive(): Color{
        return this._alertPositive;
    }
    set alertPositive(value: Color){
        this._alertPositive = value;
    }
}

