/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Border } from '@/shared/protocol/ora/border';
import type { NamedColor } from '@/shared/protocol/ora/namedColor';

func color(c NamedColor,)(Border,){
}
