/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */



export interface Color {
    r: number /*uint8*/;
    g: number /*uint8*/;
    b: number /*uint8*/;
    a: number /*uint8*/;
}

