/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { Color } from '@/shared/protocol/ora/color';
import type { HSLColor } from '@/shared/protocol/ora/hSLColor';

export interface Colors {
	// Primary
	primary: HSLColor;
	// PrimaryTen
	primary10 /*PrimaryTen*/ : HSLColor;
	// PrimaryTwelve
	primary12 /*PrimaryTwelve*/ : HSLColor;
	// PrimaryFourteen
	primary14 /*PrimaryFourteen*/ : HSLColor;
	// PrimarySeventeen
	primary17 /*PrimarySeventeen*/ : HSLColor;
	// PrimaryTwentyTwo
	primary22 /*PrimaryTwentyTwo*/ : HSLColor;
	// PrimaryThirty
	primary30 /*PrimaryThirty*/ : HSLColor;
	// PrimarySixty
	primary60 /*PrimarySixty*/ : HSLColor;
	// PrimarySeventy
	primary70 /*PrimarySeventy*/ : HSLColor;
	// PrimaryEightyThree
	primary83 /*PrimaryEightyThree*/ : HSLColor;
	// PrimaryEightySeven
	primary87 /*PrimaryEightySeven*/ : HSLColor;
	// PrimaryNinety
	primary90 /*PrimaryNinety*/ : HSLColor;
	// PrimaryNinetyTwo
	primary92 /*PrimaryNinetyTwo*/ : HSLColor;
	// PrimaryNinetyFour
	primary94 /*PrimaryNinetyFour*/ : HSLColor;
	// PrimaryNinetySix
	primary96 /*PrimaryNinetySix*/ : HSLColor;
	// PrimaryNinetyEight
	primary98 /*PrimaryNinetyEight*/ : HSLColor;
	// Secondary
	secondary: HSLColor;
	// Tertiary
	tertiary: HSLColor;
	// CustomColors
	customColors: Record<string, Color>;
}
