/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Box } from '@/shared/protocol/ora/box';
import type { BreadcrumbItem } from '@/shared/protocol/ora/breadcrumbItem';
import type { Breadcrumbs } from '@/shared/protocol/ora/breadcrumbs';
import type { Button } from '@/shared/protocol/ora/button';
import type { Card } from '@/shared/protocol/ora/card';
import type { Chip } from '@/shared/protocol/ora/chip';
import type { DatePicker } from '@/shared/protocol/ora/datePicker';
import type { Dialog } from '@/shared/protocol/ora/dialog';
import type { Divider } from '@/shared/protocol/ora/divider';
import type { Dropdown } from '@/shared/protocol/ora/dropdown';
import type { DropdownItem } from '@/shared/protocol/ora/dropdownItem';
import type { FileField } from '@/shared/protocol/ora/fileField';
import type { FlexContainer } from '@/shared/protocol/ora/flexContainer';
import type { Grid } from '@/shared/protocol/ora/grid';
import type { GridCell } from '@/shared/protocol/ora/gridCell';
import type { HStack } from '@/shared/protocol/ora/hStack';
import type { Image } from '@/shared/protocol/ora/image';
import type { MenuEntry } from '@/shared/protocol/ora/menuEntry';
import type { NavigationComponent } from '@/shared/protocol/ora/navigationComponent';
import type { NumberField } from '@/shared/protocol/ora/numberField';
import type { Page } from '@/shared/protocol/ora/page';
import type { PasswordField } from '@/shared/protocol/ora/passwordField';
import type { Scaffold } from '@/shared/protocol/ora/scaffold';
import type { Slider } from '@/shared/protocol/ora/slider';
import type { Spacer } from '@/shared/protocol/ora/spacer';
import type { StepInfo } from '@/shared/protocol/ora/stepInfo';
import type { Stepper } from '@/shared/protocol/ora/stepper';
import type { Table } from '@/shared/protocol/ora/table';
import type { TableCell } from '@/shared/protocol/ora/tableCell';
import type { TableRow } from '@/shared/protocol/ora/tableRow';
import type { Text } from '@/shared/protocol/ora/text';
import type { TextArea } from '@/shared/protocol/ora/textArea';
import type { TextField } from '@/shared/protocol/ora/textField';
import type { Toggle } from '@/shared/protocol/ora/toggle';
import type { VStack } from '@/shared/protocol/ora/vStack';
import type { WebView } from '@/shared/protocol/ora/webView';

export type Component = 
| Spacer
| Box
| VStack
| HStack
| Button
| Page
| Scaffold
| NavigationComponent
| TextField
| PasswordField
| Table
| TableCell
| TableRow
| Text
| Dialog
| Toggle
| DatePicker
| NumberField
| Slider
| Divider
| Dropdown
| DropdownItem
| Chip
| Card
| Stepper
| StepInfo
| WebView
| TextArea
| FileField
| Image
| Breadcrumbs
| BreadcrumbItem
| MenuEntry
| Grid
| GridCell
| FlexContainer
