// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { EventType } from '@/shared/protocol/ora/eventType';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { RequestId } from '@/shared/protocol/ora/requestId';

export class ComponentDestructionRequested {
    private _type : EventType;
    private _r : RequestId;
    private _ptr : Ptr;
    get type(): EventType{
        return this._type;
    }
    set type(value: EventType){
        this._type = value;
    }
    get requestId(): RequestId{
        return this._r;
    }
    set requestId(value: RequestId){
        this._r = value;
    }
    get component(): Ptr{
        return this._ptr;
    }
    set component(value: Ptr){
        this._ptr = value;
    }
}

