/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { EventType } from '@/shared/protocol/ora/eventType';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { RequestId } from '@/shared/protocol/ora/requestId';

export interface ComponentInvalidationRequested {
    type: 'ComponentInvalidationRequested'/*EventType*/;
    r /*RequestId*/: RequestId;
    ptr /*Component*/: Ptr;
}

