// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { ColorScheme } from '@/shared/protocol/ora/colorScheme';
import type { EventType } from '@/shared/protocol/ora/eventType';
import type { RequestId } from '@/shared/protocol/ora/requestId';

// ConfigurationRequested is issued by the frontend to get the applications general configuration.
// A backend developer has potentially defined a lot of configuration details about the application.
// For example, there may be a color theme, customized icons, image resources, an application name and the available set of navigations, launch intents or other meta information.
// It is expected, that this only happens once during initialization of the frontend process.
export class ConfigurationRequested {
    private _type : EventType;
    private _acceptLanguage : string;
    private _colorScheme : ColorScheme;
    private _r : RequestId;
    get type(): EventType{
        return this._type;
    }
    set type(value: EventType){
        this._type = value;
    }
    get acceptLanguage(): string{
        return this._acceptLanguage;
    }
    set acceptLanguage(value: string){
        this._acceptLanguage = value;
    }
    get colorScheme(): ColorScheme{
        return this._colorScheme;
    }
    set colorScheme(value: ColorScheme){
        this._colorScheme = value;
    }
    get requestId(): RequestId{
        return this._r;
    }
    set requestId(value: RequestId){
        this._r = value;
    }
}

