/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Date } from '@/shared/protocol/ora/date';
import type { DatePickerStyle } from '@/shared/protocol/ora/datePickerStyle';
import type { Frame } from '@/shared/protocol/ora/frame';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface DatePicker {
	// Type
	type: 'P' /*ComponentType*/;
	// Disabled
	d /*omitempty*/? /*Disabled*/ : boolean;
	// Label
	l /*omitempty*/? /*Label*/ : string;
	// SupportingText
	s /*omitempty*/? /*SupportingText*/ : string;

	/**
	 * ErrorText is shown instead of SupportingText, even if they are (today) independent
	 */
	// ErrorText
	e /*omitempty*/? /*ErrorText*/ : string;

	/**
	 * Style determines if the picker shall use the range or single mode. Default is single selection
	 */
	// Style
	y /*omitempty*/? /*Style*/ : DatePickerStyle;

	/**
	 * Value is the initial single value or start value of the picker.
	 */
	// Value
	v /*Value*/ : Date;

	/**
	 * InputValue is the picked single value or end value of the picker.
	 */
	// InputValue
	p /*InputValue*/ : Ptr;

	/**
	 * EndValue is the initial end value of the picker.
	 */
	// EndValue
	ev /*EndValue*/ : Date;

	/**
	 * EndInputValue is the picked end value of the picker.
	 */
	// EndInputValue
	ep /*EndInputValue*/ : Ptr;
	// Invisible
	iv /*omitempty*/? /*Invisible*/ : boolean;
	// Frame
	f /*omitempty*/? /*Frame*/ : Frame;
}
