/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface DatePicker {
    id /*Ptr*/: Ptr;
    type: 'DatePicker'/*ComponentType*/;
    disabled: Property<boolean>;
    label: Property<string>;
    hint: Property<string>;
    error: Property<string>;
    expanded: Property<boolean>;
    rangeMode: Property<boolean>;
    startDateSelected: Property<boolean>;
    selectedStartDay: Property<number /*int64*/>;
    selectedStartMonth: Property<number /*int64*/>;
    selectedStartYear: Property<number /*int64*/>;
    endDateSelected: Property<boolean>;
    selectedEndDay: Property<number /*int64*/>;
    selectedEndMonth: Property<number /*int64*/>;
    selectedEndYear: Property<number /*int64*/>;
    onClicked: Property<Ptr>;
    onSelectionChanged: Property<Ptr>;
    visible: Property<boolean>;
}

