/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */



/**
 * Date represents a location-free representation of a day/month/year tuple.
 */
export interface Date {
    // Day
    d/*omitempty*/? /*Day*/: number /*int*/;
    // Month
    m/*omitempty*/? /*Month*/: number /*int*/;
    // Year
    y/*omitempty*/? /*Year*/: number /*int*/;
}

