// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';

export class DatePicker {
    private _id : Ptr;
    private _type : ComponentType;
    private _disabled : Property<boolean>;
    private _label : Property<string>;
    private _hint : Property<string>;
    private _error : Property<string>;
    private _expanded : Property<boolean>;
    private _rangeMode : Property<boolean>;
    private _startDateSelected : Property<boolean>;
    private _selectedStartDay : Property<number>;
    private _selectedStartMonth : Property<number>;
    private _selectedStartYear : Property<number>;
    private _endDateSelected : Property<boolean>;
    private _selectedEndDay : Property<number>;
    private _selectedEndMonth : Property<number>;
    private _selectedEndYear : Property<number>;
    private _onClicked : Property<Ptr>;
    private _onSelectionChanged : Property<Ptr>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get disabled(): Property<boolean>{
        return this._disabled;
    }
    set disabled(value: Property<boolean>){
        this._disabled = value;
    }
    get label(): Property<string>{
        return this._label;
    }
    set label(value: Property<string>){
        this._label = value;
    }
    get hint(): Property<string>{
        return this._hint;
    }
    set hint(value: Property<string>){
        this._hint = value;
    }
    get error(): Property<string>{
        return this._error;
    }
    set error(value: Property<string>){
        this._error = value;
    }
    get expanded(): Property<boolean>{
        return this._expanded;
    }
    set expanded(value: Property<boolean>){
        this._expanded = value;
    }
    get rangeMode(): Property<boolean>{
        return this._rangeMode;
    }
    set rangeMode(value: Property<boolean>){
        this._rangeMode = value;
    }
    get startDateSelected(): Property<boolean>{
        return this._startDateSelected;
    }
    set startDateSelected(value: Property<boolean>){
        this._startDateSelected = value;
    }
    get selectedStartDay(): Property<number>{
        return this._selectedStartDay;
    }
    set selectedStartDay(value: Property<number>){
        this._selectedStartDay = value;
    }
    get selectedStartMonth(): Property<number>{
        return this._selectedStartMonth;
    }
    set selectedStartMonth(value: Property<number>){
        this._selectedStartMonth = value;
    }
    get selectedStartYear(): Property<number>{
        return this._selectedStartYear;
    }
    set selectedStartYear(value: Property<number>){
        this._selectedStartYear = value;
    }
    get endDateSelected(): Property<boolean>{
        return this._endDateSelected;
    }
    set endDateSelected(value: Property<boolean>){
        this._endDateSelected = value;
    }
    get selectedEndDay(): Property<number>{
        return this._selectedEndDay;
    }
    set selectedEndDay(value: Property<number>){
        this._selectedEndDay = value;
    }
    get selectedEndMonth(): Property<number>{
        return this._selectedEndMonth;
    }
    set selectedEndMonth(value: Property<number>){
        this._selectedEndMonth = value;
    }
    get selectedEndYear(): Property<number>{
        return this._selectedEndYear;
    }
    set selectedEndYear(value: Property<number>){
        this._selectedEndYear = value;
    }
    get onClicked(): Property<Ptr>{
        return this._onClicked;
    }
    set onClicked(value: Property<Ptr>){
        this._onClicked = value;
    }
    get onSelectionChanged(): Property<Ptr>{
        return this._onSelectionChanged;
    }
    set onSelectionChanged(value: Property<Ptr>){
        this._onSelectionChanged = value;
    }
}

