/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Component } from '@/shared/protocol/ora/component';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { ElementSize } from '@/shared/protocol/ora/elementSize';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface Dialog {
    // Ptr
    id /*Ptr*/: Ptr;
    // Type
    type: 'Dialog'/*ComponentType*/;
    // Title
    title: Property<string>;
    // Body
    body: Property<Component>;
    // Footer
    footer: Property<Component>;
    // Icon
    icon: Property;
    // Size
    size: Property<ElementSize>;
}

