// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { Component } from '@/shared/protocol/ora/component';
import type { SVG } from '@/shared/protocol/ora/sVG';
import type { Button } from '@/shared/protocol/ora/button';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';

export class Dialog {
    private _id : Ptr;
    private _type : ComponentType;
    private _title : Property<string>;
    private _body : Property<Component>;
    private _icon : Property<SVG>;
    private _actions : Property<Button[]>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get title(): Property<string>{
        return this._title;
    }
    set title(value: Property<string>){
        this._title = value;
    }
    get body(): Property<Component>{
        return this._body;
    }
    set body(value: Property<Component>){
        this._body = value;
    }
    get icon(): Property<SVG>{
        return this._icon;
    }
    set icon(value: Property<SVG>){
        this._icon = value;
    }
    get actions(): Property<Button[]>{
        return this._actions;
    }
    set actions(value: Property<Button[]>){
        this._actions = value;
    }
}

