/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface Divider {
    // Ptr
    id /*Ptr*/: Ptr;
    // Type
    type: 'Divider'/*ComponentType*/;
}

