/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Border } from '@/shared/protocol/ora/border';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Frame } from '@/shared/protocol/ora/frame';
import type { Padding } from '@/shared/protocol/ora/padding';

export interface Divider {
    // Type
    type: 'd'/*ComponentType*/;
    // Frame
    f/*omitempty*/? /*Frame*/: Frame;
    // Border
    b/*omitempty*/? /*Border*/: Border;
    // Padding
    p/*omitempty*/? /*Padding*/: Padding;
}

