// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export class DropdownItem {
    private _id : Ptr;
    private _type : ComponentType;
    private _content : Property<string>;
    private _onClicked : Property<Ptr>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get content(): Property<string>{
        return this._content;
    }
    set content(value: Property<string>){
        this._content = value;
    }
    get onClicked(): Property<Ptr>{
        return this._onClicked;
    }
    set onClicked(value: Property<Ptr>){
        this._onClicked = value;
    }
}

