/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { DropdownItem } from '@/shared/protocol/ora/dropdownItem';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface Dropdown {
    id /*Ptr*/: Ptr;
    type: 'Dropdown'/*ComponentType*/;
    items: Property<DropdownItem[]>;
    selectedIndices: Property<number /*int64*/[]>;
    multiselect: Property<boolean>;
    expanded: Property<boolean>;
    disabled: Property<boolean>;
    label: Property<string>;
    hint: Property<string>;
    error: Property<string>;
    onClicked: Property<Ptr>;
    searchable: Property<boolean>;
    visible: Property<boolean>;
}

