// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { EventType } from '@/shared/protocol/ora/eventType';
import type { RequestId } from '@/shared/protocol/ora/requestId';

export class ErrorOccurred {
    private _type : EventType;
    private _r : RequestId;
    private _message : string;
    get type(): EventType{
        return this._type;
    }
    set type(value: EventType){
        this._type = value;
    }
    get requestId(): RequestId{
        return this._r;
    }
    set requestId(value: RequestId){
        this._r = value;
    }
    get message(): string{
        return this._message;
    }
    set message(value: string){
        this._message = value;
    }
}

