// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { ComponentType } from '@/shared/protocol/ora/componentType';

export class FileField {
    private _id : Ptr;
    private _type : ComponentType;
    private _label : Property<string>;
    private _hint : Property<string>;
    private _error : Property<string>;
    private _disabled : Property<boolean>;
    private _filter : Property<string>;
    private _multiple : Property<boolean>;
    private _uploadToken : Property<string>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get label(): Property<string>{
        return this._label;
    }
    set label(value: Property<string>){
        this._label = value;
    }
    get hint(): Property<string>{
        return this._hint;
    }
    set hint(value: Property<string>){
        this._hint = value;
    }
    get error(): Property<string>{
        return this._error;
    }
    set error(value: Property<string>){
        this._error = value;
    }
    get disabled(): Property<boolean>{
        return this._disabled;
    }
    set disabled(value: Property<boolean>){
        this._disabled = value;
    }
    get filter(): Property<string>{
        return this._filter;
    }
    set filter(value: Property<string>){
        this._filter = value;
    }
    get multiple(): Property<boolean>{
        return this._multiple;
    }
    set multiple(value: Property<boolean>){
        this._multiple = value;
    }
    get uploadToken(): Property<string>{
        return this._uploadToken;
    }
    set uploadToken(value: Property<string>){
        this._uploadToken = value;
    }
}

