/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface FileField {
	// Ptr
	id /*Ptr*/ : Ptr;
	// Type
	type: 'FileField' /*ComponentType*/;
	// Label
	label: Property<string>;
	// HintLeft
	hintLeft: Property<string>;
	// HintRight
	hintRight: Property<string>;
	// Error
	error: Property<string>;
	// Disabled
	disabled: Property<boolean>;
	// Filter
	filter: Property<string>;
	// Multiple
	multiple: Property<boolean>;
	// MaxBytes
	maxBytes: Property<number /*int64*/>;
	// Visible
	visible: Property<boolean>;
}
