/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface FileField {
    id /*Ptr*/: Ptr;
    type: 'FileField'/*ComponentType*/;
    label: Property<string>;
    hintLeft: Property<string>;
    hintRight: Property<string>;
    error: Property<string>;
    disabled: Property<boolean>;
    filter: Property<string>;
    multiple: Property<boolean>;
    maxBytes: Property<number /*int64*/>;
}

