/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Component } from '@/shared/protocol/ora/component';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { ContentAlignment } from '@/shared/protocol/ora/contentAlignment';
import type { ElementSize } from '@/shared/protocol/ora/elementSize';
import type { ItemsAlignment } from '@/shared/protocol/ora/itemsAlignment';
import type { Orientation } from '@/shared/protocol/ora/orientation';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface FlexContainer {
    // Ptr
    id /*Ptr*/: Ptr;
    // Type
    type: 'FlexContainer'/*ComponentType*/;
    // Elements
    elements: Property<Component[]>;
    // ElementSize
    elementSize: Property<ElementSize>;
    // Orientation
    orientation: Property<Orientation>;
    // ContentAlignment
    contentAlignment: Property<ContentAlignment>;
    // ItemsAlignment
    itemsAlignment: Property<ItemsAlignment>;
    // Visible
    visible: Property<boolean>;
    // MaxWidth
    maxWidth: Property<ElementSize>;
}

