/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { FontStyle } from '@/shared/protocol/ora/fontStyle';
import type { FontWeight } from '@/shared/protocol/ora/fontWeight';
import type { Length } from '@/shared/protocol/ora/length';

export interface Font {
	/**
	 * Name of the font or family name as fallback. Extra fallback declarations are unspecified and must be comma
	 * separated.
	 */
	// Name
	n /*omitempty*/? /*Name*/ : string;

	/**
	 * Size of the font
	 */
	// Size
	s /*omitempty*/? /*Size*/ : Length;
	// Style
	t /*omitempty*/? /*Style*/ : FontStyle;
	// Weight
	w /*omitempty*/? /*Weight*/ : FontWeight;
}
