/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Length } from '@/shared/protocol/ora/length';

export interface Frame {

    /**
     * MinWidth is omitted if empty
     */
    minWidth/*omitempty*/? /*MinWidth*/: Length;

    /**
     * MaxWidth is omitted if empty
     */
    maxWidth/*omitempty*/? /*MaxWidth*/: Length;

    /**
     * MinHeight is omitted if empty
     */
    minHeight/*omitempty*/? /*MinHeight*/: Length;

    /**
     * MaxHeight is omitted if empty
     */
    maxHeight/*omitempty*/? /*MaxHeight*/: Length;

    /**
     * Width is omitted if empty
     */
    width/*omitempty*/? /*Width*/: Length;

    /**
     * Height is omitted if empty
     */
    height/*omitempty*/? /*Height*/: Length;
}

