/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Length } from '@/shared/protocol/ora/length';

export interface Frame {

    /**
     * MinWidth is omitted if empty
     */
    wi/*omitempty*/? /*MinWidth*/: Length;

    /**
     * MaxWidth is omitted if empty
     */
    wx/*omitempty*/? /*MaxWidth*/: Length;

    /**
     * MinHeight is omitted if empty
     */
    hi/*omitempty*/? /*MinHeight*/: Length;

    /**
     * MaxHeight is omitted if empty
     */
    hx/*omitempty*/? /*MaxHeight*/: Length;

    /**
     * Width is omitted if empty
     */
    w/*omitempty*/? /*Width*/: Length;

    /**
     * Height is omitted if empty
     */
    h/*omitempty*/? /*Height*/: Length;
}

