/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { GridCell } from '@/shared/protocol/ora/gridCell';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

/**
 * TODO this entire type is so HTML like and hard to handle and port to mobile devices. It has no semantics.
 * 
 * I vote for deletion, but what is the replacement?
 * 
 * deprecated: use flexcontainer
 */
export interface Grid {
    id /*Ptr*/: Ptr;
    type: 'Grid'/*ComponentType*/;
    cells: Property<GridCell[]>;
    rows: Property<number /*int64*/>;
    columns: Property<number /*int64*/>;
    smColumns /*SMColumns*/: Property<number /*int64*/>;
    mdColumns /*MDColumns*/: Property<number /*int64*/>;
    lgColumns /*LGColumns*/: Property<number /*int64*/>;
    gap: Property<string>;
}

