/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { GridCell } from '@/shared/protocol/ora/gridCell';
import type { Length } from '@/shared/protocol/ora/length';

/**
 * A Grid must support up to 12 Columns and a reasonable "unlimited" amount of rows.
 */
export interface Grid {
    // Type
    type: 'G'/*ComponentType*/;
    // Cells
    b/*omitempty*/? /*Cells*/: GridCell[];
    // Rows
    r/*omitempty*/? /*Rows*/: number /*int64*/;
    // Columns
    c/*omitempty*/? /*Columns*/: number /*int64*/;
    // Gap
    g/*omitempty*/? /*Gap*/: Length;
}

