/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Component } from '@/shared/protocol/ora/component';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

/**
 * TODO this entire type is so HTML like and hard to handle and port to mobile devices. It has no semantics.
 * 
 * I vote for deletion, but what is the replacement?
 * 
 * deprecated
 */
export interface GridCell {
    id /*Ptr*/: Ptr;
    type: 'GridCell'/*ComponentType*/;
    body: Property<Component>;
    colStart: Property<number /*int64*/>;
    colEnd: Property<number /*int64*/>;
    rowStart: Property<number /*int64*/>;
    rowEnd: Property<number /*int64*/>;
    colSpan: Property<number /*int64*/>;
    smColSpan: Property<number /*int64*/>;
    mdColSpan: Property<number /*int64*/>;
    lgColSpan: Property<number /*int64*/>;
}

