// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { Component } from '@/shared/protocol/ora/component';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export class HBox {
    private _id : Ptr;
    private _type : ComponentType;
    private _children : Property<Component[]>;
    private _alignment : Property<string>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get children(): Property<Component[]>{
        return this._children;
    }
    set children(value: Property<Component[]>){
        this._children = value;
    }
    get alignment(): Property<string>{
        return this._alignment;
    }
    set alignment(value: Property<string>){
        this._alignment = value;
    }
}

