/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */



export interface HSLColor {
    // H
    h: number /*float64*/;
    // S
    s: number /*float64*/;
    // L
    l: number /*float64*/;
}

