// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { ComponentType } from '@/shared/protocol/ora/componentType';

export class Image {
    private _id : Ptr;
    private _type : ComponentType;
    private _url : Property<string>;
    private _downloadToken : Property<string>;
    private _caption : Property<string>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get uRL(): Property<string>{
        return this._url;
    }
    set uRL(value: Property<string>){
        this._url = value;
    }
    get downloadToken(): Property<string>{
        return this._downloadToken;
    }
    set downloadToken(value: Property<string>){
        this._downloadToken = value;
    }
    get caption(): Property<string>{
        return this._caption;
    }
    set caption(value: Property<string>){
        this._caption = value;
    }
}

