/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface Image {
    id /*Ptr*/: Ptr;
    type: 'Image'/*ComponentType*/;
    url /*URL*/: Property<string>;
    downloadToken: Property<string>;
    caption: Property<string>;
}

