/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { KeyboardType } from '@/shared/protocol/ora/keyboardType';

export interface KeyboardOptions {
	// Capitalization
	c /*omitempty*/? /*Capitalization*/ : boolean;
	// AutoCorrectEnabled
	a /*omitempty*/? /*AutoCorrectEnabled*/ : boolean;
	// KeyboardType
	k /*omitempty*/? /*KeyboardType*/ : KeyboardType;
}
