/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { Length } from '@/shared/protocol/ora/length';

export interface Lengths {
	// CustomLengths
	customLengths: Record<string, Length>;
}
