/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */

/**
 * why is this so stupid? Because it is more or less impossible (because so ineffective) to parse
 * adjacent encoded types in typescript.
 */
export type Length = string;
