/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Length } from '@/shared/protocol/ora/length';

export interface LengthRule {
    // Name
    name: string;
    // MinWidth
    minWidth: Length;
    // Value
    value: Length;
}

