/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { MenuEntry } from '@/shared/protocol/ora/menuEntry';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface MenuEntry {
	// Ptr
	id /*Ptr*/ : Ptr;
	// Type
	type: 'MenuEntry' /*ComponentType*/;
	// Icon
	icon: Property;
	// IconActive
	iconActive: Property;
	// Title
	title: Property<string>;
	// Action
	action: Property<Ptr>;
	// ComponentFactoryId
	componentFactoryId: Property<string>;
	// Menu
	menu: Property<MenuEntry[]>;
	// Badge
	badge: Property<string>;
	// Expanded
	expanded: Property<boolean>;
	// OnFocus
	onFocus: Property<Ptr>;
}
