/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { MenuEntry } from '@/shared/protocol/ora/menuEntry';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { SVG } from '@/shared/protocol/ora/sVG';

export interface MenuEntry {
    id /*Ptr*/: Ptr;
    type: 'MenuEntry'/*ComponentType*/;
    icon: Property<SVG>;
    iconActive: Property<SVG>;
    title: Property<string>;
    action: Property<Ptr>;
    componentFactoryId: Property<string>;
    menu: Property<MenuEntry[]>;
    badge: Property<string>;
    expanded: Property<boolean>;
    onFocus: Property<Ptr>;
}

