/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */



/**
 * NamedColor specifies the color, style or even semantics for the user when using a component.
 * See also https://experience.sap.com/fiori-design-web/how-to-use-semantic-colors/.
 */
export type NamedColor = string 
