// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { EventType } from '@/shared/protocol/ora/eventType';

// NavigationBackRequested steps back causing a likely destruction of the most top component.
// The frontend may deora.Ptre to ignore that, if the stack would be empty/undefined otherwise.
export class NavigationBackRequested {
    private _type : EventType;
    get type(): EventType{
        return this._type;
    }
    set type(value: EventType){
        this._type = value;
    }
}

