// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { ComponentFactoryId } from '@/shared/protocol/ora/componentFactoryId';
import type { EventType } from '@/shared/protocol/ora/eventType';

// NavigationResetRequested removes the entire history in the scope and pushes the target on top.
export class NavigationResetRequested {
    private _type : EventType;
    private _factory : ComponentFactoryId;
    private _values : Record<string,string>;
    get type(): EventType{
        return this._type;
    }
    set type(value: EventType){
        this._type = value;
    }
    get factory(): ComponentFactoryId{
        return this._factory;
    }
    set factory(value: ComponentFactoryId){
        this._factory = value;
    }
    get values(): Record<string,string>{
        return this._values;
    }
    set values(value: Record<string,string>){
        this._values = value;
    }
}

