/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentFactoryId } from '@/shared/protocol/ora/componentFactoryId';
import type { EventType } from '@/shared/protocol/ora/eventType';

/**
 * NavigationForwardToRequested is an Event triggered by the backend which requests a forward navigation action within the frontend.
 * A frontend must put the new component to create by the factory on top of the current component within the scope.
 * The frontend is free keep multiple components alive at the same time, however it must ensure that the UX is sane.
 */
export interface NavigationForwardToRequested {
    type: 'NavigationForwardToRequested'/*EventType*/;
    factory: ComponentFactoryId;
    values: Record<string,string>;
}

