/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentFactoryId } from '@/shared/protocol/ora/componentFactoryId';
import type { EventType } from '@/shared/protocol/ora/eventType';

/**
 * NavigationResetRequested removes the entire history in the scope and pushes the target on top.
 */
export interface NavigationResetRequested {
    type: 'NavigationResetRequested'/*EventType*/;
    factory: ComponentFactoryId;
    values: Record<string,string>;
}

