/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface NumberField {
    id /*Ptr*/: Ptr;
    type: 'NumberField'/*ComponentType*/;
    label: Property<string>;
    hint: Property<string>;
    error: Property<string>;
    value: Property<string>;
    placeholder: Property<string>;
    disabled: Property<boolean>;
    simple: Property<boolean>;
    onValueChanged: Property<Ptr>;
    visible: Property<boolean>;
}

