/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Length } from '@/shared/protocol/ora/length';

export interface Padding {
    t/*omitempty*/? /*Top*/: Length;
    l/*omitempty*/? /*Left*/: Length;
    r/*omitempty*/? /*Right*/: Length;
    b/*omitempty*/? /*Bottom*/: Length;
}

