/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Length } from '@/shared/protocol/ora/length';

export interface Padding {
    // Top
    t/*omitempty*/? /*Top*/: Length;
    // Left
    l/*omitempty*/? /*Left*/: Length;
    // Right
    r/*omitempty*/? /*Right*/: Length;
    // Bottom
    b/*omitempty*/? /*Bottom*/: Length;
}

