/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface PasswordField {
    id /*Ptr*/: Ptr;
    type: 'PasswordField'/*ComponentType*/;
    label: Property<string>;
    hint: Property<string>;
    help: Property<string>;
    error: Property<string>;
    value: Property<string>;
    revealed: Property<boolean>;
    placeholder: Property<string>;
    disabled: Property<boolean>;
    simple: Property<boolean>;
    onPasswordChanged: Property<Ptr>;
    visible: Property<boolean>;
}

