// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export class PasswordField {
    private _id : Ptr;
    private _type : ComponentType;
    private _label : Property<string>;
    private _hint : Property<string>;
    private _help : Property<string>;
    private _error : Property<string>;
    private _value : Property<string>;
    private _revealed : Property<boolean>;
    private _placeholder : Property<string>;
    private _disabled : Property<boolean>;
    private _simple : Property<boolean>;
    private _onPasswordChanged : Property<Ptr>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get label(): Property<string>{
        return this._label;
    }
    set label(value: Property<string>){
        this._label = value;
    }
    get hint(): Property<string>{
        return this._hint;
    }
    set hint(value: Property<string>){
        this._hint = value;
    }
    get help(): Property<string>{
        return this._help;
    }
    set help(value: Property<string>){
        this._help = value;
    }
    get error(): Property<string>{
        return this._error;
    }
    set error(value: Property<string>){
        this._error = value;
    }
    get value(): Property<string>{
        return this._value;
    }
    set value(value: Property<string>){
        this._value = value;
    }
    get revealed(): Property<boolean>{
        return this._revealed;
    }
    set revealed(value: Property<boolean>){
        this._revealed = value;
    }
    get placeholder(): Property<string>{
        return this._placeholder;
    }
    set placeholder(value: Property<string>){
        this._placeholder = value;
    }
    get disabled(): Property<boolean>{
        return this._disabled;
    }
    set disabled(value: Property<boolean>){
        this._disabled = value;
    }
    get simple(): Property<boolean>{
        return this._simple;
    }
    set simple(value: Property<boolean>){
        this._simple = value;
    }
    get onPasswordChanged(): Property<Ptr>{
        return this._onPasswordChanged;
    }
    set onPasswordChanged(value: Property<Ptr>){
        this._onPasswordChanged = value;
    }
}

