/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { EventType } from '@/shared/protocol/ora/eventType';

export interface Ping {
    // Type
    type: 'Ping'/*EventType*/;
}

