/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

/**
 * TODO @Lukas/Philip/Kristin: sollte das nicht auch ein Label und Hint haben?
 */
export interface ProgressBar {
	// Ptr
	id /*Ptr*/ : Ptr;
	// Type
	type: 'ProgressBar' /*ComponentType*/;
	// Max
	max: Property<number /*float64*/>;
	// Value
	value: Property<number /*float64*/>;
	// ShowPercentage
	showPercentage: Property<boolean>;
}
