/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface ProgressBar {
    id /*Ptr*/: Ptr;
    type: 'ProgressBar'/*ComponentType*/;
    max: Property<number /*float64*/>;
    value: Property<number /*float64*/>;
}

