// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { Ptr } from '@/shared/protocol/ora/ptr';

// Property represents the current value of an allocated property which is uniquely addressed through a pointer
// within the backend process.
// Note, that these pointers are not real pointers and only unique and valid for a specific scope.
export class Property<T> {
    private _p : Ptr;
    private _v : T;
    get ptr(): Ptr{
        return this._p;
    }
    set ptr(value: Ptr){
        this._p = value;
    }
    get value(): T{
        return this._v;
    }
    set value(value: T){
        this._v = value;
    }
}

