/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Ptr } from '@/shared/protocol/ora/ptr';

/**
 * Property represents the current value of an allocated property which is uniquely addressed through a pointer
 * within the backend process.
 * Note, that these pointers are not real pointers and only unique and valid for a specific scope.
 */
export interface Property<T> {

    /**
     * Ptr is short for "Pointer" and references a property instance within the backend.
     * Because it is so common, the json field name is just p.
     */
    p /*Ptr*/: Ptr;

    /**
     * Value contains the actual value specified by the generic type parameter and shortend to v in json.
     */
    v /*Value*/: T;
}

