// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { SVG } from '@/shared/protocol/ora/sVG';
import type { RIDSVG } from '@/shared/protocol/ora/rIDSVG';

export class Resources {
    private _svgs : Record<RIDSVG,SVG>;
    get sVG(): Record<RIDSVG,SVG>{
        return this._svgs;
    }
    set sVG(value: Record<RIDSVG,SVG>){
        this._svgs = value;
    }
}

