/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { RIDSVG } from '@/shared/protocol/ora/rIDSVG';
import type { SVG } from '@/shared/protocol/ora/sVG';

export interface Resources {
    // SVG
    svgs /*SVG*/: Record<RIDSVG,SVG>;
}

