/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { Component } from '@/shared/protocol/ora/component';
import type { ComponentFactoryId } from '@/shared/protocol/ora/componentFactoryId';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface ScaffoldMenuEntry {
	// Icon
	i /*omitempty*/? /*Icon*/ : Component;
	// IconActive
	v /*omitempty*/? /*IconActive*/ : Component;
	// Title
	t /*omitempty*/? /*Title*/ : string;
	// Action
	a /*omitempty*/? /*Action*/ : Ptr;
	// Factory
	f /*omitempty*/? /*Factory*/ : ComponentFactoryId;
	// Menu
	m /*omitempty*/? /*Menu*/ : ScaffoldMenuEntry[];
	// Badge
	b /*omitempty*/? /*Badge*/ : string;
	// Expanded
	x /*omitempty*/? /*Expanded*/ : boolean;
}
