/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Component } from '@/shared/protocol/ora/component';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { NavigationComponent } from '@/shared/protocol/ora/navigationComponent';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface Scaffold {
    // Ptr
    id /*Ptr*/: Ptr;
    // Type
    type: 'Scaffold'/*ComponentType*/;
    // Body
    body: Property<Component>;
    // NavigationComponent
    navigationComponent: Property<NavigationComponent>;
}

