/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Alignment } from '@/shared/protocol/ora/alignment';
import type { Component } from '@/shared/protocol/ora/component';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { ScaffoldMenuEntry } from '@/shared/protocol/ora/scaffoldMenuEntry';

/**
 * Scaffold is only defined as a root view. Other use cases are undefined and will likely break the rendering.
 */
export interface Scaffold {
    // Type
    type: 'A'/*ComponentType*/;
    // Body
    b/*omitempty*/? /*Body*/: Component;
    // Logo
    l/*omitempty*/? /*Logo*/: Component;
    // Menu
    m/*omitempty*/? /*Menu*/: ScaffoldMenuEntry[];

    /**
     * Alignment defaults to Leading (usually Left).
     */
    // Alignment
    a/*omitempty*/? /*Alignment*/: Alignment;
}

