/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Border } from '@/shared/protocol/ora/border';
import type { Color } from '@/shared/protocol/ora/color';
import type { Component } from '@/shared/protocol/ora/component';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Frame } from '@/shared/protocol/ora/frame';
import type { Padding } from '@/shared/protocol/ora/padding';
import type { ScrollViewAxis } from '@/shared/protocol/ora/scrollViewAxis';

/**
 * A ScrollView can either be horizontal or vertical.
 */
export interface ScrollView {
    // Type
    type: 'V'/*ComponentType*/;
    // Content
    c/*omitempty*/? /*Content*/: Component;
    // Axis
    a/*omitempty*/? /*Axis*/: ScrollViewAxis;
    // Invisible
    iv/*omitempty*/? /*Invisible*/: boolean;
    // Border
    b/*omitempty*/? /*Border*/: Border;
    // Frame
    f/*omitempty*/? /*Frame*/: Frame;
    // Padding
    p/*omitempty*/? /*Padding*/: Padding;
    // BackgroundColor
    bgc/*omitempty*/? /*BackgroundColor*/: Color;
}

