/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { EventType } from '@/shared/protocol/ora/eventType';

/**
 * SessionAssigned must not be used by browser clients directly.
 * A http channel implementation must issue this by itself due to security concerns like http-only cookies.
 * Native client (mobile or desktop) should use this event instead.
 */
export interface SessionAssigned {
    type: 'SessionAssigned'/*EventType*/;
    sessionID: string;
}

