// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { RequestId } from '@/shared/protocol/ora/requestId';
import type { EventType } from '@/shared/protocol/ora/eventType';

export class SetPropertyValueRequested {
    private _type : EventType;
    private _p : Ptr;
    private _v : string;
    private _r : RequestId;
    get type(): EventType{
        return this._type;
    }
    set type(value: EventType){
        this._type = value;
    }
    get ptr(): Ptr{
        return this._p;
    }
    set ptr(value: Ptr){
        this._p = value;
    }
    get value(): string{
        return this._v;
    }
    set value(value: string){
        this._v = value;
    }
    get requestId(): RequestId{
        return this._r;
    }
    set requestId(value: RequestId){
        this._r = value;
    }
}

