/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { Color } from '@/shared/protocol/ora/color';
import type { Length } from '@/shared/protocol/ora/length';

export interface Shadow {
	// Color
	c /*omitempty*/? /*Color*/ : Color;
	// Radius
	r /*omitempty*/? /*Radius*/ : Length;
	// X
	x /*omitempty*/? /*X*/ : Length;
	// Y
	y /*omitempty*/? /*Y*/ : Length;
}
