/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Border } from '@/shared/protocol/ora/border';
import type { Length } from '@/shared/protocol/ora/length';

func shadow(radius Length,)(Border,){
}
