/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Length } from '@/shared/protocol/ora/length';
import type { NamedColor } from '@/shared/protocol/ora/namedColor';

export interface Shadow {
    // Color
    c/*omitempty*/? /*Color*/: NamedColor;
    // Radius
    r/*omitempty*/? /*Radius*/: Length;
    // X
    x/*omitempty*/? /*X*/: Length;
    // Y
    y/*omitempty*/? /*Y*/: Length;
}

