/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface Slider {
    id /*Ptr*/: Ptr;
    type: 'Slider'/*ComponentType*/;
    disabled: Property<boolean>;
    label: Property<string>;
    hint: Property<string>;
    error: Property<string>;
    rangeMode: Property<boolean>;
    startValue: Property<number /*float64*/>;
    endValue: Property<number /*float64*/>;
    min: Property<number /*float64*/>;
    max: Property<number /*float64*/>;
    stepsize: Property<number /*float64*/>;
    startInitialized: Property<boolean>;
    endInitialized: Property<boolean>;
    showLabel: Property<boolean>;
    labelSuffix: Property<string>;
    showTickMarks: Property<boolean>;
    onChanged: Property<Ptr>;
}

