/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Border } from '@/shared/protocol/ora/border';
import type { Color } from '@/shared/protocol/ora/color';
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Frame } from '@/shared/protocol/ora/frame';

/**
 * Spacer grows or shrinks within a HStack or VStack. In other layouts, the behavior is unspecified.
 */
export interface Spacer {
    // Type
    type: 's'/*ComponentType*/;
    // Frame
    f /*Frame*/: Frame;
    // Border
    b /*Border*/: Border;
    // BackgroundColor
    bgc /*BackgroundColor*/: Color;
}

