// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export class StepInfo {
    private _id : Ptr;
    private _type : ComponentType;
    private _number : Property<string>;
    private _caption : Property<string>;
    private _details : Property<string>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get number(): Property<string>{
        return this._number;
    }
    set number(value: Property<string>){
        this._number = value;
    }
    get caption(): Property<string>{
        return this._caption;
    }
    set caption(value: Property<string>){
        this._caption = value;
    }
    get details(): Property<string>{
        return this._details;
    }
    set details(value: Property<string>){
        this._details = value;
    }
}

