/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface StepInfo {
    id /*Ptr*/: Ptr;
    type: 'StepInfo'/*ComponentType*/;
    number: Property<string>;
    caption: Property<string>;
    details: Property<string>;
}

