/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { StepInfo } from '@/shared/protocol/ora/stepInfo';

export interface Stepper {
    id /*Ptr*/: Ptr;
    type: 'Stepper'/*ComponentType*/;
    steps: Property<StepInfo[]>;
    selectedIndex: Property<number /*int64*/>;
}

