// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { StepInfo } from '@/shared/protocol/ora/stepInfo';

export class Stepper {
    private _id : Ptr;
    private _type : ComponentType;
    private _steps : Property<StepInfo[]>;
    private _selectedIndex : Property<number>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get steps(): Property<StepInfo[]>{
        return this._steps;
    }
    set steps(value: Property<StepInfo[]>){
        this._steps = value;
    }
    get selectedIndex(): Property<number>{
        return this._selectedIndex;
    }
    set selectedIndex(value: Property<number>){
        this._selectedIndex = value;
    }
}

