/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';

/**
 * Str is a much more simple text type, which will never have special formatting options.
 * We introduced this, because our protocol encoding is so bloated by definition, that we must allocate
 * all properties and even send them over wire. In larger tables this creates mind-blowing render trees with
 * dozens of MiB in transfer size. Also, neither is the websocket compression working nor is it effective in practice.
 */
export interface Str {
    type: 'S'/*ComponentType*/;
    v,omitempty /*Value*/: string;
}

