/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Color } from '@/shared/protocol/ora/color';
import type { Length } from '@/shared/protocol/ora/length';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { TableCell } from '@/shared/protocol/ora/tableCell';

/**
 * TableRow p
 */
export interface TableRow {
    // Cells
    c/*omitempty*/? /*Cells*/: TableCell[];
    // Height
    h/*omitempty*/? /*Height*/: Length;
    // BackgroundColor
    b/*omitempty*/? /*BackgroundColor*/: Color;
    // Action
    a/*omitempty*/? /*Action*/: Ptr;
}

