/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { TableCell } from '@/shared/protocol/ora/tableCell';
import type { TableRow } from '@/shared/protocol/ora/tableRow';

export interface Table {
    // Ptr
    id /*Ptr*/: Ptr;
    // Type
    type: 'Table'/*ComponentType*/;
    // Headers
    headers: Property<TableCell[]>;
    // Rows
    rows: Property<TableRow[]>;
}

