// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { TableCell } from '@/shared/protocol/ora/tableCell';

export class TableRow {
    private _id : Ptr;
    private _type : ComponentType;
    private _cells : Property<TableCell[]>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get cells(): Property<TableCell[]>{
        return this._cells;
    }
    set cells(value: Property<TableCell[]>){
        this._cells = value;
    }
}

