/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { Alignment } from '@/shared/protocol/ora/alignment';
import type { Border } from '@/shared/protocol/ora/border';
import type { Color } from '@/shared/protocol/ora/color';
import type { Component } from '@/shared/protocol/ora/component';
import type { Length } from '@/shared/protocol/ora/length';
import type { Padding } from '@/shared/protocol/ora/padding';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface TableColumn {
	// Content
	c /*omitempty*/? /*Content*/ : Component;

	/**
	 * Values higher than 1000 are clipped.
	 */
	// ColSpan
	cs /*omitempty*/? /*ColSpan*/ : number /*int*/;
	// Width
	w /*omitempty*/? /*Width*/ : Length;
	// Alignment
	a /*omitempty*/? /*Alignment*/ : Alignment;
	// CellBackgroundColor
	b /*omitempty*/? /*CellBackgroundColor*/ : Color;
	// CellAction
	t /*omitempty*/? /*CellAction*/ : Ptr;
	// CellPadding
	p /*omitempty*/? /*CellPadding*/ : Padding;
	// CellBorder
	o /*omitempty*/? /*CellBorder*/ : Border;
	// CellHoveredBackgroundColor
	k /*omitempty*/? /*CellHoveredBackgroundColor*/ : Color;
	// CellHovered
	cellHovered /*omitempty*/? /*CellHovered*/ : boolean;
}
