/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { TableCell } from '@/shared/protocol/ora/tableCell';

export interface TableRow {
    // Ptr
    id /*Ptr*/: Ptr;
    // Type
    type: 'TableRow'/*ComponentType*/;
    // Cells
    cells: Property<TableCell[]>;
}

