/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { TableColumn } from '@/shared/protocol/ora/tableColumn';

/**
 * TableHeader aggregates the optional header properties and defines columns from left to right.
 * We are not assigning cells to columns by id, to lower the protocol overhead.
 */
export interface TableHeader {
	// Columns
	c /*omitempty*/? /*Columns*/ : TableColumn[];
}
