/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface TextArea {
    id /*Ptr*/: Ptr;
    type: 'TextArea'/*ComponentType*/;
    label: Property<string>;
    hint: Property<string>;
    error: Property<string>;
    value: Property<string>;
    rows: Property<number /*int64*/>;
    disabled: Property<boolean>;
    onTextChanged: Property<Ptr>;
    visible: Property<boolean>;
}

