/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */

/**
 * TextAlignment constants are
 *
 * - start (left) = s
 * - end (right) = e
 * - center = c
 * - justify = j
 */
export type TextAlignment = string;
