/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Frame } from '@/shared/protocol/ora/frame';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface TextField {
    id /*Ptr*/: Ptr;
    type: 'TextField'/*ComponentType*/;
    label: Property<string>;
    hint: Property<string>;
    help: Property<string>;
    error: Property<string>;
    value: Property<string>;
    placeholder: Property<string>;
    disabled: Property<boolean>;
    simple: Property<boolean>;
    onTextChanged: Property<Ptr>;

    /**
     * OnDebouncedTextChanged is called, after no changes within the DebounceTime have been seen.
     * Note that the frontend is allowed to suppress any property updates, until the debouncer kicks in.
     * This is by intention, to ensure that the backend does not re-render anyway due to always dirty views.
     */
    onDebouncedTextChanged: Property<Ptr>;
    debounceTime: Property<number /*int64*/>;
    visible: Property<boolean>;
    frame/*omitempty*/? /*Frame*/: Frame;
}

