/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Frame } from '@/shared/protocol/ora/frame';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface TextField {
    // Type
    type: 'TextField'/*ComponentType*/;
    // Label
    label: string;
    // Hint
    hint: string;
    // Help
    help: string;
    // Error
    error: string;
    // Text
    value /*Text*/: Property<string>;
    // Placeholder
    placeholder: string;
    // Disabled
    disabled: boolean;
    // Simple
    simple: boolean;
    // OnTextChanged
    onTextChanged: Ptr;

    /**
     * OnDebouncedTextChanged is called, after no changes within the DebounceTime have been seen.
     * Note that the frontend is allowed to suppress any property updates, until the debouncer kicks in.
     * This is by intention, to ensure that the backend does not re-render anyway due to always dirty views.
     */
    // OnDebouncedTextChanged
    onDebouncedTextChanged: Ptr;
    // DebounceTime
    debounceTime: number /*int64*/;
    // Invisible
    visible /*Invisible*/: boolean;
    // Frame
    frame/*omitempty*/? /*Frame*/: Frame;
}

