// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { Colors } from '@/shared/protocol/ora/colors';

export class Theme {
    private _colors : Colors;
    get colors(): Colors{
        return this._colors;
    }
    set colors(value: Colors){
        this._colors = value;
    }
}

