// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { Theme } from '@/shared/protocol/ora/theme';

export class Themes {
    private _dark : Theme;
    private _light : Theme;
    private _highContrast : Theme;
    private _protanopie : Theme;
    private _deuteranopie : Theme;
    private _tritanopie : Theme;
    get dark(): Theme{
        return this._dark;
    }
    set dark(value: Theme){
        this._dark = value;
    }
    get light(): Theme{
        return this._light;
    }
    set light(value: Theme){
        this._light = value;
    }
    get highContrast(): Theme{
        return this._highContrast;
    }
    set highContrast(value: Theme){
        this._highContrast = value;
    }
    get protanopie(): Theme{
        return this._protanopie;
    }
    set protanopie(value: Theme){
        this._protanopie = value;
    }
    get deuteranopie(): Theme{
        return this._deuteranopie;
    }
    set deuteranopie(value: Theme){
        this._deuteranopie = value;
    }
    get tritanopie(): Theme{
        return this._tritanopie;
    }
    set tritanopie(value: Theme){
        this._tritanopie = value;
    }
}

