/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ColorRule } from '@/shared/protocol/ora/colorRule';
import type { LengthRule } from '@/shared/protocol/ora/lengthRule';
import type { Theme } from '@/shared/protocol/ora/theme';

export interface Themes {
    // Colors
    colors: ColorRule[];
    // Lengths
    lengths: LengthRule[];
    // Dark
    dark: Theme;
    // Light
    light: Theme;
    // HighContrast
    highContrast: Theme;
    // Protanopie
    protanopie: Theme;
    // Deuteranopie
    deuteranopie: Theme;
    // Tritanopie
    tritanopie: Theme;
}

