/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Colors } from '@/shared/protocol/ora/colors';
import type { Lengths } from '@/shared/protocol/ora/lengths';

export interface Theme {
    // Colors
    colors: Colors;
    // Lengths
    lengths: Lengths;
}

