/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { Theme } from '@/shared/protocol/ora/theme';

export interface Themes {
    // Dark
    dark: Theme;
    // Light
    light: Theme;
    // HighContrast
    highContrast: Theme;
    // Protanopie
    protanopie: Theme;
    // Deuteranopie
    deuteranopie: Theme;
    // Tritanopie
    tritanopie: Theme;
}

