/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { Color } from '@/shared/protocol/ora/color';
import type { Lengths } from '@/shared/protocol/ora/lengths';
import type { NamespaceName } from '@/shared/protocol/ora/namespaceName';

export interface Theme {
	// Colors
	colors: Record<NamespaceName, Record<string, Color>>;
	// Lengths
	lengths: Lengths;
}
