// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';
import type { ComponentType } from '@/shared/protocol/ora/componentType';

export class Toggle {
    private _id : Ptr;
    private _type : ComponentType;
    private _label : Property<string>;
    private _checked : Property<boolean>;
    private _disabled : Property<boolean>;
    private _onCheckedChanged : Property<Ptr>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get label(): Property<string>{
        return this._label;
    }
    set label(value: Property<string>){
        this._label = value;
    }
    get checked(): Property<boolean>{
        return this._checked;
    }
    set checked(value: Property<boolean>){
        this._checked = value;
    }
    get disabled(): Property<boolean>{
        return this._disabled;
    }
    set disabled(value: Property<boolean>){
        this._disabled = value;
    }
    get onCheckedChanged(): Property<Ptr>{
        return this._onCheckedChanged;
    }
    set onCheckedChanged(value: Property<Ptr>){
        this._onCheckedChanged = value;
    }
}

