/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Ptr } from '@/shared/protocol/ora/ptr';

/**
 * Toggle is just a kind of checkbox without a label.
 */
export interface Toggle {
    // Type
    type: 't'/*ComponentType*/;

    /**
     * Value is the initial checked value.
     */
    // Value
    v/*omitempty*/? /*Value*/: boolean;

    /**
     * InputValue is where updated value of the checked states are written.
     */
    // InputValue
    i/*omitempty*/? /*InputValue*/: Ptr;
    // Disabled
    d/*omitempty*/? /*Disabled*/: boolean;
    // Invisible
    iv/*omitempty*/? /*Invisible*/: boolean;
}

