// Code generated by github.com/worldiety/macro. DO NOT EDIT.


import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export class WebView {
    private _id : Ptr;
    private _type : ComponentType;
    private _value : Property<string>;
    get ptr(): Ptr{
        return this._id;
    }
    set ptr(value: Ptr){
        this._id = value;
    }
    get type(): ComponentType{
        return this._type;
    }
    set type(value: ComponentType){
        this._type = value;
    }
    get value(): Property<string>{
        return this._value;
    }
    set value(value: Property<string>){
        this._value = value;
    }
}

