/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { ComponentType } from '@/shared/protocol/ora/componentType';
import type { Property } from '@/shared/protocol/ora/property';
import type { Ptr } from '@/shared/protocol/ora/ptr';

export interface WebView {
	// Ptr
	id /*Ptr*/ : Ptr;
	// Type
	type: 'WebView' /*ComponentType*/;
	// Value
	value: Property<string>;
}
