/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */



/**
 * Weight is between 0-1 and can be understood as 1 = 100%, however implementations must normalize the total
 * of all weights and recalculate the effective percentage.
 */
export type Weight = number /*float64*/ 
