/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */


import type { EventType } from '@/shared/protocol/ora/eventType';
import type { WindowInfo } from '@/shared/protocol/ora/windowInfo';

/**
 * WindowInfoChanged is raised by the frontend whenever the window metrics changed in a significant way.
 * It is not guaranteed that every pixel change will trigger such an event.
 * However, a frontend must guarantee to send such an event if the WindowSizeClass is changed.
 */
export interface WindowInfoChanged {
    type: 'WindowInfoChanged'/*EventType*/;
    info: WindowInfo;
}

