/**
 * Code generated by github.com/worldiety/macro. DO NOT EDIT.
 */
import type { ComponentType } from '@/shared/protocol/ora/componentType';

/**
 * WindowTitle is an invisible component which teleports its Value into the current active window navigation title.
 */
export interface WindowTitle {
	// Type
	type: 'W' /*ComponentType*/;
	// Value
	v /*omitempty*/? /*Value*/ : string;
}
